### ISSUE TITLE
Add Magic Leap SDK and build tools

### ISSUE THREAD

**Issue by StephenHodgson** [actions/virtual-environments#1022]
**Tool information**
- Tool name: Magic Leap SDK
- Tool license:  https://id.magicleap.com/terms/developer
- Add or update? Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Magic Leap SDK tools for building to the Magic Leap One device
  - URL for tool's homepage: https://developer.magicleap.com/downloads/lab

**Area for Triage**:

Packages

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

No, it cannot. 

1. Download The Lab from the developer page
2. Login
3. Download SDK and build tools from the embedded package manager
4. Add `MLSDK` to environment path

**Tool installation time in runtime**

**Are you willing to submit a PR?**

No, as I'm unsure how to add this tool without manual steps.

**Comment by al-cheb** [comment]
Hello, @StephenHodgson 

Sorry, but we can pre-installed `Magic Leap SDK` on Windows/macOS images due to policy license agreement - https://www.magicleap.com/en-us/legal/software-eula

#### 2. RESERVATION OF RIGHTS AND RESTRICTIONS

#### 2.1 
The Lumin Software is licensed and not sold. Magic Leap and its licensors retain all right, title and interest in and to the Lumin Software, and all intellectual property rights therein, including any Updates and improvements, copies, translations, adaptations, modifications, derivations and enhancements of the Lumin Software. Magic Leap does not transfer to you any right, title or interest in or to the Lumin Software.

#### 2.2 
You may not, nor allow a third party to do any of the following: (a) make any archival copies of the Lumin Software; (b) work around, interfere with, exceed, or circumvent any technical limitations or software protection measures in the Lumin Software; (c) modify, adapt, alter, rent, lease, loan or distribute the Lumin Software or use the Lumin Software in the operation of a service bureau or for the benefit of a third party; (d) reverse engineer, decompile, translate, disassemble or otherwise attempt to derive any source code of the Lumin Software (except as and only to the extent permitted by applicable law); (e) create derivative or merged works of the Lumin Software or separate the component parts of the Lumin Software; (f) input, upload, transmit or otherwise provide to or through the Lumin Software any unlawful or malicious information, materials or code;
(g) alter or remove any proprietary rights notices or legends on or in the Lumin Software; (h) use the Lumin Software in hazardous environments requiring fail-safe performance, including, without limitation, the operation of nuclear facilities, aircraft navigation, or communication systems, air traffic control, direct life support machines or weapons systems (collectively, “Restricted Use”); or (i) use the Lumin Software for thedevelopment, provision or use of a competing software service or product.

**Comment by StephenHodgson** [comment]
Ah I understand. Than for looking into this.
