### ISSUE TITLE
Andriod NDK changes on Windows

### ISSUE THREAD

**Issue by compnerd** [actions/virtual-environments#1035]
**Describe the bug**
The last Windows VM update seems to have caused some changes with the Android NDK location.  At the very least, the reported location which now contains spaces causes some problems.  Resolving the spacing issue results in `libc++.a` not being found.

**Area for Triage**: 
Android

**Question, Bug, or Feature?**: 
Bug, Question

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**
The NDK to be available at `C:\ProgramData\Microsoft\AndroidNDK`

**Actual behavior**
Using CMake to build an android executable with C++ statically linked fails.

Logs from an example run:
https://compnerd.visualstudio.com/swift-build/_build/results?buildId=33358&view=logs&jobId=f5e548e7-ba00-50d3-35db-b84d11db5ff1&j=f5e548e7-ba00-50d3-35db-b84d11db5ff1&t=4afff71e-00bf-5277-1a62-1ac69533f0db

**Comment by Darleev** [comment]
Hello @compnerd,
Yes, you are correct, ANDROID_NDK_HOME variable has been changed in scope of [pull request](https://github.com/actions/virtual-environments/pull/913). 
The current path is:` "C:\Program Files (x86)\Android\android-sdk\ndk-bundle"`
In order to properly reference this path in pipelines, you can use environment variables:
```
ANDROID_NDK_PATH
ANDROID_NDK_HOME
```
Please note that Visual Studio NDK was not removed and still available in agent machines.

**Comment by compnerd** [comment]
Hello @Darleev,

Thanks for the info, this should help me restore the builds at least temporarily.  I can get through the space issues, though, I seem to be missing `libc++.a`.  This was previously at `${ANDROID_NDK_HOME}/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++.a`.  I'll check if this is related to the NDK itself or something else.

**Comment by Darleev** [comment]
@compnerd 
Previously, Visual Studio NDK was used as a default one on Windows images.
Recently, we have switched it to the official one provided by android tool manager in scope of #913.
It was a deliberate change that was done for two reasons:
1) Visual Studio NDK is very outdated and won't be updated in the future. On our images, we would like to provide the latest ndk that will be updated in future
2) We would like to be consistent with other images because Ubuntu and macOS images use official android ndk from android tool manager
Unfortunately, we didn't expect that it could be a breaking change for someone.
Also, I checked the lib you have mentioned, and currently it is placed in the following path:
```
${ANDROID_NDK_HOME}/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++.a.16
${ANDROID_NDK_HOME}/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++.a.17
….
```
If additional information or assistance is required, feel free to contact us.

**Comment by Darleev** [comment]
@compnerd I'm going to close the issue. 
Feel free to contact us in case of any questions, we will be glad to assist you further.

**Comment by compnerd** [comment]
@Darleev - that sounds good, thanks for the information.  One quick thing - is there a good way to raise questions other than an issue?

**Comment by Darleev** [comment]
@compnerd I think the most correct option in case of any questions is to ask them as an issue, do not hesitate to contact us, we are always happy to help.
