### ISSUE TITLE
Update npm to 6.14.5: FetchError: Response timeout while trying to fetch https://pkgs.dev.azure.com/...

### ISSUE THREAD

**Issue by thijscrombeen** [actions/virtual-environments#1054]
**Describe the bug**
The specific npm version installed has a bug when trying to install packages and throws a timeout error. This is fixed in a later version of node / npm.

Is it possible to upgrade NPM from 6.14.4 to 6.14.5. This will solve the issue.

Please see 
https://github.com/npm/cli/issues/1151 
https://github.com/npm/cli/issues/1185

**Area for Triage**: 
JavaScript and Node.js

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
install npm packages

**Actual behavior**
Response timeout

verbose stack FetchError: Response timeout while trying to fetch https://pkgs.dev.azure.com/.... (over 30000ms)
1750 verbose stack     at Timeout._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:189:16)
1750 verbose stack     at listOnTimeout (internal/timers.js:549:17)
1750 verbose stack     at processTimers (internal/timers.js:492:7)

Step 1:
Use windows-latest as the virtual environment inside an azure devops build
Step 2
Add an 'npm install' step and use an azure devops package feed

**Comment by maxim-lobanov** [comment]
Hello!
We don't install NPM as a separate component. NPM is the part of Node.js installation and we wouldn't like to override it from maintenance side.
I see two options here:
1) What version of Node.js do you use? I see that Node.js 14.x uses NPM 6.14.5 by default
2) You can upgrade NPM by adding the following step / script to your pipeline: `npm install -g npm@6.14.5. It will allow you to use NPM 6.14.5 with any version of Node.js

**Comment by thijscrombeen** [comment]
Hi

When I check https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md I see that following Node.js versions are installed:
Version: 8.17.0
Version: 10.20.1
Version: 12.17.0
Version: 14.3.0

When I check the release of Node.js on https://nodejs.org/en/download/releases/ it says that 14.3.0 comes with npm 6.14.5

However https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md says that npm 6.14.4 is installed and added to the path

Adding the additional step does indeed solve the problem but I think installing npm packages using an azure devops package feed should work out of the box but that's my personal opinion

**Comment by maxim-lobanov** [comment]
Actually, we have the single version of Node.js and NPM [on image](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#nodejs): 12.17.0 and 6.14.4. We install it through choco.
Also we have 4 more versions of Node.js that are [pre-cached on image](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#node-x64): 8.17.0, 10.20.1, 12.17.0, 14.3.0. They are pre-cached on image but not used by default. To switch to it, you may use [setup-node](https://github.com/actions/setup-node) (GitHub Action) or [Node.js Tool Installer](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops) (AzDO) tasks.
If you configure this task to use Node.JS 14.3.0, NPM 6.14.5 will be used (since versions are pre-cached, switching will take less 1 second).

**Comment by maxim-lobanov** [comment]
@thijscrombeen , JFYI: Node.js 12.18.1 was released recently and it contains NPM 6.14.5.
Image with this version should be deployed in 1 week
