### ISSUE TITLE
Question: whats the best way to have same environment outside of appcenter?

### ISSUE THREAD

**Issue by Overtorment** [actions/virtual-environments#1055]
We are running builds in Appcenter, and it is a container that has following installed: https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

For the sake of verifiable/reproducible builds, how do we prepare same environment outside of Appcenter? I suppose there is no dockerfile for it, but is it available as image on Azure cloud?

**Comment by maxim-lobanov** [comment]
Hello,
Yep, App Center uses this image to run builds.
You can use [Azure DevOps ](https://azure.microsoft.com/en-us/services/devops/) or [GitHub Actions](https://help.github.com/en/actions) to run builds on the same environment. You just need to specify `macos-10.15` image in your pipeline. See related documentation how it can be done.

As for the running same environment outside Azure DevOps and GitHub Actions. Unfortunately, we don't upload this image to Azure Cloud due to legal issues.

**Comment by Overtorment** [comment]
@maxim-lobanov thanks!
Say, if I have a laptop with macOS 10.15, is there a script that installs this software..?

**Comment by maxim-lobanov** [comment]
Unfortunately, not. Source code for MacOS image-generation is not public yet. We are planning to open source it soon but no ETA for now. You can track the updates via #774
