### ISSUE TITLE
Better vcpkg support

### ISSUE THREAD

**Issue by jherico** [actions/virtual-environments#11]
The vcpkg binary exists on the target environments, but it would be _much_ more useful if the YAML could specify a specific vcpkg commit, and a set of packages required for a given build.  If the server side could recognize and cache this state, it could potentially shave an enormous amount of time off of individual builds.

**Tool information**
- Tool name: vcpkg
- Add or update? update (new functionality)

**Virtual environments affected**
- [X] macOS 10.14
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
Yes

**Are you willing to submit a PR?**
Once caching support exists in the GA syntax, yes, I would be willing to write a tool like this.

**Comment by simonsan** [comment]
I support this opinion. We're also using **vcpkg** to build dependencies ourselves, this step actually takes 10 min and is not cachable because it's outside of **GITHUB_WORKSPACE**. 

We are using `dirent eigen3 fontconfig freetype harfbuzz libepoxy libogg libpng opus opusfile sdl2 sdl2-image` so nothing special, would be nice if there would be some more packages cached or if the **cache** action gets an option to cache also the **vcpkg-dir**.

**Comment by stevencpp** [comment]
It would be helpful if someone could make an action that makes this easier, but I did it without one here: https://github.com/stevencpp/cpp_modules/blob/master/.github/workflows/build.yml . I can specify the hash of the vcpkg commit and the list of dependencies as environment variables. I can collect all of the information (compiler version, CXXFLAGS, the deps and the commit id) into a file that the cache action can use as part of the key. I used the preinstalled binary instead of bootstrapping it but chose to clone into a subfolder of the workspace which is then cached.

**Comment by simonsan** [comment]
That's pretty neat, well done! The problem is also, that the individual cache size is max. **400 MiB**, I'm pretty sure, that we are way on top of that. Not sure, if that solution is working out. Will try, though. Thank you!

**Comment by adam4813** [comment]
You just need to cache the `installed` directory under vcpkg for proper caching (saves space bot caching the buildtrees directory).

**Comment by simonsan** [comment]
Yeah, this would be still a great enhancement to the GHA...

**Comment by maxim-lobanov** [comment]
Hello, have you looked at https://github.com/actions/cache , I believe it could help you cache packages and reduce the time

**Comment by alepauly** [comment]
@jherico Thanks for the suggestion but I'm not sure we could come up with a good set of packages to precache at the virtual environment level in advance. I suggest looking at the actions/cache which along with adding `setup-vcpkg` Action could make this experience nicer.

**Comment by simonsan** [comment]
Do you mean the [run-vcpkg](https://github.com/marketplace/actions/run-vcpkg) action?

**Comment by alepauly** [comment]
> Do you mean the [run-vcpkg](https://github.com/marketplace/actions/run-vcpkg) action?

Sounds like I should have looked myself, thanks for the pointer :-)
