### ISSUE TITLE
Add TypeScript

### ISSUE THREAD

**Issue by violet-devsec** [actions/virtual-environments#1218]
**Tool information**
- Tool name: TypeScript
- Tool license: GPL
- Add or update?  Add 
- Desired version: Latest or 3.5.3
- Approximate size: 
- If this is an add request:
  - Brief description of tool: TypeScript is designed for development of large applications and transcompiles to JavaScript.
  - URL for tool's homepage: https://www.typescriptlang.org/

**Area for Triage**: Scripting and command line

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- Windows Server 2016 R2
- Windows Server 2019

**Can this tool be installed during the build?** 

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by maxim-lobanov** [comment]
Hello, we already installing TypeScript on Windows images but don't publish it in documentation since it is just NPM package: https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Install-TypeScript.ps1

Btw, what is the use case to have TypeScript pre-installed? It is pretty small NPM package that usually included to `package.json` and downloaded during `npm install`. Pre-installing TypeScript on image is some kind of pre-caching but we cache the single version and package.json can point to different one.

**Comment by violet-devsec** [comment]
Thanks for the info @maxim-lobanov. I have solved my issue by adding TypeScript to package.json. 

I had an issue with TypeScript version. But I was not sure whether TyepScript pre-installed or package.json making the issue.

**Comment by violet-devsec** [comment]
Thanks for the info @maxim-lobanov. I have solved my issue by adding TypeScript to package.json. 

I had an issue with TypeScript version. But I was not sure whether TyepScript pre-installed or package.json making the issue.

**Comment by violet-devsec** [comment]
Thanks for the info @maxim-lobanov. I have solved my issue by adding TypeScript to package.json. 

I had an issue with TypeScript version. But I was not sure whether TyepScript pre-installed or package.json making the issue.
