### ISSUE TITLE
Add R CLI tools

### ISSUE THREAD

**Issue by fnocera** [actions/virtual-environments#1220]
**Tool information**
- Tool name: R
- Tool license: GNU
- Add or update? Add
- Desired version: latest 3.x and 4.x versions
- Approximate size: 150MB
- If this is an add request:
  - Brief description of tool: R is a language and environment for statistical computing and graphics. R provides a wide variety of statistical (linear and nonlinear modelling, classical statistical tests, time-series analysis, classification, clustering, …) and graphical techniques, and is highly extensible.
  - URL for tool's homepage: https://www.r-project.org/

**Area for Triage**:
Scripting and command line

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes, though specifying specific versions can be tricky across platforms. Basic installations are:
```
### Windows
choco install R.Project
choco install rtools
 
### Ubuntu
sudo apt-get install -y r-base
 
### macOS
brew install r
```

**Tool installation time in runtime**
Windows: ~4 minutes
Ubuntu: ~1 minute
macOS: ~1 minute

**Are you willing to submit a PR?**
No

cc @margaretmeehan @jeremydelacruz

**Comment by maxim-lobanov** [comment]
Hello, thank you for your request.
We have added this issue to our backlog and will handle it soon

**Comment by gaborcsardi** [comment]
There is also an action that installs a requested R version, and it is cross platform: https://github.com/r-lib/actions/tree/master/setup-r#setup-r

**Comment by jimhester** [comment]
Is there any chance of reconsidering this? The versions of R available via the platform package managers are generally quite old, so they are often not useful in CI settings.

In addition the version of R installed by homebrew is not generally the best for macOS, rather installing the CRAN binary from the cask would be preferred, e.g. `brew cask install r`. There are some details on why this is preferred at https://rstats.wtf/set-up-an-r-dev-environment.html#what-about-homebrew.

Having an existing R on the `PATH` causes our [setup-r](https://github.com/r-lib/actions/tree/master/setup-r) action to avoid installing R, which breaks builds relying on it.

It seems there are more than 4000 workflows using this action (https://github.com/search?q=path%3A.github+%22setup-r%22&ref=opensearch), so this is a fairly severe issue.

We will change the action to unconditionally install R and workaround this issue. But generally I think it would be better for the R community not to have any R version installed by default on the images.

**Comment by maxim-lobanov** [comment]
Hello @jimhester , thank you for your feedback.
We are trying to use package managers as much as possible because they provide easiest and convenient way to install tools and usually they provide actual versions of software.
If it is wrong for R, we definitely should reconsider it.
- Windows: looks like choco provide actual version so I think it is okay to continue using it
- MacOS: we will switch to `brew cask install r`
- Ubuntu: looks like apt-get provide very outdated version 3.x, what is your suggestion for Ubuntu installation?

**Comment by jimhester** [comment]
https://cloud.r-project.org/bin/linux/ubuntu/README has instructions on obtaining newer R releases on ubuntu, perhaps that could be used here.

**Comment by jeremydelacruz** [comment]
Hello, I'm excited to see that this is being added to the images!

I wanted to ask a few questions about this. Will multiple versions of R be installed on each build agent? What would the available R versions be? If multiple versions are to be installed, will they be available in the hosted tool cache?

Thanks!

cc @fnocera @margaretmeehan

**Comment by maxim-lobanov** [comment]
Hello @jeremydelacruz , currently, we don't have plans to support multiple versions due to maintenance concerns.
Our images are updated on weekly basis and contain the latest version always.

If your use-case requires to use multiple versions and freeze old versions, I suggest to look at [setup-r](https://github.com/r-lib/actions/tree/master/setup-r#setup-r action).

**Comment by jimhester** [comment]
FWIW the `setup-r` action could benefit from R versions being available in the hosted tool cache. We use [tool-cache](https://github.com/actions/toolkit/tree/master/packages/tool-cache) in the code, but because the R versions are not hosted on GitHub there is no real benefit to it. If we could host them there then likely builds would become faster than they already are.

**Comment by dmitry-shibanov** [comment]
Hello, thank you for your response. Changes were added to all images and R version 4.0.2 is available. Feel free to raise additional threads if any.

**Comment by fnocera** [comment]
Thanks so much for adding to all images so quickly, it is much appreciated! @dmitry-shibanov @maxim-lobanov
