### ISSUE TITLE
mono nuget.exe intermittently failing with Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by schultetwin1** [actions/virtual-environments#1270]
**Describe the bug**
We use a powershell script to run nuget.exe (under mono) on the Hosted Ubuntu 18.04 virtual environment. Most of the time, the nuget restore works but sometimes the nuget restore fails with the following error:

```
WARNING: Error downloading 'Taef.UniversalTestPackages.10.46.191104001' from 'https://microsoft.pkgs.visualstudio.com/8115054f-1c74-4928-a9ab-de4769e7d6ae/_packaging/ba09f610-8053-4c83-b1e9-f1648aa3042d/nuget/v3/flat2/taef.universaltestpackages/10.46.191104001/taef.universaltestpackages.10.46.191104001.nupkg'.
The SSL connection could not be established, see inner exception.
  Authentication failed, see inner exception.
  Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
    at /build/mono-6.10.0.104/external/boringssl/ssl/handshake_client.c:1132
```

Upon some initial research, we learned that this error is expected mono/mono#12406. We attempted to run `cert-sync` but that still did not resolve our issue.

**Area for Triage**: 
Artifacts

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

One note, Ubuntu 16.04 and Ubuntu 18.04 are not tested images

**Expected behavior**
Normally, the script properly restores all the nuget packages.

**Actual behavior**
Sometimes, the build fails with the error listed above.

**Comment by Darleev** [comment]
Hello @schultetwin1,
I possibly found a very similar request in another repository https://github.com/fsprojects/Paket/issues/3009 . I believe the issue is the same, but for another version of mono.
Could you please try a workaround provided in the issue?
We are looking forward to your reply.
In the meantime, we'll take a deeper look at the issue.

**Comment by schultetwin1** [comment]
Hi @Darleev 
Thanks for the pointer. I found that issue as well. The workaround is to have mono download it's certificate store from a 3rd party. Given that these certificates will validate the authenticity of websites from which nuget will download code, we'd prefer not to grab certificates from https://curl.haxx.se/ca/cacert.pem

**Comment by Darleev** [comment]
@schultetwin1 thank you for the update.
We are investigating the issue. 
I will keep you informed.

**Comment by Darleev** [comment]
Hello @schultetwin1,
As it was mentioned above, we have a very similar issue like in https://github.com/fsprojects/Paket/issues/3009, since the workaround provided is not suitable, and [bug provided in the issue](https://xamarin.github.io/bugzilla-archives/57/57516/bug.html) is not fixed anymore. The issue is not about only Azure agent machines, but rather the mono itself.

I suggest you create another issue to investigate it on mono side.

**Comment by schultetwin1** [comment]
@Darleev , good call, I've added a comment over on the mono issue to see if we can get some guidance about how to determine if this is a configuration issue with mono or something with the Azure Pipelines image. Thanks!

**Comment by schultetwin1** [comment]
@Darleev , I was able to find a work around. If we add the flag `-DisableParallelProcessing` to `nuget.exe` (running under mono) this issue goes away. This leaves me to believe this is not an issue with the environment but instead an issue with mono itself. Closing this issue on virtual environments.
