### ISSUE TITLE
macOS + node 12/14 = e2e tests pass but "Process completed with exit code 134"

### ISSUE THREAD

**Issue by jhildenbiddle** [actions/virtual-environments#1296]
_Moving from https://github.com/microsoft/playwright/issues/3090 as this has proven to be an issue specific to the macOS environment and GitHub Actions._

**Describe the bug**

Running e2e tests (Jest + Playwright) via GitHub Actions workflow. All tests pass on all platforms (`macos-latest`, `ubuntu-latest`, and `windows-latest`), but on macOS the job fails due to `Process completed with exit code 134`:

```
Running one project: e2e
PASS browser: chromium e2e tests/e2e/example.test.js
PASS browser: firefox e2e tests/e2e/example.test.js
PASS browser: webkit e2e tests/e2e/example.test.js
PASS browser: chromium e2e tests/e2e/vue.test.js
PASS browser: firefox e2e tests/e2e/vue.test.js
PASS browser: webkit e2e tests/e2e/vue.test.js

Test Suites: 6 passed, 6 of 2 total
Tests:       24 passed, 24 total
Snapshots:   0 total
Time:        21.526 s
Ran all test suites.
Assertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 178.
/Users/runner/work/_temp/241fae1a-1600-440c-9c4a-dc01208caa50.sh: line 1:  3699 Abort trap: 6
npm run test:jest-e2e -- -ci
##[error]Process completed with exit code 134.
```

**Area for Triage**: 

JavaScript and Node.js

**Question, Bug, or Feature?**: 

Bug

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**

Expectation is that macOS will behave the same as Ubuntu and Windows environments and exit successfully given that all tests have passed.

**Actual behavior**

macOS marks the job as failed due to `Process completed with exit code 134`.

Example: https://github.com/docsifyjs/docsify/pull/1276/checks?check_run_id=907451054

**Comment by maxim-lobanov** [comment]
Hello @jhildenbiddle ,
After quick look, I have noticed:
1) Your build passed successfully with exit code 0 on Node.js 10.x but failed on the same environments with Node.js 12.x and 14.x. It means that GA build machines themselves should be correct because all builds are run on absolutely same environment.
2) We install all Node.js versions (10.x, 12.x, 14.x) directly from `https://nodejs.org` so it can't be an issue with Node.js installation.

Unfortunately, we are not familiar with playwright library to diagnose this issue deeper and I don't think that it is the image defect but I suggest to pay attention on errors in test run:
(Node.js 14.x)
```
Assertion failed: (!uv__is_closing(handle)), function uv_close, file ../deps/uv/src/unix/core.c, line 113.
/Users/runner/work/_temp/165762b5-acf4-4b33-9b90-1a875ac70bc2.sh: line 1:  2546 Abort trap: 6           npm run test:jest-e2e -- --ci
```
(Warning even on Node.js 10.x that could be potentially related)
```
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```
Probably, they could be related to issue.

Please let us know if you see any issues with image that could cause this issue.

**Comment by jhildenbiddle** [comment]
Thanks for the reply, @maxim-lobanov.

After further review I was able to identify the issue with the help of member of the playwright team (@aslushnikov and @yury-s). Details are available in an [issue](https://github.com/microsoft/playwright/issues/3090#issuecomment-664402996) I filed (and have since closed) in the playwright repo if you're interested. 

Very much appreciate the quick response. Happy to report all GitHub jobs are now passing.
