### ISSUE TITLE
Update/Add doctl

### ISSUE THREAD

**Issue by sundayoyeniyi** [actions/virtual-environments#1308]
**Tool information**
- Tool name: doctl
- Tool license: open source
- Add or update? Add
- Desired version: >= v1.46.0
- Approximate size: 
- If this is an add request:
  - Brief description of tool: It is a command line interface for digitalocean API just like that of Azure and AWS
  - URL for tool's homepage: https://github.com/digitalocean/doctl
  - Provide a basic test case to validate the tool's functionality: doctl version

**Area for Triage**:

**Question, Bug, or Feature?**:
 "Feature" 

**Virtual environments affected**
- [* ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [* ] Ubuntu 18.04 LTS
- [* ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
sudo snap install doctl

**Tool installation time in runtime**
few minutes

**Are you willing to submit a PR?**
Yes

**Comment by maxim-lobanov** [comment]
Hello, we don't have concerns about pre-installing this tool on image.
Feel free to submit PR

**Comment by maxim-lobanov** [comment]
Hello @sundayoyeniyi , returning back to this request:
There is an official action to install this tool in runtime: https://github.com/marketplace/actions/github-action-for-digitalocean-doctl
Have you tried it? Looks like it installs specific version of doctl very quick (less than 5 seconds).

**Comment by maxim-lobanov** [comment]
Hello, considering the fact that there is [official task to install doctl](https://github.com/marketplace/actions/github-action-for-digitalocean-doctl), we wouldn't like to bake this tool into the image. Task installs tool in runtime pretty quick and provide better experience than pre-installed one because task allows to specify any version of CLI and configure it right after installation.
If you see any use-cases where it makes sense to pre-install doctl to image, please let us know
