### ISSUE TITLE
Update/Add expo

### ISSUE THREAD

**Issue by chkrause** [actions/virtual-environments#1309]
**Tool information**
- Tool name: expo npm package
- Tool license: MIT
- Add or update? Add
- Desired version: latest
- Approximate size: ?
- If this is an add request:
  - Brief description of tool: Handling of Expo framework through npm
  - URL for tool's homepage: expo.io
  - Provide a basic test case to validate the tool's functionality: expo --version

*
**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
"npm install expo-cli --global"

**Tool installation time in runtime**
6 - 8 minutes

**Are you willing to submit a PR?**
no

**Comment by maxim-lobanov** [comment]
Hello @chkrause , thank you for feature request!
Have you tried [expo-github-action](https://github.com/expo/expo-github-action)? It is official expo action that allows to install specific version of expo CLI?

**Comment by maxim-lobanov** [comment]
Hello, considering the fact that there is [official task to install expo-cli](https://github.com/expo/expo-github-action), we wouldn't like to bake this tool into the image. Task installs tool in runtime pretty quick and provide better experience than pre-installed one because task allows to specify any version of CLI and configure it right after installation.
If you see any use-cases where it makes sense to pre-install expo CLI to image, please let us know
