### ISSUE TITLE
Provide images with nothing pre-installed

### ISSUE THREAD

**Issue by smorimoto** [actions/virtual-environments#1342]
Providing an image with a variety of tools pre-installed is sometimes useful, but often involves some pain. Providing a plain image should not be difficult at all, so you need to provide such images.

**Comment by miketimofeev** [comment]
Hi @smorimoto! Our generated images based on Azure plain ones as you can see, for example, from this template
https://github.com/actions/virtual-environments/blob/632722fedf81e05feae8349601bfbfc436568d0f/images/win/Windows2019-Azure.json#L59-L61
We don't have a plan to provide such plain environments, but you can create a VM from Azure marketplace(or generate it via packer) and set up self-hosted runner for your needs:
https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners
We're working on stronger documentation about building and deploying images, hope it'll help with your question too https://github.com/actions/virtual-environments/issues/564 I'm going to close the issue.
Thank you!

**Comment by smorimoto** [comment]
Hi @miketimofeev. To be honest, setting up a self-hosting runner is not at all difficult for me. But, you should be able to understand that doing it on an open-source project is very expensive. Why do you still force developers to use a dirty image with many packages added randomly?

**Comment by maxim-lobanov** [comment]
@smorimoto , providing one more image (even clean one) will add maintenance work because we will have to maintain VM pools, scale it based on capacity and etc.
Based on requests in this repository, the most of the customers need environment with pre-installed software because it significantly reduces their build time and saves build minutes. On clean environment, you will have to install all tools in runtime and it will take additional build time. 

As an option, [Windows docker containers](https://github.com/actions/virtual-environments/issues/923#issuecomment-634230038) can be used for this goal.
It was already discussed in https://github.com/actions/virtual-environments/issues/923#issuecomment-654365912.

**Comment by smorimoto** [comment]
We want something that's not clean, it's completely plain. Hmm... Have you ever wanted to install everything yourself? Windows Docker container is not the solution we are looking for.

**Comment by smorimoto** [comment]
I understand that it adds maintenance work, but don't you think it's a meaningful effort? The images you are providing at the moment are too dirty.
