### ISSUE TITLE
`brew update && brew upgrade` fails on `bazelisk` upgrading

### ISSUE THREAD

**Issue by gitoleg** [actions/virtual-environments#1365]
**Describe the bug**
The `bazelisk` formula has a conflict with `bazel` formula. The PR that added this conflict was merged only 5 days ago https://github.com/Homebrew/homebrew-core/pull/55403. 
The problem is that on macOS we already have both formula installed. And when I ran `brew update && brew upgrade` in my workflow, I got the error (no surprises here):
```
Error: Cannot install bazelisk because conflicting formulae are installed.
  bazel: because Bazelisk replaces the bazel binary

Please `brew unlink bazel` before continuing.
```

**Area for Triage**: 
Packages

**Question, Bug, or Feature?**: 
 Bug

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Would be great to run `brew update && brew upgrade` with no errors. Maybe, it would be even a good idea to add this to your internal tests.  I would leave only one of these formulae installed, but it's up to you.

**Actual behavior**
As I said, I got an error, which fails the whole workflow.
https://github.com/BinaryAnalysisPlatform/bap/runs/947996113?check_suite_focus=true
To reproduce it, just run `brew update && brew upgrade`.

**Comment by maxim-lobanov** [comment]
Hello, we have faced with the same issue during image generation and removed `bazel` formula.
The next image will have only `bazelisk` and everything should work as previously

**Comment by miketimofeev** [comment]
Hi @gitoleg!
We've already removed separate bazel installation via brew from our VM provision scripts and left bazelisk one only(bazel then installed by bazelisk). 
We're going to deploy a new VM image with these changes in the next 2 days.
As a workaround, you can run `brew uninstall bazel` before `brew update && brew upgrade`
Thank you!

**Comment by gitoleg** [comment]
Thanks! The issue can be closed then

**Comment by soonho-tri** [comment]
This is unfortunate that there is a conflict between the two formulas, `bazel` and `bazelisk`. I think `bazel` should have higher-priority over `bazelisk` which is a derived project of `bazel`. Every `bazelisk` user uses `bazel`, but it's *not* the other way around.

Please check my reasoning below:

1. A common task of macOS CI with homebrew is to test a homebrew formula.
2. A bazel-based homebrew formula has  `depends_on "bazel" => :build` in its formula file.
3. When this formula is tested via `brew install --build-from-source <formula_name>` in CI, it will check and install `bazel` if it is not installed, regardless of `bazelisk` installed in the system.
4. Since `bazelisk` is there, it will fail with a conflict.

Let's consider a hypothetical situation where we have `cmake-lisk` and it conflicts with `cmake`. Would you remove `cmake` and only provide `cmake-lisk`?

**Comment by maxim-lobanov** [comment]
Hello @soonho-tri , 
If we remove `bazelisk`, we will break all customers who use it in builds so we can't remove `bazelisk` from images.
If we remove `bazel`, we will break neither `bazelisk` customers, nor `bazel` customers because `bazelisk` installs the latest version of `bazel` and `bazel` is available in PATH. Builds that use `bazel` binary, will continue to work as previously.

`bazelisk` is [recommended way](https://docs.bazel.build/versions/master/install-bazelisk.html) to install `bazel` and it provides `bazel` + package manager for bazel versions (not replacement but extending of `bazel` functionality). 

We understand the issue with brew formula and suggest to rework your validation logic to check if `bazel` is available in PATH or get rid of validation because Bazel is already pre-installed and we don't have plans to remove Bazel from images in future.

**Comment by soonho-tri** [comment]
> bazelisk is recommended way to install bazel and it provides bazel + package manager for bazel versions (not replacement but extending of bazel functionality).

`bazelisk` is just one of the ways to install bazel according to the offical webpage. It's not the recommended way AFAIK. "Use homebrew" (`brew install bazel`) comes before `bazelisk` in the list.

<img width="473" alt="Screen Shot 2020-08-07 at 8 36 19 AM" src="https://user-images.githubusercontent.com/20779767/89646132-2caee500-d889-11ea-80be-2673189b8dbd.png">

> If we remove bazel, we will break neither bazelisk customers, nor bazel customers because bazelisk installs the latest version of bazel and bazel is available in PATH. Builds that use bazel binary, will continue to work as previously.

In one sense, it broke bazel customers (me and @gitoleg), so we are here.

> We understand the issue with brew formula and suggest to rework your validation logic to check if bazel is available in PATH or get rid of validation because Bazel is already pre-installed and we don't have plans to remove Bazel from images in future.

I understand that it requires one-line to fix this on my side. But the same thing is true if one wants to keep using `bazelisk`. (`brew install bazelisk`, that's it).

---

Here, I want to provide more reasons why I think we should prefer `bazel` over `bazelisk`.

1. According to https://formulae.brew.sh which provides homebrew package stats, `bazel` is 13x more frequently downloaded and installed than `bazelisk` in the previous 365 days.

<img width="670" alt="Screen Shot 2020-08-07 at 8 39 27 AM" src="https://user-images.githubusercontent.com/20779767/89646511-ed34c880-d889-11ea-9ec8-ed648834fb06.png">

<img width="657" alt="Screen Shot 2020-08-07 at 8 39 19 AM" src="https://user-images.githubusercontent.com/20779767/89646503-e9a14180-d889-11ea-9bc9-e75e3cf1493e.png">

2. If you provide `bazel` in your VM image, it's fully loaded. No download is required when a user calls `bazel`. However, if you ship `bazelisk`, It still needs to download the latest version of `bazel` when a user runs `bazel` first time. Since this is a CI service, it is going to happen every time there is `bazel` in a CI workflow. Isn't this against the purpose of pre-shipping a formula in a VM image?

**Comment by miketimofeev** [comment]
@soonho-tri we invoke `bazel` during VM image generation to pre-install it via bazelisk so the version is already downloaded.

**Comment by jamiesnape** [comment]
> If we remove bazelisk, we will break all customers who use it in builds so we can't remove bazelisk from images.
If we remove bazel, we will break neither bazelisk customers, nor bazel customers because bazelisk installs the latest version of bazel and bazel is available in PATH. Builds that use bazel binary, will continue to work as previously.

Actually you did just break a `bazel` customer, otherwise I would not be commenting here. The "we can't remove something because it would break customers' builds" misses the point that continuously layering more dependencies on an image also tends to break builds in the medium to long term with conflicts and incompatibilities. We moved any from Travis CI because of that situation, but looks like we are going to have to move again, i.e., you lost a customer. Thanks.

**Comment by miketimofeev** [comment]
Image with bazel installed via bazelisk has been deployed.
`brew update && brew upgrade` works now.
