### ISSUE TITLE
Install Visual Studio with Homebrew Cask

### ISSUE THREAD

**Issue by reitermarkus** [actions/virtual-environments#1390]
**Describe the bug**

`brew cask install visual-studio` fails since Visual Studio is not installed via Homebrew. Is there a specific reason for this? If not, Visual Studio should also be installed via Homebrew Cask.

**Area for Triage**: 
Apple

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Visual Studio is installed via Homebrew Cask.

**Actual behavior**
Visual Studio is not installed via Homebrew Cask.

**Comment by maxim-lobanov** [comment]
Hello @reitermarkus,
We were not aware about existing that formula. I like the formula approach because we don't need to maintain version of VS4Mac. However, I see the following issue with `visual-studio` brew cask: it depends on `homebrew/cask-versions/mono-mdk-for-visual-studio` cask.

On our images, we have to install a bunch of [Mono](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#mono) versions side by side. This approach conflicts with brew formula for Mono because formula downloads and installs `pkg` file that just removes all other versions.

**Comment by maxim-lobanov** [comment]
Closing this for now since we can't use vs4mac formula for reason above. Please let me know if you have concerns
