### ISSUE TITLE
Fedora/CentOS

### ISSUE THREAD

**Issue by sblantipodi** [actions/virtual-environments#1443]
why there is no Fedora/CentOS support in GitHub Actions?

Please add it.

**Comment by greg-hellings** [comment]
Support for either of these as a first class citizen would be helpful for me, as well. Is there any chance the community could be of assistance here?

**Comment by maxim-lobanov** [comment]
Hello @sblantipodi , thank you for your request and interest for additional images.
Different images and more flavors of existing images is something we're always considering. Unfortunately it is not possible for us to provide Fedora / CentOS images as you suggest at this time.

Our main focus for now is reducing fragmentation and stabilizing existing images. Since we see popularity of this request, we will keep it on mind and will be able to revisit this decision in future.
