### ISSUE TITLE
Did Dockerhub rate limit affect Github Action?

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#1445]
Associated community ticket: https://github.community/t/did-dockerhub-rate-limit-affect-github-action/128158

The customer noticed that Docker hub has updated their **pricing**, [**Download rate limit**](https://docs.docker.com/docker-hub/download-rate-limit/) and **retention policy** recently. He is wondering if the download rate limit affects on Github Action.
Will the steps like below are affected?
```yaml
jobs:
  my_first_job:
    steps:
      - uses: docker://alpine:3.11
```
```yaml
jobs:
  my_first_job:
    steps:
      - run: docker pull alpine:3.11
```

According to the introductions from the docs about "**Download rate limit**", the limit seems only applies for the anonymous users with an eventual limit of 100 pulls per six hours. Logged in users will not be affected at this time.

I setup a workflow with the following step that pull an image 101 times in a loop.
```yaml
- name: Test Docker download rate limits
  run: |
    docker image ls
    index=1
    while [ $index -le 101 ]
    do
      echo "---------------------------------------------------------------------------------------"
      echo "Pull image $index times"
      docker pull alpine:3.11
      docker image ls
      index=$(( $index + 1 ))
      docker image rm alpine:3.11
    done
    docker image ls
```
It can successfully download the image 101 times without any warning or error messages about the download rate limit.
**Note:** Consider there may be image cache, I have used the "**docker image rm**" command to remove the image every time before downloading it again.

**Question:**
When we try to pull some public images in the workflow, if we do not login with any of our accounts, whether GitHub has a default account to login the docker?
If not, in my above example, why it is not hit the download rate limit?

**Comment by maxim-lobanov** [comment]
Hello @BrightRan , thank you for raising it.
The new policy will be applied starting from November 1st, 2020. It is the reason why we can't reproduce it right now.
`Docker will gradually introduce these rate limits, with full effects starting from November 1st, 2020.`
GitHub doesn't have default account to login in the docker. I am not sure if it is possible because of security reasons.

I have found the following Docker use-cases in GA (I could miss something):
1.
```yml
jobs:
  my_first_job:
    steps:
      - run: docker pull alpine:3.11
```
This use-case allow customers to do login by theirselves:
```yml
steps:
  - run: |
      docker login --username ${{ secrets.docker_username }} --password ${{ secrets.docker_password }}
      docker pull alpine:3.11
```
2) 
```yml
jobs:
  container:
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
        name: Run in container
```
Looks like pull of such container is happening at the first step of pipeline and we can't login before somehow.

3.
```yml
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://alpine:3.11
```
this use case will be affected too
because even if we invoke 
```yml
steps:
  - run: docker login
  - uses: docker://alpine:3.11
```
Container pull happens at the first step of the build before docker login

4.
```yml
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: my_custom_action_that_uses_docker_inside@v1
```


In the first use-case, customer can overcome limit by login to docker as a first step of pipeline: `docker login --username ${{ secrets.docker_username }} --password ${{ secrets.docker_password }}`.
But looks like use-cases 2,3,4 will be broken.

DockerHub will use IP rate limit so our customers could be affected. `Docker will gradually impose download rate limits with an eventual limit of 100 pulls per six hours for anonymous users.`
As I can see, DockerHub even provides separate documentation section about [rate limits in GitHub Actions](https://docs.docker.com/docker-hub/download-rate-limit/#github-actions). But actually, they are asking action owners to build-in `docker login` as a part of their actions and it will fix use case 4.

I don't have much experience with docker so could be wrong, may be actions/runner team can help us to understand if there is a way to login in use-cases 2,3,4. cc: @hross , @ericsciple , @TingluoHuang 

cc: @thejoebourneidentity @alepauly @bryanmacfarlane

**Comment by BrightRan** [comment]
@maxim-lobanov ,
Thanks for your reply.
For the use case `3` and `4`, can we add a step to login docker before the '**uses**' step? Similar to the use case `1` you mentioned.

**Comment by maxim-lobanov** [comment]
@BrightRan , for 4 - yes.
For 3 it is not possible because looks like pulling of all images happen before all steps.
This yaml produces the following steps:
```yml
steps:
  - run: docker login
  - uses: docker://alpine:3.11
```
![image](https://user-images.githubusercontent.com/16715858/90864596-a1117a00-e399-11ea-8637-e5c77073ad60.png)

**Comment by BrightRan** [comment]
@maxim-lobanov ,
Yes, you're right.
I just have tried it, and the results confirms your statement.
Thanks for your detailed explanation.

**Comment by vtbassmatt** [comment]
We're also thinking about this in Azure Pipelines. We already have a technical solution for scenarios 2 and 3 (container resources can use a service connection for authentication). Most of our current usage is anonymous, though, so we'll have to help customers understand the impact and adapt.

**Comment by nihaals** [comment]
Judging from the ADRs being private, will GitHub users not get to see the syntax until it's out (and can't have breaking changes)? Since the rate limit would almost definetely affect users, would it be worth adding a deprecation notice once a fix is available eventually forcing all users to pull while being logged in? Could help solve problems before they arise if people new to GitHub Actions start using it and expect it to work without knowing about the limit or that public CIs don't get some kind of whitelist

**Comment by chrispat** [comment]
@nihaals the syntax is very simple as we are simply adding a credentials element to the `job.container` and `job.services` key.  We are also trying to understand from Docker if the library images are impacted by these changes.  Based on our telemetry we believe that will have the biggest impact in how many users are immediately impacted.

**Comment by nihaals** [comment]
I made what I think is a [related feature request](https://github.community/t/request-non-censored-secrets-dynamic-variables/128962) that may make it nicer to login with Actions which sounds like will work with the new syntax

What do you think about the deprecation notice on unauthorised Docker Hub images? Probably blocked by finding out if official images are exempt and the new syntax

**Comment by rnorth** [comment]
As I understand it one scary and unresolved problem with (1) is going to be sharing Hub credentials with forked repos. Any solution that involves a `docker login` execution will not work, because (a) [secrets are not available to forked repos](https://github.community/t/make-secrets-available-to-builds-of-forks/16166/25), and (b) we have no other safe way to provide credentials to a `docker login` invocation.

Does the solution that's being worked on address this aspect?

**Comment by chrispat** [comment]
At the moment we do not have a solution to that particular problem but we are investigating options.

**Comment by maxim-lobanov** [comment]
After the latest GitHub update, you can specify credentials for container downloading: https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/

**Comment by rnorth** [comment]
@chrispat sorry to press on this, but is there any news on solutions to the forked repo problem I mentioned [above](https://github.com/actions/virtual-environments/issues/1445#issuecomment-684539064)?

**Comment by mattwelke** [comment]
@maxim-lobanov 

> After the latest GitHub update, you can specify credentials for container downloading

I read the blog post. That looks like it'll indirectly solve the rate limiting problem for job container and service container use cases by allowing people to authenticate, which would put them in control of how subjected to rate limits they are.

However, do you know whether it will work for container actions? For example, from the docs (https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-using-a-docker-hub-action):

```yaml
jobs:
  my_first_job:
    steps:
      - name: My first step
        uses: docker://alpine:3.8
```

In this example, the image used for the Docker container action is being pulled by the GitHub Actions runner from Docker Hub. Because credentials aren't specified for the step, I'm assuming this is being done without authenticating with Docker Hub.

The images used for container actions must be public, which means people don't *have* to authenticate to use them, but if they choose not to authenticate as they use them, they'll be subject to the IP-based rate limiting, affected by other GitHub Actions users. Is this correct?

**Comment by rnorth** [comment]
@chrispat sorry to ask again, but it's getting worryingly close to November and, as far as I can tell, there's still no safe way for open source projects to use authenticated access to Docker Hub.

Has there been any progress in finding a way for forks of repos to be able to inherit Docker Hub authentication from the original repo?

**Comment by chrispat** [comment]
For publicly accessible containers we are working with docker hub to make sure you will not be impacted by the new rate limits.  If you need private containers we still do not have a solution for that problem for forks of public repos.

**Comment by rnorth** [comment]
Thank you @chrispat! As a maintainer of an open source project that uses public Docker images, that's really good news.

**Comment by mdeggies** [comment]
> For publicly accessible containers we are working with docker hub to make sure you will not be impacted by the new rate limits. 

@chrispat just to confirm, does this mean we will NOT need to add dockerhub auth to all of our jobs that pull public dockerhub images?

**Comment by chrispat** [comment]
That is correct.  It is important to note that this will only apply to the runners hosted by GitHub, if you are using self-hosted runners you will need to configure your own credentials.

**Comment by mdeggies** [comment]
Thank you for the confirmation! :)

**Comment by lizan** [comment]
> That is correct. It is important to note that this will only apply to the runners hosted by GitHub, if you are using self-hosted runners you will need to configure your own credentials.

@chrispat Will this be also applicable to Azure Pipelines hosted agents?

**Comment by chrispat** [comment]
@lizan for now this will apply for Azure Pipelines.  However, given you have the ability to enter your own credentials for containers in Azure Pipelines I would encourage you to do that.  One of the main reasons we feel this is important for GitHub Actions is to better support our open source customers, and a lot of the individual actions in the marketplace are themselves implemented as containers.

Azure Pipelines tasks by contrast have no formal support for being implemented as a container and while we know some open source projects do use it we are encouraging them to move to GitHub Actions.

**Comment by lizan** [comment]
Thanks for the clarification, that helps.

> Azure Pipelines tasks by contrast have no formal support for being implemented as a container and while we know some open source projects do use it we are encouraging them to move to GitHub Actions.

Yeah I'm asking on behalf of [Envoy](https://github.com/envoyproxy/envoy) OSS project :) and we don't have good story to move to GHA for various reasons.

**Comment by magthe** [comment]
Did this issue reach a conclusion?
Where can I find the answer to the original question, "Did Dockerhub rate limit affect Github Action?"

**Comment by maxim-lobanov** [comment]
@magthe , https://github.com/actions/virtual-environments/issues/1445#issuecomment-713861495
> For publicly accessible containers we are working with docker hub to make sure you will not be impacted by the new rate limits. If you need private containers we still do not have a solution for that problem for forks of public repos.
 It is important to note that this will only apply to the runners hosted by GitHub, if you are using self-hosted runners you will need to configure your own credentials.

**Comment by magthe** [comment]
Yes, I read that, but the wording makes it sound like it's in progress.

Should I interpret the closing of this ticket as there's a finalised an agreement with Docker Hub that ensures GitHub Actions aren't impacted by the rate limits?

**Comment by chrispat** [comment]
@magthe yes we resolved this through an agreement with Docker.

**Comment by mukul-c2fo** [comment]
I saw the docker pull limit error on few of the github actions today which build an image from a Dockerfile.

**Comment by bfjelds** [comment]
@chrispat, is there any public announcement/documentation of this Docker agreement?  it would be helpful to understand what is included/excluded (does this apply to all github repo actions/workflows except self-hosted runners?  does it apply to public and private repos?  etc)  Thanks!!

**Comment by seglo** [comment]
Does this just work by nature of dockerhub allowing unlimited pulls from builds running on github actions (by hostname/ip?)

**Comment by carlobeltrame** [comment]
This seemed to work for me, but I now have some GitHub workflows that use docker-compose to start some services, and they fail with the message:
```
Pulling db (mariadb:10.3)...
10.3: Pulling from library/mariadb
error pulling image configuration: errors:
unauthorized: authentication required
unauthorized: authentication required
```

Is this a temporary situation or is the agreement between GitHub and Docker Hub permanently amended?

**Comment by carlobeltrame** [comment]
It looks like the situation has already resolved itself again, my builds work again when I re-run the jobs. Confirmed on multiple repositories.

**Comment by XavierChapron** [comment]
> We are actually actively working on providing more native login capabilities in actions. See [this ADR](https://github.com/github/c2c-actions-runtime/blob/81d045c77db1db47a6f7ae02adfd316e7a76781b/adrs/0813-containers-from-private-registries.md). This should make it easier for customers to set up authentication for scenarios `2` and `3`.
> 
> @dakale is adjusting the syntax with @chrispat (today, actually). We should have this ready to go by the end of the month at the latest, which should mean better support before the docker limits are imposed.

@hross Is it still on the roadmap? I can't access your link.
The agreement announced by @chrispat is great for workflow working on GitHub runner, but what about self-hosted runner?
Is there at least a documented syntax to allow user login?

**Comment by maxim-lobanov** [comment]
@XavierChapron , see https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/ it should help

**Comment by XavierChapron** [comment]
@maxim-lobanov Thanks a lot! It was exactly what I was needing.

**Comment by marc-hb** [comment]
> @chrispat, is there any public announcement/documentation of this Docker agreement? it would be helpful to understand what is included/excluded (does this apply to all github repo actions/workflows except self-hosted runners? does it apply to public and private repos? etc) Thanks!!

So we still don't know what the exact agreement terms are but for at least public repos, anonymous pulls from github don't seem to hit any rate limit anymore. I'm guessing some caching is also happening because why would it not.

But rate limits are not the end of the story. I found this FAQ https://forums.docker.com/t/automated-docker-pulls-from-github-hosted-runner-which-organization-must-pay/116095
> Q: I want to run an automated agent that makes container requests on behalf of my organization. Which license do I need?
> A: Automated agents or service accounts that make container image requests of Docker Hub must be licensed under a Docker Team subscription.

This does not say anything about rate limits, it merely says "automated agent". Who is the "automated agent"? Github or the open-source project using github to docker pull anonymously?

**Comment by ssallmen-pro** [comment]
I think the issue with rate limit has landed again, has the agreement between GitHub and Docker been terminated or what has happened?
In my workflow (or actually in my own composite action but that does not really affect the functionality) I am using a fork of Docker(file) based action (https://github.com/simple-elf/allure-report-action) which uses openjdk:8-jre-alpine as the base image. This week I started getting these error when the Docker image of the allure-report-action is built:
```
Step 1/10 : FROM openjdk:8-jre-alpine
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
The problem would be easy to solve if I could do docker login before the docker build happens but as the build will happen before any steps in the workflow (or the composite action) are executed, it is not possible. Is there already some solution for this kind of case, or should the agreement of Docker Hub not limiting pulls from GitHub runners (which I have been using) for an anonymous user be still in force?

I could also use our company's self-hosted runners but it will not remove the issue because there are so many docker pulls to Docker Hub from our company's IP also that the limits are reached (tried that). I could even use our company's own Docker Hub registry cache (by adding the cache host to the action's Dockerfile, before the image name) but that would require me to login to the cache registry before the build, and we are back in the issue of not being able to have any login step before the Docker based action image build.

**Comment by marc-hb** [comment]
Some projects like this one publish their images to https://ghcr.io too:

https://github.com/zephyrproject-rtos/docker-image/blob/1a0e3737905/README.md

Given that choice, we switched from docker.io to ghcr.io for that particular image. Interestingly, we didn't observe any speedup but we (naively?) hope this will avoid all rate limiting issues now and in the future.

**Comment by ssallmen-pro** [comment]
@marc-hb Do you have some Docker(file) based actions (https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action) which are using base images from a ghrc.io or some other private Dopcker registry? How are you able to login to the registry before the action is built in the workflow since none of the steps in the workflow run before the base image is tried to be pulled?
I could use a base image from our company's own Docker registry if I just could login there before action is built, and the base image needed.

**Comment by marc-hb** [comment]
> How are you able to login to the registry before the action is built

We don't login, that's why we switched to the ghcr.io mirror of that particular image. I have never set up a ghcr.io mirror myself but I assumed it's not rocket science if you're already publishing images somewhere and an alternative worth mentioning.

**Comment by ssallmen-pro** [comment]
Ok, didn't know that it is possible to pull images from a ghcr.io mirror without any login on GitHub runners but now I know. The issue is just that the base image in the Dockerfile is an official openjdk image which I was not able to find being available in ghcr.io. And, even though it is of course always possible to set up an own user for container registry, it is even more challenging than rocket science to make that happen in such a big and stiff corporation I am working for.

**Comment by SvetaSR** [comment]
> https://ghcr.io

Facing the same issue with this package now (allure-report-action).
Did you find a solution by any chance?

**Comment by SvetaSR** [comment]
> I think the issue with rate limit has landed again, has the agreement between GitHub and Docker been terminated or what has happened? In my workflow (or actually in my own composite action but that does not really affect the functionality) I am using a fork of Docker(file) based action (https://github.com/simple-elf/allure-report-action) which uses `openjdk:8-jre-alpine` as the base image. This week I started getting these error when the Docker image of the allure-report-action is built:
> 
> ```
> Step 1/10 : FROM openjdk:8-jre-alpine
> toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
> ```
> 
> The problem would be easy to solve if I could do docker login before the docker build happens but as the build will happen before any steps in the workflow (or the composite action) are executed, it is not possible. Is there already some solution for this kind of case, or should the agreement of Docker Hub not limiting pulls from GitHub runners (which I have been using) for an anonymous user be still in force?
> 
> I could also use our company's self-hosted runners but it will not remove the issue because there are so many docker pulls to Docker Hub from our company's IP also that the limits are reached (tried that). I could even use our company's own Docker Hub registry cache (by adding the cache host to the action's Dockerfile, before the image name) but that would require me to login to the cache registry before the docker image build, and we are back in the issue of not being able to have any login step before the Docker based action image build.

@ssallmen-pro 
Facing the same issue with this package now (allure-report-action).
Did you find a solution by any chance?

**Comment by chancez** [comment]
I'm also seeing this today. Did anything change?

**Comment by ssallmen-pro** [comment]
@SvetaSR @chancez 
The issue persisted for a week or maximum two in October '22, but then it went away and I did not see it coming again even though the same docker image was downloaded multiple times a day. Currently I am working in another assignment and do not use GitHub Actions at the moment at all. Let's hope it will be just a temporary issue again.

**Comment by achimnol** [comment]
I'm seeing this in larger runners of GitHub Actions.
https://github.com/lablup/backend.ai/actions/runs/6846124540/job/18612305349?pr=1712

**Comment by smcgivern** [comment]
@chrispat are you still working on Actions?

Yesterday we hit some rate limits for public Docker images (`node` in particular) from our GitHub-hosted runners. We do not have particularly high-volume usage.

I couldn't find a mention of https://github.com/actions/runner-images/issues/1445#issuecomment-713861495 in the documentation, and GitHub Support also didn't seem to know about this agreement. Is this documented somewhere and I just missed it?

**Comment by rekha-prakash-maersk** [comment]
We are hosting self hosted runner and we are hitting the rate limit as well. how to find more information on alternative approaches ?

**Comment by sandstrom** [comment]
@smcgivern Did they share any timeline? Is this a known issue they are working to fix?

We started using the ARM runners and ran into this problem.

**Comment by smcgivern** [comment]
They did not, sorry. They said they had no ETA currently.

**Comment by benjie** [comment]
Seem to be [hitting this today](https://github.com/graphile/crystal/actions/runs/10270014362/job/28416792938?pr=2146); our runners are not special (not ARM, not GPU). Hoping it's just a temporary blip, but raising it in case others are also impacted.

**Comment by mvdan** [comment]
We are hitting this error today on public shared runners trying to pull a public Docker Hub image, https://hub.docker.com/_/postgres, so the rate limits are still in effect as far as we can see. Pretty annoying given that there's no easy way to cache pulled images on GitHub Actions either. We're having to resort to workarounds like authenticating with Docker Hub with a bot account, or trying to move off of Docker Hub as much as possible.

**Comment by mattwelke** [comment]
I don't think it's unreasonable to be required to authenticate with Docker Hub. If I were hosting a free service providing Docker images, I would find it helpful to know who's using up my bandwidth!

I wonder if GitHub could provide credentials for a "GitHub Actions" Docker Hub to all GitHub Actions like they do with [`GITHUB_TOKEN`](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication). This account would represent all GitHub Actions users authenticating only as a GitHub Actions user instead of more specifically, as themself.

GitHub could even coordinate with Docker so that Docker could impose a rate limit on this account if they want to treat it differently, considering it would represent multiple users instead of just one user.

This would allow users to start using Docker Hub with less of a chance of running into this issue without having to set up their own Docker Hub credentials in their workflows.

**Comment by mvdan** [comment]
@mattwelke I would not have an issue with reasonable rate limits if GitHub Actions made it reasonably easy to cache pulled images. Fifteen minutes of searching gave me no results other than https://github.com/marketplace/actions/docker-cache, which is an unofficial action that I would rather not have to trust.

I'm not assigning blame here, as both GitHub Actions and Docker Hub are largely free services, but it's a bit silly that their interaction runs into rate limits for no reason.

**Comment by chrispat** [comment]
> I don't think it's unreasonable to be required to authenticate with Docker Hub. If I were hosting a free service providing Docker images, I would find it helpful to know who's using up my bandwidth!
> 
> I wonder if GitHub could provide credentials for a "GitHub Actions" Docker Hub account to all GitHub Actions workflows like they do with [`GITHUB_TOKEN`](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication). This account would represent all GitHub Actions users authenticating only as a GitHub Actions user instead of more specifically, as themself.
> 
> GitHub could even coordinate with Docker so that Docker could impose a rate limit on this account if they want to treat it differently, considering it would represent multiple users instead of just one user.
> 
> This would allow users to start using Docker Hub with less of a chance of running into this issue without having to set up their own Docker Hub credentials in their workflows.

All of the shared public runners are automatically logged in to docker hub with a shared account that has significantly higher rate limits on Docker Hub.   I just ran a job that pulled that image and was not able to reproduce the issue.

**Comment by rustamabd2** [comment]
> All of the shared public runners are automatically logged in to docker hub with a shared account that has significantly higher rate limits on Docker Hub. I just ran a job that pulled that image and was not able to reproduce the issue.

This issue is sporadic, it "fixes" itself after re-running the job, so it's to be expected that it can't be easily reproduced.
Could it be that the higher limit is being reached? Is it being monitored anywhere?

**Comment by ItsReddi** [comment]
Is there a way to authenticate?
We are using GitHub Runners and getting it since today.
We use "services:"
![grafik](https://github.com/user-attachments/assets/4f992748-b640-4652-8aa1-1f94af836b53)
```yml
services:
      # Label used to access the service container
      local-mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: dev
          MYSQL_USER: dev
          MYSQL_PASSWORD: dev
          MYSQL_DATABASE: test
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
      redis:
        image: redis:6.0.8-alpine
        ports:
          - 6379:6379
```

**Comment by nebuk89** [comment]
If you are seeing this issue and it's in a public repo could you link me to workflow runs please so I can see date/time/other run info so we can dig in <3

**Comment by ramondelafuente** [comment]
We see this too, unfortunately not on a public repo... this is the raw log from the run:

```
2024-09-11T15:24:30.8594587Z Current runner version: '2.319.1'
2024-09-11T15:24:30.8619384Z ##[group]Operating System
2024-09-11T15:24:30.8620159Z Ubuntu
2024-09-11T15:24:30.8620571Z 22.04.4
2024-09-11T15:24:30.8620905Z LTS
2024-09-11T15:24:30.8621303Z ##[endgroup]
2024-09-11T15:24:30.8621707Z ##[group]Runner Image
2024-09-11T15:24:30.8622159Z Image: ubuntu-22.04
2024-09-11T15:24:30.8622601Z Version: 20240901.1.0
2024-09-11T15:24:30.8623675Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240901.1/images/ubuntu/Ubuntu2204-Readme.md
2024-09-11T15:24:30.8625378Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240901.1
2024-09-11T15:24:30.8626343Z ##[endgroup]
2024-09-11T15:24:30.8626759Z ##[group]Runner Image Provisioner
2024-09-11T15:24:30.8627256Z 2.0.384.1
2024-09-11T15:24:30.8627658Z ##[endgroup]
2024-09-11T15:24:30.8643667Z ##[group]GITHUB_TOKEN Permissions
2024-09-11T15:24:30.8645608Z Actions: write
2024-09-11T15:24:30.8646224Z Attestations: write
2024-09-11T15:24:30.8646860Z Checks: write
2024-09-11T15:24:30.8647257Z Contents: write
2024-09-11T15:24:30.8647708Z Deployments: write
2024-09-11T15:24:30.8648095Z Discussions: write
2024-09-11T15:24:30.8648503Z Issues: write
2024-09-11T15:24:30.8648966Z Metadata: read
2024-09-11T15:24:30.8649317Z Packages: write
2024-09-11T15:24:30.8649715Z Pages: write
2024-09-11T15:24:30.8650160Z PullRequests: write
2024-09-11T15:24:30.8650559Z RepositoryProjects: write
2024-09-11T15:24:30.8651043Z SecurityEvents: write
2024-09-11T15:24:30.8651533Z Statuses: write
2024-09-11T15:24:30.8651904Z ##[endgroup]
2024-09-11T15:24:30.8654875Z Secret source: Actions
2024-09-11T15:24:30.8655603Z Prepare workflow directory
2024-09-11T15:24:30.9561395Z Prepare all required actions
2024-09-11T15:24:30.9723539Z Getting action download info
2024-09-11T15:24:31.1511156Z Download action repository 'actions/checkout@v4.1.7' (SHA:692973e3d937129bcbf40652eb9f2f61becf3332)
2024-09-11T15:24:31.2764167Z Download action repository 'shivammathur/setup-php@2.31.1' (SHA:c541c155eee45413f5b09a52248675b1a2575231)
2024-09-11T15:24:31.4537468Z Download action repository 'actions/cache@v4' (SHA:0c45773b623bea8c8e75f6c82b208c3cf94ea4f9)
2024-09-11T15:24:31.7014201Z Complete job name: integration (8.3, false)
2024-09-11T15:24:31.7901518Z ##[group]Checking docker version
2024-09-11T15:24:31.7916495Z ##[command]/usr/bin/docker version --format '{{.Server.APIVersion}}'
2024-09-11T15:24:31.8915903Z '1.45'
2024-09-11T15:24:31.8949226Z Docker daemon API version: '1.45'
2024-09-11T15:24:31.8950982Z ##[command]/usr/bin/docker version --format '{{.Client.APIVersion}}'
2024-09-11T15:24:31.9179685Z '1.45'
2024-09-11T15:24:31.9185739Z Docker client API version: '1.45'
2024-09-11T15:24:31.9192124Z ##[endgroup]
2024-09-11T15:24:31.9196456Z ##[group]Clean up resources from previous jobs
2024-09-11T15:24:31.9204020Z ##[command]/usr/bin/docker ps --all --quiet --no-trunc --filter "label=019bbc"
2024-09-11T15:24:31.9409362Z ##[command]/usr/bin/docker network prune --force --filter "label=019bbc"
2024-09-11T15:24:31.9547253Z ##[endgroup]
2024-09-11T15:24:31.9548037Z ##[group]Create local container network
2024-09-11T15:24:31.9562186Z ##[command]/usr/bin/docker network create --label 019bbc github_network_cf6957732b494bb6ae13d16c7f4baea1
2024-09-11T15:24:32.0297875Z 07d2aa32c8271575dadfe2d18188db4ec4cd8fa48b54707034fc218cb7be4f1c
2024-09-11T15:24:32.0327450Z ##[endgroup]
2024-09-11T15:24:32.0446731Z ##[group]Starting mailer service container
2024-09-11T15:24:32.0515749Z ##[command]/usr/bin/docker pull axllent/mailpit
2024-09-11T15:24:32.0614358Z Using default tag: latest
2024-09-11T15:24:37.2900135Z latest: Pulling from axllent/mailpit
2024-09-11T15:24:37.3058632Z toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
2024-09-11T15:24:37.3085866Z ##[warning]Docker pull failed with exit code 1, back off 3.575 seconds before retry.
2024-09-11T15:24:40.8847426Z ##[command]/usr/bin/docker pull axllent/mailpit
2024-09-11T15:24:40.8950838Z Using default tag: latest
2024-09-11T15:24:41.0395882Z Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
2024-09-11T15:24:41.0415680Z ##[warning]Docker pull failed with exit code 1, back off 5.34 seconds before retry.
2024-09-11T15:24:46.3798025Z ##[command]/usr/bin/docker pull axllent/mailpit
2024-09-11T15:24:46.3910865Z Using default tag: latest
2024-09-11T15:24:46.5341928Z Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
2024-09-11T15:24:46.5442001Z ##[error]Docker pull failed with exit code 1
2024-09-11T15:24:46.5572271Z Remove container network: github_network_cf6957732b494bb6ae13d16c7f4baea1
2024-09-11T15:24:46.5577160Z ##[command]/usr/bin/docker network rm github_network_cf6957732b494bb6ae13d16c7f4baea1
2024-09-11T15:24:46.7412872Z github_network_cf6957732b494bb6ae13d16c7f4baea1
2024-09-11T15:24:46.7597309Z Cleaning up orphan processes
```

And a relevant part of the workflow:

```
 integration:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      matrix:
        php-versions: ['8.3']
        allow-failure: [false]

    services:
      mailer:
        image: axllent/mailpit # Docker Hub image: https://hub.docker.com/r/axllent/mailpit
        ports:
          - 1025:1025
          - 8025:8025
      mariadb:
        image: mariadb:10.11 # https://hub.docker.com/_/mariadb
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4.1.7
      ...etc
```

On a side-note: 
Is there a better place for a renewed discussion on this topic than a closed issie from 2020? (open question, since research did bring me here).

**Comment by ramondelafuente** [comment]
@nebuk89 Was the comment above useful? (i.e. should I post the moar logs if we see this happening again)
We've only had two instances (in the past 2 weeks) so not a frequent occurrence for us.

**Comment by y-nk** [comment]
this hitting me on a private repo too. impossible to know exactly why/how.

**Comment by jon-nfc** [comment]
> If you are seeing this issue and it's in a public repo could you link me to workflow runs please so I can see date/time/other run info so we can dig in <3

@nebuk89, Seen this today too when attempting to pull `docker.io/library/python:3.11-alpine3.19`.

job link -> https://github.com/nofusscomputing/centurion_erp/actions/runs/11330393667/job/31508120435.

**Comment by vbalumuri** [comment]
Same here, getting the rate limit error on our private repo while trying to pull `python:3.7-slim`

**Comment by drcongo** [comment]
Also just started getting this today.

**Comment by nvuillam** [comment]
I had docker pull rate llimit issues when I was authenticated to Docker Hub.
So I authenticated only when necessary, to remain unauthenticated most of the time -> no more docker pull issues

Since today: Pull issues again... i'd never seen rate limit issue from GitHub Actions with unauthenticated user :/

**Comment by MikeSchlosser16** [comment]
Also getting this today on a private repo!

**Comment by van-sprundel** [comment]
Since a lot of comments are coming in right now, it seems to be either a new policy or a bug.

**Comment by carloseduardosx** [comment]
+1. I'm facing the same issue while fetching public images from the Docker Registry on my GHA Workflows.

**Comment by KlausVii** [comment]
This was an issue on docker's side https://github.com/docker/hub-feedback/issues/2414

**Comment by glimchb** [comment]
from today
```
Starting job container
  /usr/bin/docker pull docker.io/library/ubuntu:22.04
  Error response from daemon: unauthorized: authentication required
  Warning: Docker pull failed with exit code 1, back off 7.047 seconds before retry.
```
