### ISSUE TITLE
Interest in adding support for "clean"/bare hosted runner images?

### ISSUE THREAD

**Issue by joehorsnell** [actions/virtual-environments#1454]
There's a large amount of software [pre-installed](https://docs.github.com/en/actions/reference/software-installed-on-github-hosted-runners) in the GitHub hosted runner images.

Obviously this is generally useful, but if you're testing something specifically around the installation of software (eg automatic developer environment provisioning), the pre-installed software gets in the way, and you have to first delete/uninstall stuff, eg as [the Homebrew installer CI config does](https://github.com/Homebrew/install/blob/a058021007795cc59c1256ab7493d7cb658b5e2f/.github/workflows/tests.yml#L36).

Would you consider adding support/accept PRs for adding "clean" images, eg. `macos-10.15-clean`, `ubuntu-18.04-clean`, etc. that would have just the bare o/s and nothing else, apart from maybe some minimal tools needed for interaction with GitHub Actions server?

Thanks,

Joe.

**Comment by maxim-lobanov** [comment]
Hello @joehorsnell , different images and more flavors of existing images is something we're always considering. Unfortunately it is not possible for us to provide clean images as you suggest at this time because of maintenance concerns and fragmentation (additional VM pools, scaling them based on capacity and etc)

If there are ways where we can build the existing environment in a way that it's easier to make it appear clean as a workaround, we would be in favor of reviewing changes to the images that you think could help with this.

**Comment by joehorsnell** [comment]
Hi @maxim-lobanov - thanks for your reply.

> Hello @joehorsnell , different images and more flavors of existing images is something we're always considering. Unfortunately it is not possible for us to provide clean images as you suggest at this time because of maintenance concerns and fragmentation (additional VM pools, scaling them based on capacity and etc)
> 

Fair enough 👍.

> If there are ways where we can build the existing environment in a way that it's easier to make it appear clean as a workaround, we would be in favor of reviewing changes to the images that you think could help with this.

Obviously one can always just manually uninstall Homebrew and any other pre-existing software in the rarer cases where required, before running builds. The only suggestion that springs to mind is maybe an "official" or endorsed "Clean" GitHub Action that does this uninstallation for you, but that it's quite simple to do manually, it might not be worth it?

Thanks.
