### ISSUE TITLE
question: ramdisk for runners _work directory

### ISSUE THREAD

**Issue by shusson** [actions/virtual-environments#1466]
**Question**:
I'm not sure if this is the correct location for this question, but I was wondering if github considered using a ramdisk for the default runners `_work` directory? On our own self-hosted runners we get a significant performance increase (our test actions do a lot of IO). It would add more size constraints but maybe it's possible to expose a special directory to the runner.

**Virtual environments affected**
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS

**Comment by mio9** [comment]
2 years late on this, but seems the question is not answered even the issue is closed.

For anyone looking for a solution to use your RAM (not necessarily ramdisk) for the `_work` directory, mount a tmpfs over the `_work` directory with 
```bash
sudo mount -t tmpfs -o size=2G _work/
```
-t defines the mount type, -o defines the size of the mount, we took 2GB for the _work folder from our RAM here. The command is for ubunu/debian based systems, adjust according to your OS (i.e. remove sudo if you're already root). IO speed up is immediate after setup, and also saves your SSD from going bad with constant writes by your pipelines

**Comment by sambolek** [comment]
sudo mount -t tmpfs -o size=20G tmpfs /home/runner/actions-runner/_work
