### ISSUE TITLE
What is the use of tools based on gui??

### ISSUE THREAD

**Issue by SaumitraVerma** [actions/virtual-environments#1474]
in the information file i saw the following software included
Google Chrome 84.0.4147.105
Chrome Driver 84.0.4147.30
Microsoft Edge 84.0.522.52
Microsoft Edge Driver 84.0.522.52
Mozilla Firefox 79.0
Gecko Driver 0.27.0
IE Driver 3.150.1.0
as we cannot get access to the gui what is the need of  google chrome and firefox??

**Comment by dmitry-shibanov** [comment]
Hello @SaumitraVerma . Browsers and its related drivers can be used for testing purpose (like UI tests for your app). In selenium tests you can specify test cases.
- [selenium](https://www.selenium.dev/)
- [example](https://github.com/dmitry-shibanov/ChromeTests/blob/master/test_selenium_chrome.py)

**Comment by SaumitraVerma** [comment]
Ok, is there a way to access the gui

**Comment by dmitry-shibanov** [comment]
No, there is no way to access GUI of images. Actually, running ui tests don't require GUI access. You can find more details using this link: https://dev.to/seleniumbase/running-browser-tests-from-github-workflows-with-seleniumbase-1oic .
I am closing this issue because it is not related to the image content.
