### ISSUE TITLE
use vmImage pool ubuntu-20.04	

### ISSUE THREAD

**Issue by arman1150** [actions/virtual-environments#1524]
hi 
i want to use new feature vmImage ubuntu-20.04 in azure devops server . how can i use???

**Comment by maxim-lobanov** [comment]
Hello, since you use Azure DevOps Server, [you don't have access to Microsoft-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops-2020&tabs=yaml). `ubuntu-20.04` is Microsoft-Hosted pool and it is available only in Azure DevOps services.
On Azure DevOps Server, you have to generate your own agents and host it. More details can be found in guide: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops-2020&tabs=browser

I am closing this issue for now since this repository is intended only for Hosted images since we don't have much experience with Azure DevOps Server and self-hosted agents
