### ISSUE TITLE
Incorrect version

### ISSUE THREAD

**Issue by trajano** [actions/virtual-environments#1570]
**Description**  

https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md

states that it is using `Docker Compose (docker-compose version 1.26.2, build eefe0d31)`

However, when I did `docker-compose --version`  I got

```
docker-compose version 1.27.0, build 980ec85b
```

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  

The versions match the documentation

**Actual behavior**  

The versions do not match the documentation.  In addition, there appears to be a bug in 1.27 which prevents docker-compose config from exiting `0` with no message causing the build scripts to fail.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Step 1
2. Step 2

**Comment by miketimofeev** [comment]
Hi @trajano!
We've been updating Ubuntu 18 environments with the new VM image since Wednesday and plan to finish on Monday. The new readme available here, they will be automatically merged into master when deployment is finished
https://github.com/actions/virtual-environments/blob/releases/ubuntu18/20200908/images/linux/Ubuntu1804-README.md
https://github.com/actions/virtual-environments/blob/releases/ubuntu20/20200908/images/linux/Ubuntu2004-README.md

As a workaround you can update to 1.27.2 until we roll out the new image with this version:
```
URL="https://github.com/docker/compose/releases/download/1.27.2/docker-compose-Linux-x86_64"
sudo curl -L $URL -o /usr/local/bin/docker-compose
docker compose -v
```

**Comment by trajano** [comment]
Thanks, in my case I have to use
```
          - bash: |
              URL="https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64"
              sudo curl -L $URL -o /usr/local/bin/docker-compose
              docker-compose version
            displayName: Fix docker-compose version
```
since the upgrade to 1.27.x is causing the issue

**Comment by miketimofeev** [comment]
I'm going to close the issue since we can't do much with compose bugs. Feel free to reopen it if you have any concerns.
Thank you!
