### ISSUE TITLE
Add Nix package manager

### ISSUE THREAD

**Issue by samuela** [actions/virtual-environments#1579]
**Tool information**
- Tool name: Nix
- Tool license: 
- Add or update? add
- Desired version: latest at the time of writing is 2.3.7
- Approximate size: <300Mb
- If this is an add request:
  - Brief description of tool: Nix is a declarative package manager that makes it dead simple to install build and use any tool in the Nixpkgs ecosystem. Adding Nix would obviate the need for most other tool requests.
  - URL for tool's homepage: https://nixos.org/
  - Provide a basic test case to validate the tool's functionality: 
```
$ nix-shell -p python3 nodejs go rustc
[nix-shell] $ node --version
v10.20.1
[nix-shell] $ go version
go version go1.14.1 linux/amd64
[nix-shell] $ rustc --version
rustc 1.42.0
```

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Sometimes? See https://discourse.nixos.org/t/installing-nix-on-github-actions/3810.

**Tool installation time in runtime**
~10-15s

**Are you willing to submit a PR?**
sure!

**Comment by maxim-lobanov** [comment]
Hello everyone, have you considered using [official Nix action](https://github.com/cachix/install-nix-action) to install it in runtime? 
It is pretty fast (10-15 seconds) and require minimal additional code

**Comment by samuela** [comment]
Thanks for the pointer, @maxim-lobanov ! I wasn't ware of that Action, I'll give it a shot. I still think it would be great to have it included in the VM images but this is certainly helpful in the meantime.

**Comment by maxim-lobanov** [comment]
Considering the fact that there is an official action for Nix installation and installation in runtime is pretty quick, we wouldn't like to bake this tool into image at the moment.
Usually, Official actions provide better UX because you can install specific version using it (it means you won't be affected by any breaking change in new versions of tool). Also actions provide build-in configuration of tool after installation.

Please let us know if you have any concerns / objections.

**Comment by rickynils** [comment]
For reference, there is also https://github.com/marketplace/actions/nix-quick-install
