### ISSUE TITLE
Add JFrog CLI to Runners

### ISSUE THREAD

**Issue by IAmHughes** [actions/virtual-environments#1598]
**Tool information**
- Tool name: JFrog CLI
- Tool license: 
- Add or update? Add
- Desired version: Latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Allows interaction with jFrog tools such as Artifactory
  - URL for tool's homepage: [JFrogCLI](https://www.jfrog.com/confluence/display/CLI/JFrog+CLI)
  - Provide a basic test case to validate the tool's functionality: 

```.sh
jfrog --help
```

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

No time available now, but I can maybe do this later

**Comment by maxim-lobanov** [comment]
@IAmHughes , Hello, thank you for feature request!
As I know, There is an [official task](https://github.com/marketplace/actions/setup-jfrog-cli) to install JFrog CLI in runtime.
it installs this tool pretty quick (3-5 seconds). Does it work for you?

**Comment by IAmHughes** [comment]
@maxim-lobanov thanks! That's great and will work. It doesn't NEED to be on the image but saving seconds is always nice, especially if I'm building an action that wraps the JFrog CLI.

**Comment by maxim-lobanov** [comment]
@IAmHughes , considering the fact that there is an official task and installation in runtime is very quick, we wouldn't like to bake this tool into the image.
We are trying not to add new tool if there is an official task. Setup task usually provide significantly better UX because you can specify specific version of tool and tool owners have better experience to fix any issues. Also it allows us to avoid additional maintenance in future.

Please let me know if you have any questions / concerns.
