### ISSUE TITLE
What kind of tools do u use to be sure that backward compatibility is not broken?

### ISSUE THREAD

**Issue by pekhota** [actions/virtual-environments#1643]
Hi. Do u have any kind of action.yml or something that u use as a test to be sure that virtual machine backward compatible? 
I'm asking this because there are a lot of action.yml across the github and it is very easy to deploy new version of the image (ex ubuntu1804) which will be backward incompatible or something. So, my question is do you have any tests to run on the machine to make sure that everything is fine?

**Comment by maxim-lobanov** [comment]
Hello @pekhota ,
We have validation gates that contain a bunch of smoke (very simple) tests for every tool to validate that the tool is installed on image successfully.
As for the backward compatibility - on images, we always install the latest version of every tool (we have a few tools where we manage multiple versions but we are trying to avoid such cases due to maintenance concerns). So if new version of tool contains breaking changes, it could affect customers' builds because we can't freeze previous version forever.

For such tools, where new versions often contains breaking changes, we suggest using [tasks](https://github.com/marketplace?type=actions) to install specific version of tool in runtime.

**Comment by pekhota** [comment]
I'm going to create aws image with the idea to modify only packer configuration. Are that smoke tests available in public so I could run them on my aws ec2 instance?

**Comment by maxim-lobanov** [comment]
Installation scripts contain tests like `<tool> --version`. They will be run automatically during image-generation
As for the more complex tests, unfortunately, No. They are private ones for now

**Comment by pekhota** [comment]
Will you do code review and is it possible to accept pull request with aws packer provider?

**Comment by maxim-lobanov** [comment]
@pekhota will it be a separate template or just extending the current one?
AWS packer provider is not our use-case because we build in Azure so if this will require additional maintenance in future, we won't be able to accept it

**Comment by pekhota** [comment]
@maxim-lobanov Just extending the current one. Is it more preferable for you?

**Comment by maxim-lobanov** [comment]
Hello @pekhota , we have discussed it internally and we won't be able to accept this contribution.
Our main use case is image generation in Azure. We use this approach for image-generation and deployment VMs.
If we accept contribution, we will have to support AWS approach. Unfortunately, we don't have much experience with AWS and we won't be able to help customers if they face with any issues during AWS generation.
