### ISSUE TITLE
Publish Publicly Available copies of environments

### ISSUE THREAD

**Issue by dfreilich** [actions/virtual-environments#1649]
**Description**  
I would like to use the `ubuntu-latest` runner in a [Github Actions container](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer), and I would like to use the `ubuntu-latest` runner. I was unable to find a publicly available package of the environment, however, on any public docker registry. Please publish one, or clarify where it can be found. 

**Area for Triage**:  

**Question, Bug, or Feature?**:  

"Feature/Question"

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
A description of what you expected to happen.
A link/clarification as to where you can find the runner.

**Comment by maxim-lobanov** [comment]
Hello @dfreilich , we can't publish the built images to any storage or distribute them somehow due to legal issues (licenses of tools that are included to images)
You can find some details in related issue: https://github.com/actions/virtual-environments/issues/176#issuecomment-620638942
We are working with legal team to improve this in future but no solution for now.

**Comment by dfreilich** [comment]
Thanks for the fast response! I hope you can work something out for the future 😄
