### ISSUE TITLE
Cached Docker images are not always present

### ISSUE THREAD

**Issue by vgubar** [actions/virtual-environments#1660]
**Description**  
After MS is publishing new windows docker images to registry agent cache is not updated for a few weeks accordingly.
So cached layers are missing on agents and it is increasing time of container initialisation 2-3 times.

**Area for Triage**:  
Docker, Container, Image

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] Windows Server 2019

**Expected behavior**  
Renew of agent docker cache should be synchronised with adding new windows related images to the registry.

**Actual behavior**  
Few weeks after MS is publishing new windows related docker images agent docker cache is wrong, so all image layers except core are redownloaded. This is increasing container initialisation 2-3 times.

**Repro steps**  
Wait for new docker windows images to be pushed to registry ( as example mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019 ) and try to use it inside pipeline. Cache will not be used, all layers except one will be redownloaded

**Comment by Darleev** [comment]
Hello, @vgubar 
Docker images and cache are updated every week, in rare cases 2-3 times a week. So this is the expected behavior and sometimes the images can be out of date. You can track current release status using[ the link](https://github.com/actions/virtual-environments/#available-environments).

In case of any questions, feel free to contact us.

**Comment by vgubar** [comment]
We are having such issue 4 times during last 6 months. 3 issues were opened for support but they are redirecting us here. It is very critical for our builds, since container initialization time with not valid cache near 25 minutes, instead of 11 max.

**Comment by LeonidLapshin** [comment]
Hi, @vgubar!
As @darleev mentioned, this situation happens when the release cycle takes longer than usual. Currently, we tend to deploy new  Windows images, with up-to-date docker images, weekly. The propagation process usually starts on Monday and finishes on Thursday. Unfortunately, there are some cases (which you have faced with) when we have to postpone the update process and the docker layers stale at the images. For now, there is no obvious way to somehow work around this issue for hosted runners, but we're constantly working on lowering the image deployment delay rate to avoid such problems in the future.
A possible solution is to set up a self-hosted runner (https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners) where you can easily define any schedule that will update docker images on that runner within your requirements.
We're going to close the issue, but please feel free to contact us if you have any questions.
Thank you!
