### ISSUE TITLE
10022 port is not allowed to be used by embedded test execution server

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#1666]
Associated GitHub Community ticket: https://github.community/t/10022-port-is-not-allowed-to-be-used-by-embedded-test-execution-server/133903

The customer set 10022 port in their workflow to be used by embedded test execution server, but the 10022 port seems is not allowed. When they changed the port from 10022 to any others, the workflow can work.

**Comment by LeonidLapshin** [comment]
Hi, @Ginxo @BrightRan 
I tried to reproduce the problem with 10022 port with nginx container on 10022
```
docker run --name test-10022-nginx -d -p 10022:80 nginx:latest
curl http://localhost:10022
```
But everything work just fine, it seems that the problem is not about the port, but the connection to port on localhost. 
We have seen similar problems here: [flaky networking](https://github.com/actions/virtual-environments/issues/1187) 
Could you please try to disable hardware network offloading at the start of the build? For ubuntu the proper way is:
`sudo ethtool -K eth0 tx off rx off`
I hope it will help, please share with more details if any, thank you!

**Comment by LeonidLapshin** [comment]
@Ginxo, @BrightRan 
Could you please provide a feedback for the provided workaround?
Thank you!

**Comment by Ginxo** [comment]
Hi @LeonidLapshin @BrightRan 
at the beginning we thought it was due to the environment (GA runner), and it was, but could check it was not only happening there. So we open a ticket https://issues.redhat.com/browse/JBPM-9402 in our side and after this PR https://github.com/kiegroup/droolsjbpm-integration/pull/2261/files the job is working https://github.com/kiegroup/droolsjbpm-integration/runs/1207831159
Sorry for wasting your time and many thanks for your support.
