### ISSUE TITLE
Provide SSH host keys for GitHub services out of the box

### ISSUE THREAD

**Issue by mpdude** [actions/virtual-environments#1669]
Dear GitHub,

would it be possible to set up Action worker nodes in a way that we already have the SSH Host Keys for GitHub services (repos, Gists) etc. available in either /etc/ssh/ssh_known_hosts or ~/.ssh/known_hosts? 

That would make workflows somewhat more straightforward when we e. g. need to fetch dependencies.

Also, it would be more secure than having to run `ssh-keyscan` and just accept whatever keys we find. You should be in the best position to always provide the correct and up-to-date keys :wink:.

Thanks!

**Comment by Darleev** [comment]
Hello @mpdude,
Thank you for contacting us.
Could you please clarify which agent (OS) you are facing the problem with?
We are looking forward to your reply.

**Comment by mpdude** [comment]
Oops, my bad! I double-checked `ubuntu-18.04` and `ubuntu-20.04` and in fact, the RSA key is there at `/etc/ssh/ssh_known_hosts`.

It seems GH also has a `DSA` type key; would it make sense to add those as well?

**Comment by vsafonkin** [comment]
Hello @mpdude , it's right, RSA key for github.com was already added to `/etc/ssh/ssh_known_hosts` on Ubuntu. We believe it makes no sense to add DSA key, because it was deprecated by OpenSSH since version 7.0: [link](http://www.openssh.com/legacy.html)

**Comment by mpdude** [comment]
Ok, thank you

**Comment by adamrogas** [comment]
I recently came across a related issue when using (in my case ubuntu 20.04 based) service containers... 

obviously you can't add keys to unknown service container images but because of the environment mapping that occurs as they are mounted it makes working with them somewhat confusing.

in most cases a user would assume `~/`  is the home directory of the current user and when using it on mounted service container it takes you to `~/github/home` but tools like SSH are aware you are really running as root and look for the hidden `.ssh` directory at `/root/.ssh'.

**Comment by Tranduchuy12** [comment]
8571944
