### ISSUE TITLE
macOS needs Xamarin.iOS 14.0

### ISSUE THREAD

**Issue by ramtechjoe** [actions/virtual-environments#1698]
The latest upgrade to Visual Studio is at Xamarin.iOS 14.0.0.  However, this is not included in the current macOS 10.15 image.  This causes builds to fail if built on the latest Visual Studio and using macOS 10.15 build host (e.g., Add Center)

**Comment by maxim-lobanov** [comment]
Hello, Xamarin.iOS 14.0 has been already added to image-generation scripts: https://github.com/actions/virtual-environments/pull/1663
The new image with Xamarin.iOS 14.0 will be deployed in a week.

**Comment by ramtechjoe** [comment]
Thank you for the fast response and update.  I had seen that issue but wasn't clear because it showed merged but I didn't see the updated vm image.  Thank you for letting me know the schedule of the release and clarifying the issue.

**Comment by maxim-lobanov** [comment]
@ramtechjoe , if you don't mind, let's keep your issue opened with `awaiting-deployment` label until new image with Xamarin is deployed everywhere.

**Comment by ramtechjoe** [comment]
Sounds good!

**Comment by maxim-lobanov** [comment]
Hello everyone!
The new image with Xamarin.iOS 14.0 has already been deployed (See #1737). Please pay attention that it is not set by default yet because default Xcode 11.7 is not compatible with it.  
We are going to update default Xcode to 12.0 in a few weeks and after that will set Xamarin.iOS 14.0 by default.
For now, you can switch Xamarin.iOS to 14.0 using [Setup Xamarin](https://github.com/marketplace/actions/setup-xamarin) task with parameters:
```
with:
    xamarin-ios-version: 14.0
```
