### ISSUE TITLE
Update Ubuntu images packages more frequently and/or run "sudo apt update && sudo apt upgrade" as part of job setup

### ISSUE THREAD

**Issue by FranciscoPombal** [actions/virtual-environments#1757]
**Description**  

Recently, I observed the following job failures on Ubuntu 18.04:

https://github.com/qbittorrent/qBittorrent/runs/1220463176?check_suite_focus=true
https://github.com/qbittorrent/qBittorrent/pull/12086/checks?check_run_id=1220615532

At first I thought it was a spurious error, but then I realized that the true cause was outdated packages/package lists.

My solution was to add `sudo apt update && sudo apt upgrade` before anything else is done:
https://github.com/qbittorrent/qBittorrent/pull/13480/checks?check_run_id=1220719732

This solved the problem, but I noticed it also increased the CI time quite considerably, because a ton of packages had to be upgraded. So I would suggest either, or both:

- Updating the packages in the Ubuntu images more frequently, so that `sudo apt update && sudo apt upgrade` executes faster.
- Running the aforementioned commands as part of the job setup, because it has to be done anyway.

**Area for Triage**:  
Packages

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  

Packages/package lists in the image are up to date.

**Actual behavior**  

They're not, one has to manually update them as part of the job.

**Repro steps**

See example runs linked above.

**Comment by al-cheb** [comment]
Hello, @FranciscoPombal 
Currently, it's impossible to run `sudo apt update && sudo apt upgrade` on every agents as part of pre-build step, because it would affect timing for 100% of ubuntu pipelines and create unpredictable behavior after upgrade. I don't think it's right approach to update the whole system using `sudo apt upgrade`. You should always use `sudo apt update` before running apt-get install to update packages cache and update only particular packages what you use in your CI.

**Comment by FranciscoPombal** [comment]
@al-cheb 

Thanks for the answer. If a full upgrade as part of the pre-build step is out of the question, what about just the `sudo apt update`? Seems reasonable, since this is something everyone should/will be doing anyway.

And what about increasing the frequency of the image upgrades, or making sure they contain a more updated package base?

**Comment by al-cheb** [comment]
> @al-cheb
> 
> Thanks for the answer. If a full upgrade as part of the pre-build step is out of the question, what about just the `sudo apt update`? Seems reasonable, since this is something everyone should/will be doing anyway.
> 
> And what about increasing the frequency of the image upgrades, or making sure they contain a more updated package base?
1. Currently, we deploy a new image once a week or two, but sometimes external factors block a deployment and there is nothing we can do from our side.

2. `sudo apt update` - it would affect 100% builds and most of them don't use `apt install` at all, thus wasting agent time resources, that's why we don't include it as a pre-build step.

**Comment by al-cheb** [comment]
@FranciscoPombal, I will let you know if we have any updates in this direction.

**Comment by marc-hb** [comment]
Here's a more recent example. This one fails because Ubuntu removed a supposedly insecure package from http://security.ubuntu.com/ubuntu . If Ubuntu had not removed it, the build would have passed... with an insecure package.

https://github.com/thesofproject/sof-test/pull/584/checks

```
Get:15 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 python3-olefile all 0.46-2 [33.7 kB]
Ign:16 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 python3-pil amd64 7.0.0-4ubuntu0.1
Get:17 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 python3-tk amd64 3.8.5-1~20.04.1 [103 kB]
Get:18 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 python3-scipy amd64 1.3.3-3build1 [11.1 MB]
Err:16 http://security.ubuntu.com/ubuntu focal-updates/main amd64 python3-pil amd64 7.0.0-4ubuntu0.1
  404  Not Found [IP: 52.252.75.106 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/pillow/python3-pil_7.0.0-4ubuntu0.1_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
Fetched 15.2 MB in 1s (21.1 MB/s)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Available at http://security.ubuntu.com/ubuntu/ubuntu/pool/main/p/pillow/ right now: `python3-pil_7.0.0-4ubuntu0.2_amd64.deb` (and many others)

**Comment by marc-hb** [comment]
After the python3-pil_7.0.0-4ubuntu0.1_amd64.deb example above, here's the new broken link of the day:

http://security.ubuntu.com/ubuntu/pool/main/o/openjdk-lts/openjdk-11-jre_11.0.9.1+1-0ubuntu1~20.04_amd64.deb  MISSING

(upgraded to openjdk-11-jre_11.0.9+10-0ubuntu1_amd64)


> Currently, we deploy a new image once a week or two, but sometimes external factors block a deployment and there is nothing we can do from our side.

I understand deploying a new `apt UPGRADEd` image requires significant validation time. On the other hand you could and should provide images that have _already_ been `apt UPDATEd` images at least a couple times a day - exactly like all "normal" Ubuntu systems.

> sudo apt update - it would affect 100% builds and most of them don't use apt install at all, thus wasting agent time resources, that's why we don't include it as a pre-build step.

Don't get me wrong: I'm NOT requesting to automatically prefix every workflow with `apt update`, that would indeed be a massive duplication and waste of resources. I'm asking for github to provide images where the package index has _already_ been `apt updated` ONCE for everyone. This requires zero validation because the package index does not affect functionality at all (unless you actually use the package index - but then you obviously don't want one with broken links)

By holding on to an obsolete package index with broken links to security.ubuntu.com, you're forcing every user who wants to install a couple extra packages to start with `apt update` which wastes "agent time resources" = exactly what you're trying to avoid.

@al-cheb we need to either re-open this issue or file a more specific one.

**Comment by maxim-lobanov** [comment]
@marc-hb , the current behavior is by design and it is not something that we are planning to change in future.
After image generation, image state is frozen (snapshot is generated) and applied to all VMs. After running builds, machine is reverted to the snapshot. We don’t modify image state somehow after image-generation, running such updates before each build will make image a bit different for every build, which reduces image reliability.
We regenerate images and redeploy VMs on weekly basis and it means that apt package index can be 1 week old.
If you install any apt packages in runtime, you should run `apt update` as a part of your build.

**Comment by marc-hb** [comment]
Thanks @maxim-lobanov for the prompt answer and clarification, really appreciated.

>  We don’t modify image state somehow after image-generation, running such updates before each build will make image a bit different for every build, which reduces image ~reliability~ determinism.

I totally understand the logic but as far as the _package index_ is concerned this is not a correct statement. A more recent package index does not make the build different / less deterministic because it has no effect unless you actually use it to download software. In that latter case you can forget about determinism anyway because only the latest index works:

> If you install any apt packages in runtime, you should run apt update as a part of your build.

Sad but understood. Please document this, maybe at
https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners ?

BTW the following example does not have any "apt update": https://docs.github.com/en/actions/learn-github-actions/migrating-from-circleci-to-github-actions#complete-example

**Comment by maxim-lobanov** [comment]
cc: @AlenaSviridenko what do you think about adding information about it in image documentation or GH docs?

**Comment by marc-hb** [comment]
@al-cheb , @maxim-lobanov , @AlenaSviridenko please  help document this important and problematic `apt-get update` requirement that it is not required on regular Ubuntu systems. Unlike github images, regular Ubuntu systems  update their indexes in the background: 
https://askubuntu.com/questions/1139545/how-do-i-utterly-stop-automatic-update-checks-in-ubuntu-19-04
Regularly updating package indexes in the background allows Ubuntu to remove (insecure) packages from servers after some time without breaking `apt-get install`

Let me know whether  I should file a new documentation issue different from this one.

It's an important requirement because builds randomly fail without apt-get update. It's a problematic and non-intuitive requirement because it's not required on regular Ubuntu systems and wastes time and resources in every build when it could be done once for all in the system image itself. I mean `apt-get update`, NOT `apt-get upgrade` - the latter and only the latter would affect determinism.

**Comment by catthehacker** [comment]
Since when Ubuntu "server edition" updates indexes automatically? I've never heard of such thing. There is only unattended upgrades option which derives from Debian.
I think you are confusing server version with desktop version of Ubuntu.

**Comment by marc-hb** [comment]
```
# dpkg -s update-notifier-common

Description: Files shared between update-notifier and other packages
 Apt setup files and reboot notification scripts shared between
 update-notifier and other packages, NOTABLY FOR SERVER USE CASES.
```

```
$ ssh any_ubuntu_system

Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.10.0-rc1-sof+ x86_64)

X updates can be installed immediately.
Y of these updates are security updates.
```
Outside extremely strict control of network usage (clearly not servers), there is simply no reason not to run `apt-get update` in the background.

**Comment by marc-hb** [comment]
Ubuntu's "server edition" should not even matter anyway. I don't know which particular Ubuntu edition (if any) the github virtual environment is based on but after github customization[*], the default package selection should not be specialized for server-side development and fortunately it does not look like it is.

[*] https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md

**Comment by maxim-lobanov** [comment]
@marc-hb , Totally makes sense to me. I will take about updating GH documentation.
@marc-hb , if you prefer - could you please log an issue in this repository just to track this work?

**Comment by marc-hb** [comment]
Thanks  @maxim-lobanov , I filed #2924
