### ISSUE TITLE
Add [DENO] as a preinstalled RTE to improve execution speed

### ISSUE THREAD

**Issue by michael-spengler** [actions/virtual-environments#1777]
Corresponding Discussion:  
https://github.community/t/github-actions-deno-support/135130/4

Example: 
https://github.com/michael-spengler/github-action-with-deno

**Comment by LeonidLapshin** [comment]
Hey, @michael-spengler 
Could you please provide all information requested in [issue template](https://github.com/actions/virtual-environments/issues/new?assignees=&labels=feature+request%2C+needs+triage&template=tool-request.md&title=Update%2FAdd+%5Btool+name%5D) ?

**Comment by maxim-lobanov** [comment]
Hello @michael-spengler , thank you for feature request.

There is [an action to install Deno](https://github.com/denolib/setup-deno) in runtime and it takes about 2-4 seconds to install any version. It is pretty fast. Also, actions provide better experience than pre-installed software because it allows to install or even freeze specific version instead of having latest version always.
Considering installation time and maintenance concerns, we wouldn't like to bake this tool into the image.

**Comment by michael-spengler** [comment]
@maxim-lobanov sorry for my late response - I understand it's pretty quick however there are scenarios where each second counts in order to provide a good user experience - e.g. in the context of https://github.com/cla-assistant/github-action

--> we did not switch to a deno based version there just to save seconds for a good user experience - while user interacts with the PR.

I really can imagine there will be many Deno based GitHub Actions which would suffer from this delay.

**Comment by maxim-lobanov** [comment]
Thank you for providing additional information.

Task provides significantly better experience than we can provide from image side because you can select the specific version and installation process is controlled by Deno owners. On image, we would install the latest version always. It means that any new version with breaking changes will break customers and they have to switch to previous version via task. Also there is a delay with image deployment and delivering new versions.

When we decide whether to add a tool, we have to consider a lot of factors like tool installation time, size and maintenance effort, existence of action, complexity of runtime installation. The problem is that every new tool brings additional maintenance effort on long term. So considering the fact that this tool installation time is very quick (just a seconds), it is not something that we would like to bake into the image.

We will be able to revisit this decision later if we see more requests.
