### ISSUE TITLE
GITHUB_WORKSPACE evaluting to blank

### ISSUE THREAD

**Issue by timheuer** [actions/virtual-environments#1794]
**Description**  
Per the documentation: https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables
The `GITHUB_WORKSPACE` variable should evaluate to a path.  When using in a workflow (after checkout) however, it is evaluating to nothing and not providing the path both on ubuntu-latest/windows-latest

Example: https://github.com/timheuer/buildtest/runs/1243185809?check_suite_focus=true#step:3:2 from workflow: https://github.com/timheuer/buildtest/blob/master/.github/workflows/build.yml#L40

**Area for Triage**:  
Servers

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
I expect to see a full path to the workspace per documentation

**Actual behavior**  
A blank variable is provided

**Repro steps**  
See example repo that has an echo of the variable evaluating to nothing

**Comment by maxim-lobanov** [comment]
Hello @timheuer , you use incorrect way to reference this variable.
If you would like to reference GITHUB_WORKSPACE as environment variable, you should use:
```
$env:GITHUB_WORKSPACE # powershell
$GITHUB_WORKSPACE # bash
```

If you would like to use `{{}}` syntax, you should use
```
${{ github.workspace }} 
```

Please follow documentation: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context

**Comment by LanceMcCarthy** [comment]
That's the confusing part. Yes, you can directly use the GitHub context `${{ github.workspace }}`. However, according to the docs, you can read the workspace GitHub context value as an environment variable.

https://twitter.com/lancewmccarthy/status/1315686054113021957
![image](https://user-images.githubusercontent.com/3520532/95769909-94691e00-0c86-11eb-984d-0032d12427c9.png)

Since we know this `$env:GITHUB_WORKSPACE` works in PowerShell... `${{ env:GITHUB_WORKSPACE }}` should also work.



Is there an easy way to test commands on a local runner without requiring a trigger? Running commands inside PowerShell only gets you so far, especially when you rely on the way Actions packs up the steps as ps1 files.

**Comment by maxim-lobanov** [comment]
I don't have much context about this logic because it is owned by https://github.com/actions/runner.
In my understanding, `${{ env:* }}` is not equal PS `$env:*`. Through `${{ env: }}` you can only access the variables that are set by your workflow because such expressions are evaluated by runner and they don't have an access to machine environment.

```
The env context contains environment variables that have been set in a workflow, job, or step
```
so you can access only variables that are set in YAML like below or similar
```
env:
  SERVER: production
```

**Comment by maxim-lobanov** [comment]
Closing this one but please let me know if you have any questions

**Comment by edwardskrod** [comment]
> That's the confusing part. Yes, you can directly use the GitHub context `${{ github.workspace }}`. However, according to the docs, you can read the workspace GitHub context value as an environment variable.
> 
> ![image](https://user-images.githubusercontent.com/3520532/95769909-94691e00-0c86-11eb-984d-0032d12427c9.png)
> 
> Since we know this `$env:GITHUB_WORKSPACE` works in PowerShell... `${{ env:GITHUB_WORKSPACE }}` should also work.
> 
> Is there an easy way to test commands on a local runner without requiring a trigger? Running commands inside PowerShell only gets you so far, especially when you rely on the way Actions packs up the steps as ps1 files.

I just ran into this same issue, thinking I could use "${{ env:GITHUB_WORKSPACE }}"

**Comment by michael-hawker** [comment]
Ran into this as well... these variables are still called out in this doc here: https://docs.github.com/en/actions/learn-github-actions/variables (which I find very unhelpful at explaining how to setup and use `env` properly). 

The note in blue at the bottom of the long list of variable examples is not highlighted well enough:

> Most of the default variables have a corresponding, and similarly named, context property. For example, the value of the GITHUB_REF variable can be read during workflow processing using the ${{ github.ref }} context property.
