### ISSUE TITLE
Add Pack CLI

### ISSUE THREAD

**Issue by eddumelendez** [actions/virtual-environments#1821]
**Tool information**
- Tool name:  Pack CLI
- Tool license:  Apache-2.0 License
- Add or update?  Add
- Desired version:  0.14.2
- Approximate size: 
- If this is an add request:
  - Brief description of tool:  Allow you to create docker images taking advantage of buildpacks
  - URL for tool's homepage:  https://github.com/buildpacks/pack
  - Provide a basic test case to validate the tool's functionality:  `pack --version`

**Area for Triage**:

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

Yes

**Comment by AlenaSviridenko** [comment]
Hi @eddumelendez,
this tool can be installed in runtime in a second, also, there is an action for it [actions/pack-docker-action](https://github.com/marketplace/actions/pack-docker-action). Please, consider using these two options to work with Pack CLI.
Closing this issue due to installation and usage simplicity.
Feel free to create a new one in case of any other questions. Thanks!
