### ISSUE TITLE
Fails when using VM without temporary disk

### ISSUE THREAD

**Issue by JvanDerPaal** [actions/virtual-environments#1842]
Packer build fails when using a VM Size that does not contain a temporary disk.
I have found one area in which the D: is explicitly referenced, this is for the disk expansion and causes the build to run out of space, In future I will test further by bypassing this using the below example on how to natively extend the disk in powershell and not use the write to D: drive to see if it fails elsewhere. 

**Area for Triage**:  
Scripting and command line

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**  
build to complete all toolset installations

**Actual behavior**  
it seems to silently fail to extend the disk 
unexteded disk fills up and fails here every time: ==> vhd: ERROR: Can not set length for output file : There is not enough space on the disk. : C:\Users\packer\AppData\Local\Temp\boost-1.72.0-win32-msvc14.2-x86_64\boost-1.72.0-win32-msvc14.2-x86_64.tar

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Create image using VMSzie with no temp disk such as Standard_D4s_v4
2. Run packer build

**Suggestion**
Recommend you don't "hardcode" D: into any scripts.
The script where the C drive is extended uses this in the Vm init script
try using powershell native commands e.g.
$size = Get-PartitionSupportedSize -DriveLetter C
Resize-Partition -DriveLetter C -Size $size.SizeMax

**Comment by al-cheb** [comment]
Hello, @JvanDerPaal 
We don't use a temp disk  disk during image generation process.  As you can see in the configs [windows2016.json](https://github.com/actions/virtual-environments/blob/main/images/win/windows2016.json) and [windows2019.json](https://github.com/actions/virtual-environments/blob/main/images/win/windows2019.json) for windows images, we define a disk size - `"os_disk_size_gb": "256"`, instead of default 128gb disk size which is not enough, since an image size after generation is more than 128gb.
