### ISSUE TITLE
Add Ubuntu 20.10 groovy

### ISSUE THREAD

**Issue by tobiasdiez** [actions/virtual-environments#1862]
**Tool information**
- Tool name: Ubuntu 20.10
- Tool license: 
- Add or update? Add 
- Desired version: beta (RC planned for 10/22/2020)
- Approximate size: large
- URL for tool's homepage: https://releases.ubuntu.com/20.10/

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**
No

**Comment by miketimofeev** [comment]
Hi @tobiasdiez!
We do not plan to offer other non-LTS ubuntu versions. We recommend using Docker if you'd like to build using other distributions with the hosted virtual environments. Alternatively, you can leverage self-hosted runners and fully customize your environment to your needs.
I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!

**Comment by SolidHal** [comment]
@miketimofeev I understand the policy of only supporting ubuntu LTS releases, but this leaves maintainers using qemu in a bit of a pickle. 
Please see bug: https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1895456
Because of this, simply using docker is not a fix. 
Even if the docker-guest os has the patched qemu version, this bug gets hit because the docker-host os must also have it. 
As you can see from the bug report, the ubuntu devs won't be backporting the fixes to 20.04. 
This means that anyone using github actions to cross compile binaries will be required to use 3rd party ppas to install the newer version of qemu-user-static. 
This issue isn't immediately obvious to debug either, as the way the host vm, docker, and qemu interact is a bit opaque.

**Comment by letmaik** [comment]
Hitting the same issue. I'm developing a library that relies on video4linux2 and hence the videodev kernel module. However, that module is only [shipped](https://packages.ubuntu.com/search?suite=groovy&arch=any&mode=exactfilename&searchon=contents&keywords=videodev.ko) with `linux-modules-extra-azure` starting from Ubuntu 20.10. Given that 22.04 LTS is a year away I currently have to disable any testing on Linux.

**Comment by christianparpart** [comment]
> Hitting the same issue. I'm developing a library that relies on video4linux2 and hence the videodev kernel module. However, that module is only [shipped](https://packages.ubuntu.com/search?suite=groovy&arch=any&mode=exactfilename&searchon=contents&keywords=videodev.ko) with `linux-modules-extra-azure` starting from Ubuntu 20.10. Given that 22.04 LTS is a year away I currently have to disable any testing on Linux.

same here, but a different system dependency library that's not available before 20.10 (catch2).

**Comment by danger89** [comment]
This is really really a shame GitHub! Please, just support 20.10!
