### ISSUE TITLE
Install BizTalk project build tools in pipeline build agent hosts.

### ISSUE THREAD

**Issue by Elvis-Shi** [actions/virtual-environments#1865]
Tool name: BizTalk project build component
Tool license: Developer license
Add or update? Add
Desired version: 3.13.*.*
Approximate size: 15 MB(Msi Install package) + 15MB(vsix install package)
If this is an add request:
Brief description of tool: BizTalk is a Microsoft product, you can refer to here to get more understanding about what is BizTalk. Our customer use BizTalk development tools, which are built on top of Visual Studio, to create, and build BizTalk solutions. We also created an Azure devOps pipeline component "Deploy BizTalk Application" for deployment, while customers are also willing to use Azure DevOps pipeline hosted agent to do the build.

URL for tool's homepage: https://docs.microsoft.com/en-us/biztalk/core/developer-tools

Provide a basic test case to validate the tool's functionality: if msbuild biztalk.sln can give success, then it works.

Area for Triage:
Servers

Question, Bug, or Feature?:
Feature

Virtual environments affected

 Windows Server 2019
Can this tool be installed during the build?
Yes.

Tool installation time in runtime
2 mins(MSI installation) + 5 mins(vsix installation).

Are you willing to submit a PR?
Yes.

**Comment by maxim-lobanov** [comment]
Hello, I have marked this issue as `community feature`. Feel free to submit PR.

**Comment by maxim-lobanov** [comment]
@Elvis-Shi , I have merged your PR. Changes should be deployed to all Hosted VMs by the end of next week

**Comment by LeonidLapshin** [comment]
Hi, @Elvis-Shi !
BizTalk project build component successfully added to images.
Thank you!

**Comment by fabsenet** [comment]
hi @Elvis-Shi and others,

I feel like this component might need an update? I really cannot tell the correct version nummer, but https://marketplace.visualstudio.com/items?itemName=ms-biztalk.BizTalk&ssr=false lists version 3.13.2.0

This page https://support.microsoft.com/en-us/topic/service-pack-and-cumulative-update-list-for-biztalk-server-108e5e94-4558-8b57-d5fb-45984506d56f lists 3.13.785.0 as latest (CU2)

and finally the agent is currently using 3.13.765.0.

this update is of importance to me because I am maybe observing an error in my solution which was fixed with an updated version of the build tools? https://stackoverflow.com/questions/69827757/biztalk-map-error-only-when-building-in-azure-devops

**Comment by miketimofeev** [comment]
Hi @fabsenet!
We use the following link to install BizTalk https://aka.ms/BuildComponentSetup.EN — it is a zip archive containing Bootstrap.msi and BuildComponentSetup.msi files. The latest CU2 however is an EXE file and when I tried to apply it to the VM I got the error
![image](https://user-images.githubusercontent.com/48208649/140711917-15ce3069-34f1-4e97-8bb7-e7c5ea53f177.png)

**Comment by fabsenet** [comment]
I was reading the issue and the pullrequest and I feel like this buildcomponent setup was created just for azure devops. Maybe handmade by @Elvis-Shi ?

I have no idea, how I can help here tbh, I only know, I want/need the latest version :-)

the cumulative update is always an update for biztalk, but the agent has only some kind of minimal installation which is obviously not detected.

**Comment by miketimofeev** [comment]
@fabsenet could you file an issue for this problem? We will engage BizTalk team after that
