### ISSUE TITLE
Python 3.8 jobs on Ubuntu don't finish

### ISSUE THREAD

**Issue by tysonite** [actions/virtual-environments#1896]
**Virtual environments affected**  
- [x] Ubuntu 18.04 LTS + Python 3.8

For some reason, Python 3.8 jobs on Ubuntu 18.04 don't complete, and print:
![image](https://user-images.githubusercontent.com/196535/97092246-255ad480-164b-11eb-8a5f-e74f87ab745e.png)

Many of the pull requests have an yellow circle for days (even weeks). See [this](https://github.com/robotframework/robotframework/pulls) page.

**Comment by al-cheb** [comment]
Hello, @tysonite 
The issue doesn't relate to an image itself. Please post your answer  - https://github.community/

**Comment by tysonite** [comment]
This is not a question, this is some issue on github side. E.g. https://github.com/robotframework/robotframework/pull/2898 runs since Jul 8, 2018. But in 2018, there were no even actions or other CI in this project.

Please, have a look.

**Comment by al-cheb** [comment]
@dakale, Could you please take a look?

**Comment by maxim-lobanov** [comment]
@tysonite , I guess it is expected behavior.
As I can see, you have added your workflow 3 days ago: https://github.com/robotframework/robotframework/tree/master/.github/workflows
And marked it as `required`(https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-status-checks)
If some workflow is marked as `required`, GH enforces required checks to be run but they can't be run because they don't exist in PR branch.
You should pull the latest `master` branch to all pull-requests to invoke this check.

P.S. As it is mentioned in readme of this repository, we own only content of Hosted images and don't own other GitHub services. This issue is not related to content of Hosted images so it is better to raise it on GitHub Actions Community Forum.
> This repository contains the source used to create the virtual environments for GitHub Actions hosted runners, as well as the VM images of Microsoft-hosted agents used for Azure Pipelines. To file bug reports, or request that tools be added/updated, please open an issue using the appropriate template. To build a VM machine from this repo's source, see the instructions.
> For general questions about using the virtual environments or writing your Actions workflow, please open requests in the GitHub Actions Community Forum.

**Comment by tysonite** [comment]
Alright, thank you for clarification! I am still a bit concerned that required checks are applied to old PRs that were submitted before such checks have been enabled, but this looks to be a different issue. This is a bit confusing.
