### ISSUE TITLE
Add python 3.4.10 x86 (32 Bit)

### ISSUE THREAD

**Issue by blackjack4494** [actions/virtual-environments#1941]
**Tool information**
- Tool name: Python
- Add
- Desired version: 3.4.10 x86 (32 Bit)
- Approximate size:
- If this is an add request:
  - Brief description of tool: self explaining?!
  - URL for tool's homepage: https://www.python.org/downloads/
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature request

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Nope. Needed upfront.

**Tool installation time in runtime**
Matter of seconds.

**Are you willing to submit a PR?**
If I have to. Maybe some other people have experience with this already.

@maxim-lobanov @kaylangan

**Comment by AraHaan** [comment]
Please for the log of god include Windows as well.

**Comment by maxim-lobanov** [comment]
Hello @blackjack4494  , thank you for feature request.
For Ubuntu and MacOS, we build python from source code. It is pretty tricky to build those old versions. Some time ago we have tried but failed and wouldn't like to invest more time into it. For example, Python 3.4 end of life was more than 1 year ago.

For Windows, we will upload Python binaries because it doesn't require effort from our side. See #1943
