### ISSUE TITLE
[Question] msbuild path not found

### ISSUE THREAD

**Issue by eddynaka** [actions/virtual-environments#1978]
**Description**  
MSBuild wasn't found when you use a custom script instead of msbuild task

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Question: is it possible to add msbuild to PATH, if yes, how?

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
I would expect that MSBuild was found in the PATH, just like when you install the VS in your machine.

**Actual behavior**  
I have a custom msbuild script to build/test/etc my solution. This script is in powershell.
When I use any windows pipeline, msbuild isn't located in the PATH, so it fails.

**Repro steps**  
Execute any simple msbuild in powershell/command line instead of msbuild task

**Comment by maxim-lobanov** [comment]
Hello @eddynaka , it is expected behavior that I can reproduce on my local machine.
If you use default terminal "Command Line", msbuild and any other development tools are not available in PATH by default.
`msbuild` is available in PATH only in "Developer Command Prompt for Visual Studio". This console sets additional environment variables and configure environment for using msbuild and other build tools.

There is a official MS guide how to activate proper environment without task: https://github.com/microsoft/vswhere/wiki/Start-Developer-Command-Prompt

Also, there are a few official tasks to activate it:
- For GitHub Actions: https://github.com/marketplace/actions/setup-msbuild
- For Azure DevOps: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/msbuild?view=azure-devops

**Comment by eddynaka** [comment]
I see!

thanks for the quick response!

You can close this if you want!

**Comment by dibir-magomedsaygitov** [comment]
I'm going to close this issue. In case of any questions feel free to contact us.
