### ISSUE TITLE
MacOS jobs faills with the new image version 

### ISSUE THREAD

**Issue by etelvinacunha** [actions/virtual-environments#1981]
**Description**  
Jobs fails with Error:
Xcode build...
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/runner/work/1/s/Mobile/platforms/ios/Pods/CouchbaseLite/iOS/CouchbaseLite.framework/CouchbaseLite' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Area for Triage**:  
Apple

**Question, Bug, or Feature?**:  
"Bug",
**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Job run without error. 
The previous image version runs without any error. macos-10.15. Image Version: 20201017.1

**Actual behavior**  
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/runner/work/1/s/Mobile/platforms/ios/Pods/CouchbaseLite/iOS/CouchbaseLite.framework/CouchbaseLite' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
A description of what is actually happening.

**Repro steps**  
In the mac-os-10.15 version 20201017.1 the job runs ok, with the new image the jobs stops and exit with an error.
no changes were maded to yml file.

1. Step 1
2. Step 2

**Comment by maxim-lobanov** [comment]
Hello @etelvinacunha , 
Unfortunately, provided information is not enough to understand the issue.
Could you please provide:
- minimal repro steps for the issue (public repository with simple / minimal project where the issue is reproduced
- exact image version where your build has passed
- exact image where your build fails
- full build logs for both successful and failed builds
- Xcode version that you use for build

**Comment by etelvinacunha** [comment]
im running a pipeline azure and since October 30th  we have facing a error.
we did not make changes to the pipeline, but we now verify that the mac-os image version is different.

any help will be welcome.

please tell me if you need more details.

**successful build** 
[log_buid_20201027.txt](https://github.com/actions/virtual-environments/files/5488970/log_buid_20201027.txt)
**unsucessful build** 
[log_build_20201030.txt](https://github.com/actions/virtual-environments/files/5488971/log_build_20201030.txt)
[yml.txt](https://github.com/actions/virtual-environments/files/5489010/yml.txt)

**Comment by tim-fitzgerald** [comment]
https://github.com/actions/virtual-environments/issues/1933

This sxeems to be a very widespread consistent issue.

**Comment by maxim-lobanov** [comment]
@tim-fitzgerald , in that issue builds are not started. How it is related to this issue where builds fail on Xcode build?

@etelvinacunha , As I can see in YAML file, you rely on default version of Xcode.
In the recent image update, default Xcode was updated from 11.7 to 12.0
- Image diff: https://github.com/actions/virtual-environments/pull/1922/files
- Announcement: https://github.com/actions/virtual-environments/issues/1712

Errors in your build log is known issue with Xcode 12 and cocoapods. Cocoapods team has released Cocoapods 1.10 with proper support of Xcode 12 where this issue is fixed. See details in https://github.com/CocoaPods/CocoaPods/issues/9902

So you have the following options:
- Downgrade to Xcode 11.7 and continue using it for build
- Update cocoapods to 1.10 and use Xcode 12 for build

**Comment by maxim-lobanov** [comment]
I am closing this issue since there is no response.
Please let me know if steps above didn't resolve an issue

**Comment by etelvinacunha** [comment]
we downgrade to Xcode 11.7 and it works, thanks.
