### ISSUE TITLE
Xcode 12.1 replaced silently with Xcode 12.1.1 RC? 

### ISSUE THREAD

**Issue by asnaith** [actions/virtual-environments#1985]
At some point today it seems that `/Applications/Xcode_12.1.app/` was updated from Xcode 12.1 to Xcode 12.1.1 (which as of right now is still a release candidate). 

This is on the macOS-10.15 image 

<img width="785" alt="Screen Shot 2020-11-04 at 7 41 59 PM" src="https://user-images.githubusercontent.com/3982665/98195711-3e7b4500-1ed7-11eb-9a00-386426fce539.png">

**Comment by maxim-lobanov** [comment]
Hello @asnaith , usually, we install the latest Xcode for every major.minor pair.
For example, when Xcode 12.0.1 is released, we replace 12.0.0 by 12.0.1 (except cases when it is beta release)
Changing of patch version (third number) doesn't bring breaking changes because of semantic versioning and RC means that most likely this version will be officially published as stable.

Do you have any use-cases that are broken after this change?

**Comment by sisoje** [comment]
12.1.1 is not even released and it is breaking because it does not have ios14.1 simulators but only ios14.2 simulators

you need to test a bit before you deploy such things:

```
Run export DEVELOPER_DIR=/Applications/Xcode_12.1.app/Contents/Developer && xcodebuild test -scheme App -workspace ios/App/App.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.1' | xcpretty && exit 

xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:14.1, name:iPhone 12 }
```

**Comment by maxim-lobanov** [comment]
We are rolling back image. You can track progress in #1984
