### ISSUE TITLE
Update/Add bzr

### ISSUE THREAD

**Issue by tamalsaha** [actions/virtual-environments#200]
**Tool information**
- Tool name: Bazzar
- Add or update? Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: bzr is used by Go modules when downloading dependencies
  - URL for tool's homepage: https://bazaar.canonical.com/en/

**Area for Triage**: Go

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
```
sudo apt-get -qq update || true
sudo apt-get install -y bzr
```

The annoying part is sometimes the apt-get update fails. So, it will be easier if bzr was pre-installed.

**Are you willing to submit a PR?**
yes

**Comment by alepauly** [comment]
@tamalsaha - since bzr is not actively maintained/developed nor widely used, I don't think we should add it to the runner. An alternative I suggest is to write an Action that installs (and possibly attempts to deal with install failures) so that it's easy to include in new workflows. Thanks for the suggestion.
