### ISSUE TITLE
Unable to apt-get update on ubuntu-latest

### ISSUE THREAD

**Issue by naubryGV** [actions/virtual-environments#2092]
**Description**  
Hi, I'm wondering if this recent change #1816  could have bring some issue with ca-certificates:
This dockerfile (https://github.com/naubryGV/cpp-clang-check/blob/master/Dockerfile) was working pefectly fine yesterday, but now I'm getting those:
```
  W: http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease: No system certificates available. Try installing ca-certificates.
  W: http://security.ubuntu.com/ubuntu/dists/focal-security/Release: No system certificates available. Try installing ca-certificates.
  E: The repository 'http://security.ubuntu.com/ubuntu focal-security Release' does not have a Release file.
```
Not sure if it's the way to report those kind of issues.

**Area for Triage**:  
Containers

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [* ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Being able to run apt-get without error

**Actual behavior**  
apt-get update throws an error and the whole process have to stop
**Repro steps**  
You can easily recreate, by trying to add my GitHub action to your workflow and run it.
https://github.com/naubryGV/cpp-clang-check

**Comment by maxim-lobanov** [comment]
I can't reproduce it from my side.
Build Docker passes successfully on both `ubuntu-latest` and `ubuntu-20.04` labels: https://github.com/maxim-lobanov/test-repo/runs/1419712497?check_suite_focus=true. Run stage fails due to lack of token but I guess it doesn't matter.

Please pay attention that the that work that you refer #1816 is not started yet. So it can't impact you.
![image](https://user-images.githubusercontent.com/16715858/99567415-321ae000-29df-11eb-9ad8-5ffb7082776d.png)

Could you please share the link to the repo where you have repro for this issue?
Or attach screen of `Set up job` step for latest successful and the first failed build.
Example: 
![image](https://user-images.githubusercontent.com/16715858/99567614-68f0f600-29df-11eb-91af-34799942ddb3.png)

**Comment by naubryGV** [comment]
Thanks for the fast reply @maxim-lobanov.
Sorry for the confusion about #1816 I misunderstood the issue thread.
Here is the setup jobs when it failed:
![image](https://user-images.githubusercontent.com/73480455/99568180-1abb0300-299d-11eb-8859-c0643ed1012d.png)
And here is one when it worked:
![image](https://user-images.githubusercontent.com/73480455/99568281-3b835880-299d-11eb-80a9-c173d6e19b76.png)
The only change between the two is specify ubuntu-18.04 instead of latest, but I can see that there's the same OS version. I guess it was just an temporary issue, I will try again with ubuntu-latest and let you know

**Comment by maxim-lobanov** [comment]
@naubryGV , Yes, it looks like `ubuntu-18.04` is used for both builds.
Also, please pay attention on Version line. Both builds use `20201108.1` image version. It means that both builds are run on identical image.

**Comment by naubryGV** [comment]
Ok, so it was just a temporary hiccup, it's working now - go figure! Closing now - Thanks @maxim-lobanov
