### ISSUE TITLE
Update Homebrew formulae

### ISSUE THREAD

**Issue by ApsarasX** [actions/virtual-environments#2173]
**Tool information**
- Tool name: Homebrew formulae
- Tool license: BSD-2-Clause
- Add or update? update

**Question, Bug, or Feature?**:
I want to install antlr(v4.9) using homebrew in workflow, but antlr(v4.8) is installed. And I try to update homebrew using `brew update`, but it took a long time to finish. Please update brew's formula in time. Thanks!

**Virtual environments affected**
- [x] macOS 10.15
- [x] macOS 11.0

**Comment by miketimofeev** [comment]
Hi @ApsarasX!
We've set no auto-update intentionally here
https://github.com/actions/virtual-environments/blob/55d0c3bed6d1c8e1480a85a2d4965add4940b9fc/images/macos/provision/configuration/environment/bashrc#L30
Because of this issue: https://github.com/Microsoft/appcenter/issues/293
Usually, we update images weekly, but there was a deployment freeze due to holidays and we skipped the last week's deployment — that's why the update takes so long.
We're going to deliver a new image in the next few days, sorry for the inconvenience.
I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!
