### ISSUE TITLE
Remove all tools

### ISSUE THREAD

**Issue by RomainFallet** [actions/virtual-environments#222]
**Tool information**
- Tool name: None
- Add or update? Remove
- Desired version: None
- Approximate size: 0 Kb

**Area for Triage**: 

**Question, Bug, or Feature?**: Question

**Virtual environments affected**
- [*] macOS 10.15
- [*] Ubuntu 16.04 LTS
- [*] Ubuntu 18.04 LTS
- [*] Windows Server 2016 R2
- [*] Windows Server 2019

Hello,

I would like to have fresh virtual machines instead of preinstalled ones in order to test installation scripts with Github Actions.

Is it possible to have an uninstall/cleanup script that does the exact opposite of all pre-installation things which I could run before my tests?

Thanks!

**Comment by oldskool** [comment]
Sounds like you want a clean Docker container and do your things in there.

So get a Dockerfile like (all code below is untested/from the top of my head, but just for illustation):

```
FROM ubuntu:18.04

COPY your-install-script.sh /

ENTRYPOINT /your-install-script.sh
```

And then just build and run that from the runner:

```
- name: Build empty container
  run: docker build -t my-installer-test .

- name: Run it
  run: docker run --rm my-installer-test
```

Should allow you to do just what you want in an empty environment.

**Comment by RomainFallet** [comment]
What about MacOS and Windows? They cannot run in docker.

**Comment by alepauly** [comment]
@RomainFallet we don't support that and there aren't any plans for something like that at this time. You can always [self-host your runner](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/hosting-your-own-runners). I know it's not as simple as the hosted runners but since you don't need anything preinstalled, it should be fairly straightforward to set up.

**Comment by samuela** [comment]
This is also a pain point simply because of how heavyweight the runners are. I frequently find myself debugging jobs that failed due disk space issues. There are even folks building sorta workarounds for this: https://github.com/easimon/maximize-build-space.

Is there any way we could just get a "minimal" runner? Something with only the bare essentials?

**Comment by aep-sunlife** [comment]
> And then just build and run that from the runner

That's not workable, as Docker itself frequently encounters disk capacity issues in GitHub runners, due to the very bloat of the premade images.
