### ISSUE TITLE
Add Ubuntu 20.04 focal

### ISSUE THREAD

**Issue by KOLANICH** [actions/virtual-environments#228]
**Tool information**
- Tool name: Ubuntu 20.04 `focal`
- Add or update? Don't care.
- Desired version: 20.04
- Approximate size: large
- If this is an add request:
  - Brief description of tool: A new release of Ubuntu. The ones used are damn obsolete.
  - URL for tool's homepage: https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule

**Area for Triage**: 

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] Ubuntu 18.04 LTS

**Can this tool be installed during the build?**
Not really.

**Are you willing to submit a PR?**
No.

**Comment by kaylangan** [comment]
Thanks for the feedback! We offer LTS versions of Ubuntu and will be looking to add 20.04 when it becomes available.

**Comment by deinok** [comment]
@kaylangan Now it's ready to use

**Comment by hartwork** [comment]
> Thanks for the feedback! We offer LTS versions of Ubuntu and will be looking to add 20.04 when it becomes available.

@kaylangan could this ticket be re-opened please? Thank you!

CC @hannob

**Comment by kinnison** [comment]
I am having difficulty migrating CI to github actions for a project which needs newer GTK/glib than is available in 18.04.  Is there any indication of when 20.04 will become available in actions?

**Comment by orthodoX** [comment]
@kinnison I have the same problem 😞

**Comment by peaceiris** [comment]
Is there any roadmap about this?

I have some public GitHub Actions and want to test those on the Ubuntu 20.04 LTS. Now, the version is not available via `runs-on` so I will use the following workaround.

```yaml
jobs:
  my_job:
    container:
      image: ubuntu:20.04
```

We are looking forward to 20.04! 😄

**Comment by maxim-lobanov** [comment]
Hello everyone, we are looking at adding Ubuntu 20.04 environment but can't provide any ETA or promises for now. Will keep you posted

**Comment by maxim-lobanov** [comment]
Hello everyone!

We are happy to say that Ubuntu 20.04 is available for both GitHub Actions and Azure DevOps! 🚀 
You can switch to it using `ubuntu-20.04` label in YAML files.

We added Ubuntu 20 as a preview for now. It means that `ubuntu-latest` label is not updated and still points to Ubuntu 18.04. Also some important tools are not available on Ubuntu 20.04 yet.

The list of the tools that are not available on Ubuntu 20.04 yet (It should be available in a few weeks):
1) Docker
2) Pre-cached versions of Python, PyPy, Ruby, Node (setup-python / UsePython, setup-ruby / UseRuby tasks may not work properly due to that).

Also we have deprecated a bunch of software from Ubuntu 20.04, especially old versions of tools for which we support multiple versions. If you see that any important tool or version is missed on Ubuntu 20.04, please feel free to create the separate issue on adding it back.

Please share you feedback and let us know if any issues

**Comment by AkihiroSuda** [comment]
Docker is now officially available for Ubuntu 20.04: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/

Could you update the image?

**Comment by maxim-lobanov** [comment]
@AkihiroSuda , we can't install official docker version on images because of legal issues. On our images, we use special Moby version licensed for MS images (from https://packages.microsoft.com/config/ubuntu/20.04/). Docker for Ubuntu 20.04 is available on preview channel. We are going to add this to image soon #1002

**Comment by blake-newman** [comment]
@maxim-lobanov what is the estimated time it takes after PR is merged before the image will be available to public?

**Comment by maxim-lobanov** [comment]
New image with Docker should be available tomorrow or on Monday. We will update this issue

**Comment by miketimofeev** [comment]
The image with docker has been deployed.

**Comment by Blaok** [comment]
Somehow `ubuntu-20.04` shows up as `windows`.

![image](https://user-images.githubusercontent.com/4057569/83930241-69f0dc80-a74b-11ea-8efa-dd4e66b81b5c.png)

**Comment by maxim-lobanov** [comment]
@Blaok , I have created the separate issue for bug that you have found: https://github.com/actions/virtual-environments/issues/1050. We will escalate it to appropriate team. Thank you!

**Comment by maxim-lobanov** [comment]
Hello everyone, latest deployed image contains pre-cached versions for Ruby, Python, PyPy, and Node.JS so `setup-node`, `setup-python`, `setup-ruby` actions should work as expected.
I am going to close this issue since Ubuntu 20.04 is deployed and available for everyone! 🚀 

Feel free to create a separate issue if you see any problems with new image.
