### ISSUE TITLE
Update ghc from 8.10.2 to 8.10.3

### ISSUE THREAD

**Issue by jneira** [actions/virtual-environments#2353]
**Tool information**
- Tool name: ghc
- Tool license: current
- Add or update? update
- Desired version: 8.10.3
- Approximate size: 

**Area for Triage**: haskell

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- All

**Are you willing to submit a PR?**
Yes

I think all package managers have the version included:
* ubuntu -> hvr:ppa: https://launchpad.net/%7Ehvr/+archive/ubuntu/ghc/+sourcepub/11939945/+listing-archive-extra
* windows -> chocolatey: https://chocolatey.org/packages/ghc/8.10.3
* macos -> ghcup

**Comment by Darleev** [comment]
Hello @jneira,
Thank you for submitting the issue. 
GHC will be automatically updated after the next image rollout most likely in the first weeks of January.
I will let you know as soon as ghc is deployed.

**Comment by jneira** [comment]
thanks a lot for the quick response

**Comment by maxim-lobanov** [comment]
I think the new version should be already available via official haskell action: https://github.com/haskell/actions/tree/main/setup
It will install the new version in runtime with minor latency. As soon as image is updated, it will switch versions without latency.

**Comment by jneira** [comment]
@jneira maybe I missed something but I tested GitHub actions and all install methods failed for ghc-8.10.3: https://github.com/jneira/haskell-language-server/actions/runs/441063983

**Comment by maxim-lobanov** [comment]
@jneira , it is absolutely correct code. Could you please try to rerun it? I see your last attempt was 2 days ago but, for example, new version was added to choco just yesterday. May be it is delay with updating

**Comment by jneira** [comment]
@maxim-lobanov hi, thanks for the tip, I've reran jobs and Windows one has been succesful but the rest continue failing https://github.com/jneira/haskell-language-server/actions/runs/441063983

**Comment by maxim-lobanov** [comment]
Hm, looks like [ghcup](https://www.haskell.org/ghcup/) is not updated yet and still doesn't contain new version.
Just checked on local box:
![image](https://user-images.githubusercontent.com/16715858/103138898-f2cf6580-46e7-11eb-8bed-959db498cbb0.png)

As soon as it is updated, task will work as expected.

**Comment by jneira** [comment]
@maxim-lobanov thank you, i didnt check ghcup. For completeness, [afaics hvr:ppa is used to install ghc in the ubuntu images](https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/haskell.sh#L14), and 8.10.3 is included there, it is matter of time to get it in ubuntu too?

**Comment by maxim-lobanov** [comment]
Unfortunately, I am not familiar with process for adding versions to ghcup so can't predict when it will be updated.
Yes, image generation uses `hvr:ppa` but `actions/setup-haskell` uses ghcup to install versions in runtime AFAIK

**Comment by jneira** [comment]
A pr to add support for ghc-8.10.3 was merged a two days ago: https://gitlab.haskell.org/haskell/ghcup-hs/-/merge_requests/53
It only updated yaml files, so afaiu, only the config files would be needed to make ghcup supports the new version.

**Comment by mouse07410** [comment]
A silly question: why not make CI do `ghcup upgrade` immediately after `ghcup` (of whatever version) is installed by the script?

**Comment by maxim-lobanov** [comment]
@mouse07410  When image is just generated, it always has latest `ghcup`. But images are regenerated on weekly basis (sometimes rare because of deployment freeze) so if image was generated and deployed yesterday, and today the new version of ghcup is released, it will be outdated in CI

**Comment by jneira** [comment]
I think @mouse07410 want to ask why not upgrade ghcup in the setup-haskell action itself, to make it download the last version without waiting for the next image bump.
It makes more sense if the upgrade only fetches config files, and doesn't update the executable itself, like it seems.

**Comment by jared-w** [comment]
I froze ghcup in the setup action because it felt weird to update ghcup to a new version invisibly. But now that I see ghcup keeps the same version when updating yaml files, it does make sense to run `ghcup upgrade` inside the action, so I'll modify it to do that.

In the meantime, regardless of the version of  ghcup used, the setup action should be running `apt install ghc-8.10.3` and then `ghcup install ghc 8.10.3` (if the first failed). Which you can see is exactly what's happening in the logs. However, the action (rightly) does not run `apt update`, so if the image is slightly behind (which it is) then it won't have the newest listing of GHC when `apt-get install` runs. Then `ghcup` is a slightly older version so it is also not updated yet to have 8.10.3.

**Comment by mouse07410** [comment]
What's the point of `apt install ghc-x.y.z`?

The whole idea of using `ghcup` is that it does all of the necessary installations for you, correctly, for the platform you're running it on.

**Comment by jared-w** [comment]
Apt is used first on ubuntu because, on the runners, GHC is already installed using apt, so apt is tried first to save a download of ghc and/or ghcup if possible. I also need to know the location of the app download spots to check if the specified GHC is already available anyway (as that's the vast majority and the "no-op" happy path). So since I have 99% of the complexity there just to short circuit properly, I might as well check apt first since it's likely to be faster.

hvr's ppa also supports versions of GHC down to 7.0.1 whereas ghcup only goes to 7.10.3. Not a big deal, but keeping that working seamlessly is useful for not breaking expectations.

**Comment by mouse07410** [comment]
@jared-w I hear you. But I question the usefulness of downloading different GHC with different tools, and going back as far as GHC 7.0.1 instead of stopping at 7.10.3.

It was my understanding that in the Haskell world the preferred way of installing everything (except for Stack) is `ghcup`. Therefore, I'd recommend downloading only `ghcup`.

**Comment by jared-w** [comment]
It appears that GHC 8.10.3 has rolled out to at least several rings, and the latest version of the `haskell/actions/setup` action installs GHC 8.10.3 successfully in all cases now, so I believe this issue can be closed.

**Comment by jneira** [comment]
I can confirm hls is already using ghc-8.10.3 without any issue, many thanks!
