### ISSUE TITLE
Add Ruby 3.0 to tool-cache for Hosted images

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/virtual-environments#2357]
**Tool information**
- Tool name: Ruby
- Add or update? Add
- Desired version: 3.0.0
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Ruby
  - URL for tool's homepage: https://github.com/ruby/ruby-builder/releases/tag/toolcache and https://rubyinstaller.org/downloads
  - Provide a basic test case to validate the tool's functionality: ruby --version

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by maxim-lobanov** [comment]
It is about pre-caching Ruby 3.0 in tool-cache. As for the default (system) Ruby, we are planning to pin it to 2.7 for now because I think switching 2.7 -> 3.0 could be a breaking changes for some customers.
@eregon do you have any recommendations about default Ruby on Hosted images? How much time does it make sense to keep 2.7 before switching to 3.0? The most of the customers use tasks and won't be affected but I guess there are customers who depend on default version.

**Comment by eregon** [comment]
I wonder if there should even be a ruby by default in PATH.
If there was not, then everyone would select their version explicitly.

Ruby 3.0 has keyword arguments changes, the rest should be mostly compatible. Problematic keyword arguments usage should warn in 2.7, but these warnings are only shown with `ruby -w` or `Warning[:deprecated] = true`.
I'd recommend to change the default when 3.0.1 comes out (x.y.0 often has a few bugs due to less testing by users), or already now. In either case it can be a breaking change, but there is no way around it. Probably best to announce it early enough.

**Comment by vsafonkin** [comment]
Ruby 3.0.0 was added to cached Ruby pre-build versions on all platforms:
https://github.com/roasted-eggplant/validate-vlsafo/actions/runs/554405661

**Comment by miketimofeev** [comment]
We've finished image deployments with Ruby 3.0
