### ISSUE TITLE
Status of shipped Boost?

### ISSUE THREAD

**Issue by vadi2** [actions/virtual-environments#2425]
What is the future status of the shipped Boost in environments? It is super convenient that is is available in Ubuntu and Windows (unfortunately missing on macOS) but I also see that further updates to it have been rejected.

While there is a script to download latest boost for Windows, there don't seem to be similar ones for other platforms.

I'm wondering what path should I take for making use of Boost in the Github CI?

**Comment by AraHaan** [comment]
I would be for having an github action that can do all the needed checks to download, setup, build, and then install boost (according to what the user asks for) similar to the ``setup-dotnet`` action.

**Comment by vadi2** [comment]
There is in a way: https://github.com/marketplace/actions/run-vcpkg however it insists on building Boost, this can take 15-20min unless it's cached. Github likes to evict the cache pretty often from my experience, so you have to pay that price a bit too much for my taste - which is nice when Github itself provisions Boost.

**Comment by maxim-lobanov** [comment]
Hello @vadi2 , 
Unfortunately, we don't have plans to bake future versions of Boost into the images.
Boost is not very popular on Hosted images and rises maintenance concerns (takes much free space, supporting a few versions because of breaking changes, building from source code and etc)

Previously, we had to build it from source code and distribute through packages on https://github.com/actions/boost-versions since building from source code takes much time during image-generation.

I think the most convenient way to use newer versions of Boost right now is
- Windows: download [official pre-build binaries](https://sourceforge.net/projects/boost/files/boost-binaries/) provided by Boost team.
- Ubuntu:
  - Use apt packages: https://www.osetc.com/en/how-to-install-boost-on-ubuntu-16-04-18-04-linux.html
  - Use vcpkg + caching feature (the first build could take much time but consuming existing cache works really fast)
- macOS: Install via `brew install boost`

**Comment by vadi2** [comment]
OK, thanks for the reply. It's unfortunate since none of the solutions are as good for the first build + repeating builds as having it be shipped.
