### ISSUE TITLE
[all OSs] Java 7 will be removed from images on February, 8.

### ISSUE THREAD

**Issue by AlenaSviridenko** [actions/virtual-environments#2446]
**Breaking changes**
Java 7 will be removed from all images.

**Target date**
Image deployment will start February, 8 and will take 3-4 days.

**The motivation for the changes**
We would like to provide images with the most popular software, and based on our telemetry,  Java 7 has very small usage rate, so we are going to deprecate it as unpopular.

**Possible impact**
If your project depends on specific Java 7 features — build will be broken.

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.13
- [x] macOS 10.14
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Mitigation ways**
Please, use tasks `actions/setup-java` for GitHub Actions and `JavaToolInstaller` for Azure DevOps to install Java 7 in runtime if needed.

**Comment by dibir-magomedsaygitov** [comment]
[macOS](https://github.com/actions/virtual-environments/pull/2631), [Windows](https://github.com/actions/virtual-environments/pull/2629) and [Ubuntu](https://github.com/actions/virtual-environments/pull/2633) PR's were merged. Images without Java 7 should be available with this week's rollout.

**Comment by cbuche** [comment]
In case anyone else needs this, I had an issue with just using `actions/setup-java`.  Our whole project (android) targets/uses java 1.8.   However one of our third party libraries has java 1.7 nested inside it somewhere (I believe it's the new relic android client -- specifically the java-agent dependency they likely use inside of it).  Since `actions/setup-java` changed our JAVA_HOME environment variable as well, our version of gradle couldn't run (I couldn't find an option to disable this).

The solution I ended up using was to follow up the `actions/setup-java` call with:
```
- name: Reset JAVA_HOME
      run: echo "JAVA_HOME=${JAVA_HOME_8_X64}" >> $GITHUB_ENV
```

This kept java 7 available, but let everything else use java 8.

**Comment by miketimofeev** [comment]
The deployment completed for all OSs
