### ISSUE TITLE
Different Java version with and without sudo on macOS images

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/virtual-environments#2454]
**Description**  
`java --version` and `sudo java --version` refer different Java versions on macOS runners
See screen for details
![image](https://user-images.githubusercontent.com/16715858/104745983-be3b5080-575f-11eb-8c8f-37b3cd80efd3.png)

**Area for Triage**:  

**Question, Bug, or Feature?**:  

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Both `java --version` and `sudo java --version` should point the same version

**Actual behavior**  
- `java --version` points to Java 8
- `sudo java --version` points to Java 14

**Repro steps**  
See description

**Comment by al-cheb** [comment]
This behavior is by design for sudo:
`-E' The -E (preserve environment) option indicates to the security policy that the user wishes to preserve their existing environment variables. The security policy may return an error if the -E option is specified and the user does not have permission to preserve the environment.`

you should use flag -E to pass env variables, because JAVA_HOME is missing:
```
Mac-1610725225646:~ runner$ sudo java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)

Mac-1610725225646:~ runner$ sudo -E java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)
```

unset JAVA_HOME:
```
Mac-1610725225646:~ runner$ unset JAVA_HOME
Mac-1610725225646:~ runner$ java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)
```
