### ISSUE TITLE
Add /home/runner/.local/bin to PATH on Linux

### ISSUE THREAD

**Issue by abitrolly** [actions/virtual-environments#2455]
`/home/runner/.local/bin` is not in PATH on Linux, which makes Python CLI tools installed with `pip install <command>` unavailable. Adding this dir to PATH will make `pip` in build environment behave similar to how things work in `virtualenv` where installed commands are immediately available.

See also https://github.com/actions/setup-python/issues/99

- Add
- If this is an add request:
  - Provide a basic test case to validate the tool's functionality:
```
pip install coverage
coverage
echo $?
```

**Area for Triage**:
Python Scripting and command line Feature

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Are you willing to submit a PR?**
Yes, if you show me where.

**Comment by Darleev** [comment]
Hello @abitrolly,
We've added the required changes to our templates. PATH will be updated after the next image rollout.
I will keep you informed.

**Comment by Darleev** [comment]
Hello @abitrolly,
We've added the required changes to the code, but they don't work at this time, due to some unexpected behavior for agent machines. We will investigate the issue with this path internally. As soon as a fix is applied, the path will be added to the agents.
Currently, it is possible to set environment variables using this approachs:
[Github Actions](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files)
[Azure DevOps](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md)

In case of any questions, feel free to contact us.
