### ISSUE TITLE
Ubuntu-latest Job fails after 1 h and doesn't display logs.

### ISSUE THREAD

**Issue by adamhass** [actions/virtual-environments#2475]
**Description**  
I work on Kompact, an open-source Actor-framework in Rust. We recently migrated to Github Actions from Travis. We are trying to get a Code-coverage report produced as part of the CI pipeline, so this is not a job which was running and then suddenly started failing. 

The Code-coverage job fails after 1 hour. No logs are saved for/viewable for the step which it fails on. You can view four similar failing jobs [here](https://github.com/kompics/kompact/actions?query=workflow%3ACodecov) and see what I'm talking about. We have tried to ensure that it's not failing due to faulty configuration/scripting/set-up on our end.

I found a similar issue (#1491) I suspect it is the same problem. 

**Area for Triage**:  Rust

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [✅] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Expecting the job to succeed, or, fail and display logs.

**Actual behavior**  
Failure and no log for the failing step.

**Repro steps**  
The Job config is viewable [here](https://github.com/kompics/kompact/pull/132/files#diff-512f30627f95d7fcdc76dc362d896351e9a4539994b7ab00b41979e653a6d0a9).

The tests ran during that job run for a long time. The testing includes networked integration tests, in which multiple sockets are opened and closed, for many of the test cases, and they are run multiple times against a feature-matrix. So the issue may be related to resource usage, as the related issue alludes to, but it is difficult to troubleshoot for us without access to the logs.

**Comment by miketimofeev** [comment]
Hi @adamhass!
I've checked the provided failing jobs and 2 of them actually contain some data"
1. [Use source-based code coverage Codecov #2](https://github.com/kompics/kompact/runs/1717639312?check_suite_focus=true) — a lot of `ERRO slog-async: logger dropped messages due to channel overflow` messages
https://pipelines.actions.githubusercontent.com/HIOnzKPM13Mp2mueOWpEoPDQaglt6dMP2qFrpGOn8g2OyHGIsi/_apis/pipelines/1/runs/17/signedlogcontent/3?urlExpires=2021-01-19T08%3A17%3A51.5954744Z&urlSigningMethod=HMACV1&urlSignature=yl4HUik8kFqjr6yYlr2bqUz12LO3NqMn5UNWByEJzg8%3D
2. [Use source-based code coverage Codecov #3](https://github.com/kompics/kompact/actions/runs/492081512) — pretty straightforward error `No space left on device` 
Could you please check how much space is usually used for the tests? This can be a reason for such behavior.

In the meantime, I'll try to find what's wrong with those 2 without logs.

**Comment by miketimofeev** [comment]
Managed to find backend service logs for runs without any data — the lack of logs is related to the disk space usage: `Failed to upload diagnostics System.IO.IOException: No space left on device`

**Comment by adamhass** [comment]
Thanks for the quick help. We can solve our problem with that information.
