### ISSUE TITLE
Update/Add Boost Release

### ISSUE THREAD

**Issue by rahulbansal16** [actions/virtual-environments#2507]
**Tool information**
- Tool name: Boost
- Tool license: 
- Add or update? update
- Desired version: 1.75.0
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: https://www.boost.org/
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**: C/C++

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by AlenaSviridenko** [comment]
Hi @rahulbansal16,
unfortunately, we don't have plans to support more versions of Boost on our images due to space and maintenance concerns (we build Boost by ourselves in [actions/boost-versions](https://github.com/actions/boost-versions)), and eventually, we'd like to get rid of it on our images in favor of official packages that can be installed in runtime.
I am closing this issue. Please, feel free to contact us if any help needed.

**Comment by maxim-lobanov** [comment]
For reference: https://github.com/actions/virtual-environments/issues/2425#issuecomment-759303364
