### ISSUE TITLE
Add FreeBSD runner

### ISSUE THREAD

**Issue by smorimoto** [actions/virtual-environments#2529]
Although FreeBSD is used by many teams in production, many open-source software development teams can't fully test the software on FreeBSD because it's missing in many CI services. This is something that Docker can't solve, and I believe it's definitely worth adding. (It's not completely impossible with hacks, but it's definitely not what we want to do.)

Related issues:
- https://github.com/actions/runner/issues/385
- https://github.com/actions/runner/issues/243

**Comment by AlenaSviridenko** [comment]
Hi @smorimoto,
thank you for your suggestion, but unfortunately, currently, we don't have plans to provide more images mostly due to maintenance concerns, our current focus is on stabilizing and improving images we have now. 
Please, consider setting up a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners) or using [FreeBSD-vm](https://github.com/marketplace/actions/freebsd-vm) action mentioned in one of the linked topics.

I am closing this issue. Hopefully, we can revisit this solution in the future. 
Please, feel free to contact us in case of any questions.
