### ISSUE TITLE
Add node:14-alpine and node:14 to the list of cached docker images

### ISSUE THREAD

**Issue by litan1106** [actions/virtual-environments#2560]
**Tool information**
- Tool name: Node image (pre-cached)
- Add or update? Add
- Desired version: node:14-alpine and node:14 
- Approximate size: 100mb

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**
1+ minute

**Comment by AlenaSviridenko** [comment]
Hi @litan1106,
Installation time in runtime for both images took 5 seconds in GitHub Actions. Given this short installation time and the fact that they will take ~1Gb, we'd rather not to add these containers to our runners. Unfortunately, we cannot afford it as a permanently cached images (especially for Ubuntu 18.04) due to space concerns.
![image](https://user-images.githubusercontent.com/8777209/106141331-fb044000-6180-11eb-9f47-c2448db8252d.png)

I am closing this issue. Please, feel free to create a new one if any help needed.
Thanks!
