### ISSUE TITLE
Windows x64 Image broken when attempting to use commands provided by git bash

### ISSUE THREAD

**Issue by jtpetty** [actions/virtual-environments#263]
**Describe the bug**
If an agent is attempting to run a bash script, and that script tries to run 'find', it attempts to run the Windows version of 'find' instead of that bash version of 'find'. This fails since those two commands take very different parameters. It results in the following output:

```
FIND: Parameter format not correct
```

I believe this a result of this PR #211 

This started happening on Jan 10, 2020 after 5:45p EST

I was able to add a step to add those paths back to the PATH and my pipeline works again.

**Comment by ethomson** [comment]
More reports of this issue: https://github.community/t5/GitHub-Actions/Windows-tests-worked-yesterday-broken-today/td-p/43574

**Comment by DaanDeMeyer** [comment]
As could be expected, there's already lots of scripts that depend on the unix tools being available from the PATH without running in the git bash shell so #211 is a breaking change (I wasn't really expecting it to get merged without some discussion to be honest especially since I explicitly asked for pointers on how to actually test the changes in the pull request).

The tools really should really never have been added to the PATH when running cmd or powershell in the first place but they were so now we're stuck in a mess where having them in the PATH breaks some workflows (My use case works perfectly since #211 was deployed) but removing them breaks other existing workflows.

If #211 is reverted since it's a breaking change, the documentation should be updated to clearly mention that MinGW won't work by default since it's own libstdc++ will be overriden by the one put in the PATH by the Git installation and manual intervention is required to make sure the correct libstdc++ is found first.

It might also be possible that chocolatey is simply not adding the git tools to the PATH correctly. However, I'm not sure if it's possible to fix that without adding libstdc++ to the PATH again which breaks chocolatey MinGW for everyone else.

**Comment by alepauly** [comment]
> so #211 is a breaking change (I wasn't really expecting it to get merged without some discussion to be honest especially since I explicitly asked for pointers on how to actually test the changes in the pull request).

@DaanDeMeyer yeah, that's on me for trying to multi-task and not looking carefully enough. Removing Mingw paths seemed clear enough but I didn't think it through as I should have. Lesson learned :-)

There's currently no simple way to test other than building the machine on your own but that's quite a bit of effort. We're working on adding some CI and checks within the PRs in the coming months.

**Comment by bryanmacfarlane** [comment]
This also broke our runner builds.  

I think the fix is as simple as adding a path to PATH

**Comment by alepauly** [comment]
apologies for the delay on this, the fix is in but the rollouts have been delays for multiple unrelated reasons. We're pushing to get the latest updates out there as soon as possible!

**Comment by DaanDeMeyer** [comment]
@alepauly Is it necessary to add the directories to the PATH outside of git-bash as well? It seems my pull request has been reverted which will break chocolatey MinGW builds again. Can we solve this by adding the paths only when in git bash or do the tools have to be available outside of git-bash as well?

**Comment by alepauly** [comment]
@DaanDeMeyer I'm guessing you're referring to #304? We kept the other cleanup you added (thanks) but adding the Git folder back addresses the issue of using the proper tools in the proper context. See @al-cheb's comment here: https://github.com/actions/virtual-environments/pull/304#issuecomment-577259228
Do you think that will still break those builds?

**Comment by DaanDeMeyer** [comment]
My bad, I must have been looking at an old version of the file. #304 seems like the perfect solution that allows both git-bash and MinGW builds to work.

**Comment by al-cheb** [comment]
Hello, @jtpetty
Could you check that the issue's been fixed?

**Comment by jtpetty** [comment]
@al-cheb - It does appear to have been resolved. Thanks!

**Comment by ethomson** [comment]
Thanks for the helpful report and the information on this issue.

**Comment by regevbr** [comment]
Hi,
There is still issues with git core commands.
Need to add `C:\Program Files\Git\mingw64\libexec\git-core` to the path as well.
For example git submodule command fails without it in the path
