### ISSUE TITLE
Add jdk 14

### ISSUE THREAD

**Issue by Omer3160** [actions/virtual-environments#2653]
**Tool information**
- Tool name: jdk 14
- Tool license: no need for license 
- Add or update? Add
- Desired version: 14
- Approximate size:
- If this is an add request: add
  - Brief description of tool: java but in the advenced version - java 14.02 preview 
  - URL for tool's homepage: https://www.oracle.com/java/technologies/javase/jdk14-archive-downloads.html
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature 

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**
Not a lot of time, just to add the language zip

**Are you willing to submit a PR?**
Yes

**Comment by AlenaSviridenko** [comment]
Hi @Omer3160 ,
please, fulfill the issue with the details requested in the issue template, so we could review your suggestion.
Thanks!

**Comment by Omer3160** [comment]
Hi @AlenaSviridenko , 
I updated the issue with what I know about it, if there is anything else I can do, let me know

**Comment by AlenaSviridenko** [comment]
Thank you for updating the description.
Some time ago we started sticking to the policy to provide only LTS Java versions on the images due to maintenance concerns, so please, consider using [actions/setup-java](https://github.com/actions/setup-java) to pre-install any other versions. It supports preinstallation of EA versions if needed, and installation takes ~12 sec on Windows 2016.

I am closing this issue, please, feel free to create a new one in case of other questions.
Thanks!
