### ISSUE TITLE
[OSX CURL BROKEN SSL]: SSL Error on macOS latest

### ISSUE THREAD

**Issue by Milerius** [actions/virtual-environments#2804]
**Description**  

```
==> Downloading https://homebrew.bintray.com/bottles/automake-1.16.3.catalina.bottle.tar.gz
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "automake"
Download failed: https://homebrew.bintray.com/bottles/automake-1.16.3.catalina.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://git.savannah.gnu.org/cgit/config.git/snapshot/config-0b5188819ba6091770064adf26360b204113317e.tar.gz
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to git.savannah.gnu.org:443 
Error: Failed to download resource "automake--config"
Download failed: https://git.savannah.gnu.org/cgit/config.git/snapshot/config-0b5188819ba6091770064adf26360b204113317e.tar.gz
Cloning into 'libwally-core'...
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
```

**Area for Triage**:  
https://github.com/KomodoPlatform/atomicDEX-Desktop/runs/1998713579?check_suite_focus=true

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] macOS latest
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Environment: macos-10.15
  Version: 20210220.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20210220.1/images/macos/macos-10.15-Readme.md

**Expected behavior**  
Working

**Actual behavior**  
Not working

**Repro steps**  
use any action that use brew

**Comment by dibir-magomedsaygitov** [comment]
Hello @Milerius. Thank you for your report. Seems like this issue was related to [SSL error](https://github.com/Homebrew/brew/issues/10739). If the same issue will appear again, simply run this command before using brew:

`export HOMEBREW_BOTTLE_DOMAIN=https://dl.bintray.com/homebrew
` 

or inline:

`HOMEBREW_BOTTLE_DOMAIN=https://dl.bintray.com/homebrew brew upgrade
`

This workaround should help to avoid [SSL error](https://github.com/Homebrew/brew/issues/10739).

**Comment by Milerius** [comment]
Thanks a lot
