### ISSUE TITLE
Experience large delays with MacOS builds

### ISSUE THREAD

**Issue by newhoggy** [actions/virtual-environments#2841]
**Description**  
We're experience very large delays with MacOS builds as compared to builds for Linux and Windows

**Area for Triage**:  

**Question, Bug, or Feature?**:  
For all of today, MacOS builds are way behind and are being queued up.

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
Not sure how to get an image version, but the problem is happening here with many builds queuing for 7 hours or more:

https://github.com/input-output-hk/cardano-node/actions

**Expected behavior**  
MacOS builds should be roughly as fast as all the other builds.

**Actual behavior**  
MacOS builds are slow and queue up.

**Repro steps**  
N/A

**Comment by al-cheb** [comment]
Hello, @newhoggy
Does the issue still reproduce for you?

**Comment by newhoggy** [comment]
Yes it is.  Please see the list of jobs here: https://github.com/input-output-hk/cardano-node/actions

There are a number of them where MacOS builds are behind.

**Comment by al-cheb** [comment]
> Yes it is. Please see the list of jobs here: https://github.com/input-output-hk/cardano-node/actions
> 
> There are a number of them where MacOS builds are behind.

It's by design. https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration

GitHub plan | Total concurrent jobs | Maximum concurrent macOS jobs
-- | -- | --
Free | 20 | 5
Pro | 40 | 5
Team | 60 | 5
Enterprise | 180 | 50

As I can see you have already run 5 concurrent macOS jobs.

https://github.com/input-output-hk/cardano-node/runs/2129734134?check_suite_focus=true - 1 jobs
![image](https://user-images.githubusercontent.com/47745270/111477150-e1728400-873f-11eb-8646-08d4dc3f9c53.png)
https://github.com/input-output-hk/cardano-node/runs/2129758818?check_suite_focus=true - 2 jobs
![image](https://user-images.githubusercontent.com/47745270/111477207-f0593680-873f-11eb-9186-81273b54aaef.png)
https://github.com/input-output-hk/cardano-node/runs/2129854875?check_suite_focus=true - 2 jobs
![image](https://user-images.githubusercontent.com/47745270/111477255-fbac6200-873f-11eb-9a4b-f14f2f6293bb.png)
