### ISSUE TITLE
add archlinux-latest virtual environment

### ISSUE THREAD

**Issue by soloturn** [actions/virtual-environments#2845]
**Tool information**
- Tool name: archlinux
- Tool license: GNU GPL and other
- Add or update? Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of tool: rolling release linux distribution 
  - URL for tool's homepage: https://archlinux.org 
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Feature**:

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

it can be run as image on e.g. ubuntu. but #2658, #2698 show it can lead to long outages.

**Tool installation time in runtime**

its a docker image, so, short.

**Are you willing to submit a PR?**

if you tell how and where, sure.

**Comment by maxim-lobanov** [comment]
@soloturn , thank you for your proposal.
I think pre-caching docker image wouldn't help in cases that you mentioned. The problem in those cases is that docker image was updated and started to require new library that is not distributed by docker but requires to be on host machine. So the fix for that issue was updating docker to latest version or freezing previous version of docker image.

Even if previous version is cached on local machine, your build most likely will consume `latest` tag and will download image with breaking change in runtime.

Considering the fact that image size is pretty small and it can be easily installed in runtime - we wouldn't like to pre-cache it to the images.
