### ISSUE TITLE
Selenium Test not running, Chrome=88, ChromeDriver=89

### ISSUE THREAD

**Issue by yesenin** [actions/virtual-environments#2850]
**Description**  
Selenium test fail when run on Windows Server 2019 image

**Area for Triage**:  
Win Server 2019

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
2.183.1

**Expected behavior**  
Chrome and ChromeDriver have the same version

**Actual behavior**  
ChromeDriver = 89, Chrome = 88
```
TearDown : System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 89
Current browser version is 88.0.4324.182 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe (SessionNotCreated)
```

**Comment by maxim-lobanov** [comment]
@yesenin, Hello!
Hosted images contain Chrome 88.x and ChromeDriver 88.x for now. See details in documentation: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#browsers-and-webdrivers

Looks like ChromeDriver 89 is installed during your build in runtime somehow (probably by test framework?) because we don't have such version on image.

**Comment by yesenin** [comment]
Ok, seems problem in a third-party wrapper for Selenium. Will dive into that.
Sorry for inconvenience and thank you.
