### ISSUE TITLE
Provide a Consistent Java Version Offering Above Java 11

### ISSUE THREAD

**Issue by alzimmermsft** [actions/virtual-environments#2905]
**Tool information**
- Tool name: Java Development Kit
- Tool license: No new licenses (I believe)
- Add or update? Add/Update
- Desired version: TBD
- Approximate size: A few 100MBs

Currently, the pre-installed Java versions for agents aren't consistent. This is the current breakdown:

| Agent OS | Java Versions |
| ----------- | -------------- |
| Windows 2019 | 8, 11, 13 |
| Windows 2016 | 8, 11, 13 |
| Ubuntu 20.04 | 8, 11 |
| Ubuntu 18.04 | 8, 11, 12 |
| Ubuntu 16.04 | 8, 11, 12 |
| MacOs 10.14 | 8, 11, 12, 13, 14 |
| MacOs 10.15 | 8, 11, 12, 13, 14 |
| MacOs 11 | 8, 11 |

If I have a workload which requires above Java 11 there isn't a guarantee that the agent will have it pre-installed, requiring additional configuration to ensure I have a stable baseline. What I'm requesting is a consistent offering across OSes for maximum Java version, either aligned with the most recent release (Java 15 currently) or a yearly update after an LTS (which would have been Java 13 then Java 15 given the 6 month release cycle).

**Area for Triage**:
Java

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
I believe so, but I haven't done so myself

**Tool installation time in runtime**
< 5 minutes

**Are you willing to submit a PR?**
Yes

**Comment by maxim-lobanov** [comment]
Hello @alzimmermsft , we don't pre-installed non-LTS versions of Java on Hosted images. Currently, some non-LTS versions are already installed and we can't remove them due to breaking changes but for future - we are following LTS approach.

The recommended approach is using official tasks to set up Java in runtime (it is pretty quick and takes just a couple of seconds. it also guarantee that you won't be broken in future when some version is deprecated from image):
1) [setup-java](https://github.com/actions/setup-java) (GitHub Actions)
2) [Java Tool Installer task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops) (Azure DevOps)

Related thread: https://github.com/actions/virtual-environments/pull/946#issuecomment-636096092

**Comment by alzimmermsft** [comment]
Thanks for the quick reply @maxim-lobanov.  I'll go with the recommended approaches you listed.

Just for clarification, later this year when Java 17 is released that will be included in the agents?

**Comment by maxim-lobanov** [comment]
Yes, since Java 17 will be LTS, it will be included to agents

**Comment by maxim-lobanov** [comment]
Anyway, I suggest using task even for pre-installed versions. This way task will switch Java immediately for you without latency
