### ISSUE TITLE
macOS 11.0 build "This check failed" with no log or further info of any kind

### ISSUE THREAD

**Issue by aryairani** [actions/virtual-environments#2920]
**Area for Triage**:  
Apple

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] macOS 11.0

**Image version**
"Set up job" is not present.

**Expected behavior**  
A normal execution

**Actual behavior**  
No execution and no explanation

**Repro steps**  
Repo: https://github.com/unisonweb/unison/runs/2103890386

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/538571/111052178-d6111700-8426-11eb-871e-723889b74cc5.png">

If it's just a matter of whitelisting our organization, that would be much appreciated, thanks!

**Comment by Darleev** [comment]
Hello @aryairani,
Most probably you just need to change your workflow and set the macOS version like in the example below:

`runs-on: macos-11.0` 

instead of 

`runs-on: macos-11.10` 

After that, it should work as expected. By default, we use the latest updates for macOS, and it is not required to set minor version additionaly.
In case of any questions, do not hesitate to contact us.

**Comment by aryairani** [comment]
@Darleev That's embarrassing. Thanks for your help!

**Comment by aryairani** [comment]
(Suggestion: maybe a better error message, though?)
