### ISSUE TITLE
Ubuntu Latest Version: 20210309.1 cannot find Release file

### ISSUE THREAD

**Issue by stevepiercy** [actions/virtual-environments#2938]
**Description**  
A new error message started appearing today in repos under the Pylons organization.

From:

https://github.com/Pylons/deformdemo/runs/2114011815?check_suite_focus=true#step:5:60

```
E: The repository 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  Release' no longer has a Release file.
```

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Version: 20210309.1

**Comment by jackgerrits** [comment]
I am hitting this also hitting this here: https://github.com/VowpalWabbit/vowpal_wabbit/runs/2113958668
```
Current runner version: '2.277.1'
Operating System
  Ubuntu
  20.04.2
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210309.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210309.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F
```

**Comment by sirosen** [comment]
To share a workaround while we wait for a fix, here's what I'm doing:

```
sudo rm /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
sudo apt-get update -y
```

Looks like this is how GitHub installs podman onto the VMs:
https://github.com/actions/virtual-environments/blob/1ef3339658fcf902799dfe6c55a8b75d359c19ae/images/linux/scripts/installers/containers.sh

So it's unlikely that most people doing builds need to update these packages. I don't know whether or not it's a good idea for the VMs to still have these sources in place after the machine is built? On the one hand, it makes the VM more internally consistent (because we can see where the installed packages came from). On the other hand, it exposes users to potential upstream breakage. Maybe a the VM build should run a `sed -i 's/^/#/'` on this, so an ordinary user doing an `apt update` can't be broken by this.

**Comment by al-cheb** [comment]
Hello, @stevepiercy 
Release file was updated in the repo and I unable to reproduce the issue:
![image](https://user-images.githubusercontent.com/47745270/111186830-7486af00-85c4-11eb-9939-a6ae280360de.png)
![image](https://user-images.githubusercontent.com/47745270/111186907-8700e880-85c4-11eb-8338-29af97e74894.png)

**Comment by al-cheb** [comment]
Close as duplicate https://github.com/actions/virtual-environments/issues/2919.
