### ISSUE TITLE
Microsoft Hosted agents - Linux ARM Virtual environments

### ISSUE THREAD

**Issue by jonmikeli** [actions/virtual-environments#2986]
**Tool information**
- Tool name: Microsoft Hosted agents - Virtual Environment
- Add or update? Linux ARM 64
- If this is an add request:
  - Brief description of tool: IoT Edge development deeply needs this. We often need to build modules for different platforms.

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by AlenaSviridenko** [comment]
Hi @jonmikeli, 
unfortunately, we are unable to add Linux ARM 64 images due to 2 reasons:
1. We host our images in Azure, and it doesn't support ARM 64 architecture
2. Currently, we don't have plans to add more images now due to maintenance and possible segmentation concerns. Our current focus is on stabilizing and improving existing images. Please, consider using [self-hosted runners ](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) for configurations that are not supported in GitHub-hosted runners.

Anyway, thank you for your suggestion, it will help us to understand image popularity if we will revisit this decision in the future.

I am closing this issue. Please, feel free to create a new one in case of any questions.
