### ISSUE TITLE
docker app command is unavailable inside ubuntu 20.04

### ISSUE THREAD

**Issue by friedow** [actions/virtual-environments#3043]
**Description**  
Even after enabling experimental docker features inside the virtual environment, the `docker app` command stays unavailable. [The docker docs regarding `docker app`](https://docs.docker.com/app/working-with-app/) state that the command requires experimental features to be enabled and a docker version of `19.03` or higher.

**Area for Triage**:  
Docker

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210315.1

**Expected behavior**  
After enabling docker experimental features, the `docker app` command should be available.

**Actual behavior**  
After enabling docker experimental features, the `docker app` command stays unavailable.

**Repro steps**  
Here is a minimal github action to reproduce the issue: https://github.com/dot-base/dot-base/blob/feature/docker-app/.github/workflows/ci.yml. It will enable docker experimental features inside the virtuel environment and execute a docker app command afterwards.

**Comment by miketimofeev** [comment]
Hi @friedow!
I'll take a look at what goes wrong and get back with the results shortly

**Comment by Darleev** [comment]
Hello @friedow,
Did you try to enable this feature locally? I tried to do this on Ubuntu18, Ubuntu20 machines, but with no luck. According to `docker version` command, all experimental features are enabled for CLI and Server but the command still not available for use. Also, I see a lack of documentation in official docker documentation, which does not shed light on this.
Could you please provide steps to enable the feature locally?
We are looking forward to your reply.

**Comment by Darleev** [comment]
Finally, I've found how to enable the feature:
1) It is possible to auto-enable the feature in Docker desktop, just by setting up the latest updates and enable experimental mode in the configuration. It's a pretty easy way to achieve a result.
2) The second part is about docker which was installed using apt/brew options, the experimental feature is not enough for such cases, and we need to install `docker app` as additional plugin for docker.
So, in order to enable the feature for your GitHub actions workflow, it is required to add the following commands:

```
export OSTYPE="$(uname | tr A-Z a-z)"
curl -fsSL --output "/tmp/docker-app-${OSTYPE}.tar.gz" "https://github.com/docker/app/releases/download/v0.8.0/docker-app-${OSTYPE}.tar.gz"
tar xf "/tmp/docker-app-${OSTYPE}.tar.gz" -C /tmp/
mkdir -p ~/.docker/cli-plugins && cp "/tmp/docker-app-plugin-${OSTYPE}" ~/.docker/cli-plugins/docker-app
```

For more information please refer[ the link](https://github.com/docker/app#linux-or-macos) .

In case of any questions, feel free to contact us.

**Comment by friedow** [comment]
I've just tested this and had a github action build my docker app successfully 🙌! Thanks so much for investigating and solving this.

Time to polish these github actions 😄💪.
