### ISSUE TITLE
Ubuntu 16.04 LTS Policy

### ISSUE THREAD

**Issue by hutson** [actions/virtual-environments#3082]
Ubuntu 16.04 LTS reaches end-of-life this month, April 2021.

Does GitHub use a base image that comes with a Extended Security Maintenance contract with Canonical, thereby extending security patches until 2024?

**Comment by AlenaSviridenko** [comment]
Hi @hutson,
GitHub doesn't have such a contract, so we started preparing a plan for Ubuntu 16.04 retirement. Thanks for raising up this question.

**Comment by BrianMouncer** [comment]
Please tell us how long the Ubuntu 16.04 Microsoft hosted build agents will be maintained and hosted?
I am hoping for at least the next year.

**Comment by maxim-lobanov** [comment]
Hello @BrianMouncer , considering the fact that 16.04 LTS reaches end-of-life in April 2021 and we don't have Extended Security Maintenance contract, we won't be able to provide Ubuntu 16.04 in future due to security concenrs. Also the number of customers who uses Ubuntu 16.04 is very low.

We will come with official plan for Ubuntu 16.04 retirement and provide ETA in a few weeks.

**Comment by maxim-lobanov** [comment]
Ubuntu 16.04 will be deprecated on September 20, 2021.
Related items:
- https://github.com/actions/virtual-environments/issues/3287
- [GitHub Blog](https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/)
