### ISSUE TITLE
Update/Add some mechanism to make iOS Simulator faster

### ISSUE THREAD

**Issue by igorgiumellizup** [actions/virtual-environments#3239]
Hi,

My Appium iOS tests on GitHub Actions are very slow. I know that the simulator runs on software mode** and it is slower, but in some cases, like using deep links (URL Scheme) to improve tests speed, the tests simply won't complete and the whole job times out. The same test takes 9min on a macbook pro. Is there a way to use the simulator or a setting that might help? This is the workflow that we use for the tests:

https://github.com/ZupIT/beagle/blob/master/.github/workflows/automated_tests_appium_ios.yml

** The simulator prints this message before the tests:

> Unable to create basic Accelerated OpenGL renderer.
> Core Image is now using the software OpenGL renderer. This will be slow.

**Comment by dsame** [comment]
Can you please confirm the same tests have better performance on the local machines?

**Comment by igorgiumellizup** [comment]
> Can you please confirm the same tests have better performance on the local machines?

They have because on my local machine (Macbook Pro 2019 / i7 / 16gb ram / ssd) the Simulator runs on gpu mode and it doesn't print the open gl warning before the tests.

**Comment by AlenaSviridenko** [comment]
Hi, @igorgiumellizup,
unfortunately, our macOS runner don't support accelerated OpenGL renderer due to virtualization. And our hardware specification can be found in the official docs ["Supported runners and hardware resources"
](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). For better performance, you can consider using a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners).
I am going to close this issue, please, let me know if you have any concerns or questions. Thanks.
