### ISSUE TITLE
Update/Add cargo-deny

### ISSUE THREAD

**Issue by thedataking** [actions/virtual-environments#3256]
**Tool information**
- Tool name: cargo-deny
- Tool license: MIT OR Apache-2.0
- Add or update? Add
- Desired version: latest
- Approximate size: ~10M
- If this is an add request:
  - Brief description of tool: similar to existing Rust tool cargo-audit but with the ability to enforce licensing rules
  - URL for tool's homepage: https://crates.io/crates/cargo-deny
  - Provide a basic test case to validate the tool's functionality: `cargo deny check`

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature.

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
`cargo install cargo-deny`

**Tool installation time in runtime**
downloading and compiling the tool during a build takes about 10 wall clock minutes on windows-latest.

**Are you willing to submit a PR?**
sure!

**Comment by AlenaSviridenko** [comment]
Hi @thedataking,
given the tool popularity and its installation time, we'd rather not to add it to the images due to maintenance concerns. Please, consider using [actions/cargo-deny](https://github.com/marketplace/actions/cargo-deny) as it seems to be pretty popular and flexible. Using actions is a recommended way to interact with images.
I am closing this issue. Please, feel free to reach out to us if you have any questions. Thank you.

**Comment by thedataking** [comment]
@AlenaSviridenko thanks for the quick reply.  Using actions/cargo-deny is not an option here as it only supports Linux.  I don't see any indications that support for Windows is forthcoming on the actions/cargo-deny repo but it sounds like something worth exploring given the maintenance concerns you have.
