### ISSUE TITLE
Include libavformat-dev in the list of packages

### ISSUE THREAD

**Issue by sr229** [actions/virtual-environments#3306]
**Description**  

Some of our headless tests requires libavformat-dev installed since they're part of our test suite. It should be included on all Linux builds since I expect there's projects relying on this for testing.

**Area for Triage**:  

Testing and code coverage

**Question, Bug, or Feature?**:  

Feature

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Ubuntu-20.04 (ubuntu-latest)

**Comment by miketimofeev** [comment]
Ubuntu20:
Installation time — 38s
Installation size — 157Mb

**Comment by AlenaSviridenko** [comment]
Hi @sr229,
due to maintenance concerns, package popularity and installation time in runtime, we'd rather not to add this package to the image. Also, based on our experience with similar packages - they often bring some conflicts with other packages, and we are trying to avoid that.
I am closing this issue. Please, feel free to contact us for any support. Thanks.
