### ISSUE TITLE
Newer versions of Boost are needed

### ISSUE THREAD

**Issue by stcmz** [actions/virtual-environments#3383]
**Description**  
The boost-vesions action is out of date and newer versions are not added.

According to *We are trying to prepare packages for new versions of Boost as soon as they are released. Please open an issue in virtual-environments repository if any versions are missing.* at https://github.com/actions/boost-versions I am filing this issue.

**Area for Triage**:  
C/C++

**Question, Bug, or Feature?**:  
Feature

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**

Version independent

**Expected behavior**  
Add prebuilt boost libraries as they release

**Actual behavior**  
No Boost libs were added in almost a year. Newer versions including 1.74, 1.75, 1.76 should be added.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Open https://github.com/actions/boost-versions/blob/main/versions-manifest.json to see the current added versions in the repository
2. Open https://www.boost.org/users/history/ to see all official boost versions.

**Comment by AlenaSviridenko** [comment]
Hi @stcmz,
we supported this boost-versions repo until we had Boost pre-installed on our images. Unfortunately, we are not providing it anymore due to the reasons described in the https://github.com/actions/virtual-environments/issues/2425#issuecomment-759303364, so we wouldn't like to maintain this repo anymore. 
 
Sorry for inconveniences, I will update repo's README and archive it to avoid such confusions.
I am closing this issue. Please, feel free to reach out to us in case of any questions.
