### ISSUE TITLE
Update/Add libc++

### ISSUE THREAD

**Issue by seanmiddleditch** [actions/virtual-environments#3494]
**Tool information**
- Tool name: libc++
- Tool license: same as LLVM/Clang
- Add or update? update
- Desired version: 12, matching all installed llvm/clang versions
- Approximate size: 
- If this is an add request:
  - Brief description of tool: LLVM project's C++ standard library implementation
  - URL for tool's homepage: https://libcxx.llvm.org/
  - Provide a basic test case to validate the tool's functionality: Compile any C++ project on clang++-12 using `-stdlib=libc++`

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:
"Feature"

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
in `clang.sh` add:
```sh
apt-get install libc++-dev libc++abi-dev
```

**Tool installation time in runtime**

**Are you willing to submit a PR?**
Yes, if there's interest

**Comment by seanmiddleditch** [comment]
Extra notes:

Stock Ubuntu 20.04 ships with libc++-10, which is installed. The virtual environments additionally add clang-11 and clang-12 using the LLVM project's `llvm.sh` helper script. This script does not install libc++ itself, however, so it must be installed explicitly.

Without this, c++20 code cannot test compilation with libc++'s latest features and implementations, which hampers the ability to use CI for portability and conformance testing. C++ code is instead required to compile with the out-of-date libc++-10 or the latest libstdc++ (GNU's library implementation).

The setup for the virtual images installs packages from apt.llvm.org, but doesn't leave the package source enabled in the final image. This means that we can't just easily run `apt-get install libc++-dev libc++abi-dev` ourselves without reconfiguring the llvm apt repositories and re-updating our local apt caches, which is wasteful for CI jobs of course.

**Comment by catthehacker** [comment]
Please see #3479

**Comment by dsame** [comment]
@seanmiddleditch 
Unfortunately libc++*-dev packages are not designed to co-exist on the same image and it is a bit risky to have them pre-installed. 

Particularly every `apt-get install libc++-*-dev libc++abi-*-dev` overwrites links in `/usr/lib/x86_64-linux-gnu/` and files in `/usr/share/lintian/overrides/`

In theory we can backup and restore the links but having the install time of `sudo apt-get install -y libc++*-dev libc++abi-*-dev` below 20sec makes the links manipulations during image generation and, probably, during workflow runtime overkill.

As a result i suggest:
1. to do not clean up `deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main` from apt/sources.list
2. add canary test to make sure we have to use libc++-12 and build c++ 14 code against it
3. probably update docs

all the above relates to ubuntu-20.04 only because we do not have clang-12 installed on the older images

The build to illustrate 
https://github.com/dsame/actions-demo/runs/2734231079?check_suite_focus=true

**Comment by chandlerc** [comment]
FWIW, I like the suggestion of just keeping the relevant apt sources so that workflows can install the versions as needed. Seems cleaner than my PR, happy to abandon mine in favor of #3523

**Comment by dsame** [comment]
In the next rollout the documentation will include a link to apt repo to install libc++ in the pipeline

**Comment by adsharma** [comment]
> Stock Ubuntu 20.04 ships with libc++-10, which is installed.

It seems unusable with:

```
clang++ -std=c++14 -stdlib=libc++
```

Unable to find basic header files.

https://github.com/adsharma/py2many/pull/324/checks?check_run_id=2890706393

I've tried installing matching libstdc++ etc to see if the problem goes away. But it didn't help. Something changed mid-May that broke this.

Ubuntu 18.04 works ok.

Details: https://github.com/adsharma/py2many/issues/240

**Comment by miketimofeev** [comment]
The readme was updated.
@seanmiddleditch I'm going to close the issue, please feel free to contact us if you have any concerns.
Thank you!

**Comment by dsame** [comment]
The apt source for LLVM components added to Sofrware Report. This apt source should be used to install requires version of libc++. It is impossible to preinstall non-default versions because they are not designed to co-exist on the same host
