### ISSUE TITLE
User suggestion to document supported CPU instructions

### ISSUE THREAD

**Issue by rsese** [actions/virtual-environments#3520]
**Description**  

:wave:!  Kinda related to https://github.com/actions/virtual-environments/issues/3389, a user wrote-in to Support and mentioned that a couple of CPU instructions (`adcx` and `lzcnt`) seemed to intermittently not be available across runs.  It basically seemed to be a similar issue to https://github.com/actions/virtual-environments/issues/3389 where it was mentioned that agents aren't guaranteed to support certain instructions?

Not really sure what the scope would be or if the information is available elsewhere, but just sharing the suggestion from the user that it could be useful to have this type of information documented somewhere so people can know what CPU instructions they can depend on and what things they might need to manually check for?

Anyways just passing along the feedback and this repo seemed like a potential place for this documentation, if y'all think it could be useful to document but not in this repo (e.g. https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) let me know or feel free to close if it's not something you think can be easily documented :v:

**Area for Triage**:  
n/a

**Question, Bug, or Feature?**:  
Question/documentation request

**Comment by miketimofeev** [comment]
Hi @rsese!
Unfortunately, the underlying hardware is subject to change even without our awareness so that we can't guarantee anything related to the available CPU instructions.
If a user needs any specific CPU instruction it's better to rely on a self-hosted runner for that.
I hope that all explains why we wouldn't like to add such information in the docs. I'm going to close the issue.
Please feel free to contact us if you have any questions.
Thank you!

**Comment by rsese** [comment]
np that makes sense thank you @miketimofeev :bow:!
