### ISSUE TITLE
Add `yq`

### ISSUE THREAD

**Issue by Yann-J** [actions/virtual-environments#3645]
**Tool information**
- Tool name: `yq`
- Tool license: MIT
- Add or update? Add
- Desired version: 4.x
- Approximate size: ~6Mb
- If this is an add request:
  - Brief description of tool: `yq` is the YAML equivalent to `jq` and provides convenient YAML query and edits by command line
  - URL for tool's homepage: https://github.com/mikefarah/yq
  - Provide a basic test case to validate the tool's functionality: 

```
[ "$(yq -n eval '.somekey = "somevalue"')" = "somekey: somevalue" ];
```

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

```
brew install yq
```

**Tool installation time in runtime**

~10s?

**Are you willing to submit a PR?**

Yes

**Comment by AlenaSviridenko** [comment]
Hi @Yann-J,
there is a popular action for setting up `yq` https://github.com/marketplace/actions/setup-yq, have you tried this? Using actions is the preferable way to interact with images https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#using-preinstalled-software.

**Comment by Yann-J** [comment]
Yes, it's true, but actions are not available in Azure Devops (I think), which is what we use... Right now we install it at runtime, i.e. for all of our builds, which works OK but since this is a popular and useful tool I think it makes sense to have it as part of the base image...

**Comment by Yann-J** [comment]
I gave a shot at a PR for it...

**Comment by catthehacker** [comment]
I would recommend installing it via Homebrew (`brew install yq`) since it's already available on ADO and GHA (if you install it at runtime) or install it via toolset
https://github.com/actions/virtual-environments/blob/405a368b22cbac48f31ce7b35f415369d31a27b1/images/linux/toolsets/toolset-2004.json#L199-L201
https://github.com/actions/virtual-environments/blob/405a368b22cbac48f31ce7b35f415369d31a27b1/images/linux/toolsets/toolset-1804.json#L199-L201
https://github.com/actions/virtual-environments/blob/405a368b22cbac48f31ce7b35f415369d31a27b1/images/linux/toolsets/toolset-1604.json#L206-L208

**Comment by AlenaSviridenko** [comment]
We are not using brew during Ubuntu image generation as it brings some issues, and we still wouldn't like to pre-install this tool on the image, due to easy and fast installation in runtime and maintenance concerns. I'd suggest use officially recommended installation way in runtime: via Homebrew or via [targz](https://github.com/mikefarah/yq#compressed-via-targz)

**Comment by Yann-J** [comment]
OK that's really up to you of course... I understand the desire to keep the images lean - although having really great base images with nearly everything pre-installed is something we really love about Azure Devops.

With Kubernetes and all the cloud-native solutions around, nearly all heavily YAML-based, I feel very strongly that having a YAML manipulation tool out of the box makes a lot of sense just like it made sense to have `jq` and `yamllint`...

**Comment by AlenaSviridenko** [comment]
@Yann-J, your arguments make sense to me. I have left a comment in the PR, feel free to update the code, and we will accept your contribution. Thanks!

**Comment by AlenaSviridenko** [comment]
Hi,
related PR was merged, and the tool will be available with the next deployment next week.
Thanks.

**Comment by miketimofeev** [comment]
@Yann-J thank you for your contribution! Images with yq were deployed, however, yq binary will be placed in the /usr/bin instead of /usr/local/bin starting from next week's images. https://github.com/actions/virtual-environments/pull/3768
I'm going to close the issue. Please feel free to contact us if you have any conerns.
