### ISSUE TITLE
Add Windows Insider SDK (22000)

### ISSUE THREAD

**Issue by sylveon** [actions/virtual-environments#3696]
### Tool name

Windows Insider SDK

### Tool license

Custom license

### Add or update?

- [X] Add
- [ ] Update

### Desired version

10.0.22000.51

### Brief description of tool

The latest Insider build of the Windows SDK, which contains important fixes for XAML codegen that are required for my project to build.

### URL for tool's homepage

https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Can this tool be installed during the build?

Yes. Running the SDK installer like for the non-Insider SDKs should work

### Tool installation time in runtime

5-10 minutes

### Are you willing to submit a PR?

Yes, if the procedure to add a Windows SDK isn't too complicated.

**Comment by AlenaSviridenko** [comment]
Hi @sylveon,
we wouldn't like to install that tool to the image due to the following reasons:
1. It is a preview, which means it can be unstable, we usually try to avoid installing preview versions of anything as we don't have expertise to handle possible issues. 
2. We need a special account to download the installation file, which means pretty complex manual maintenance.

Please, keep installing it in runtime. I am closing this issue, feel free to contact us in case of any other questions. Thanks.
