### ISSUE TITLE
docker pull takes 16 minutes on Windows runner

### ISSUE THREAD

**Issue by potatoqualitee** [actions/virtual-environments#3728]
**Describe the bug**
docker pull for the SQL Server image takes 45 seconds on Linux and 16 minutes on Windows

**To Reproduce**
Add the following pull to an action with windows-latest

```
docker pull microsoft/mssql-server-windows-developer
```

This is a decent sized image (1.x GB), but should take 1.5 minutes at most.

**Expected behavior**

The pull should take closer to 1.5 minutes, not 16 minutes as seen here 
https://github.com/potatoqualitee/sqlsuite/actions/runs/1019479639

I even tried without verifying and it still took way too long

```
docker pull microsoft/mssql-server-windows-developer --disable-content-trust
```

## Runner Version and Platform
Version of your runner?
windows-latest

Windows Server 2019

## What's not working?
Reasonable download times

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

[log.txt](https://github.com/actions/runner/files/6796452/log.txt)

Perhaps getting Docker installed on WSL 2 would solve this. That's how I use it locally. In addition, Windows containers for SQL Server are no longer being supported, so soon, we'll just have to install it from the internet instead, which takes about 5 minutes.

**Comment by miketimofeev** [comment]
Hi @potatoqualitee!
The compressed image size is 8gb, not 1.x
https://hub.docker.com/r/microsoft/mssql-server-windows-developer/tags?page=1&ordering=last_updated&name=latest
![image](https://user-images.githubusercontent.com/48208649/125661325-8759b9cc-5208-4649-8056-1fa1f690d452.png)
The average download speed is 300 Mbps, which is decent enough and it takes about 3-4 minutes to download all the layers. The rest of the time is spent on extracting the layers and it takes a long time since VM has only 2 cores and 8GB of ram. You will get the same results on a VM in Azure with similar specs. I'm afraid we can't do anything here. Please consider using a self-hosted runner for better performance.

**Comment by potatoqualitee** [comment]
oof, my information was highly outdated. sorry for not double checking. thank you for the info!
