### ISSUE TITLE
clang-tidy-12 installation failes on ubuntu-20.04

### ISSUE THREAD

**Issue by baranyaib90** [actions/virtual-environments#3827]
### Description

Dear Developers!

I can not install clang-tidy-12 package on ubuntu-20.04.
Please fix the APT issue so the proper packages will be available.
Thank you in advance!

My job failures:

1. [with apt update](https://github.com/baranyaib90/https_dns_proxy/runs/3213709457?check_suite_focus=true)
2. [without apt update](https://github.com/baranyaib90/https_dns_proxy/runs/3214069854?check_suite_focus=true)

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

Version: 20210726.1

### Is it regression?

unknown

### Expected behavior

Installation of clang-tidy-12 does not fail.

### Actual behavior

It failes.

### Repro steps

Run `sudo apt-get install -f cmake libc-ares-dev libcurl4-openssl-dev libev-dev build-essential clang-tidy-12 clang-12` on ubuntu-20.04.

**Comment by dibir-magomedsaygitov** [comment]
Hello @baranyaib90 . Thank you for your report. We will take a look.

**Comment by LeonidLapshin** [comment]
Hey, @baranyaib90 
We currently try to avoid using additional repos on Ubuntu images, you can install this one with:
```
- run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
- run: sudo apt update
- run: sudo apt-get install -f cmake libc-ares-dev libcurl4-openssl-dev libev-dev build-essential clang-tidy-12 clang-12
```
I'll close this issue but feel free to reopen it/tag me if you have any concerns.
Thanks!

**Comment by baranyaib90** [comment]
Hi @LeonidLapshin,

as you can see in the "sudo apt-get update" output (when checking my linked "with apt update" logs) the "focal-updates/universe" repository is default Ubuntu repo. So it's not additional. Please check the output I provided.
It's simple Ubuntu 20.04 package I want: https://packages.ubuntu.com/focal-updates/clang-tidy-12
So please continue the investigation.

**Comment by LeonidLapshin** [comment]
Hey, @baranyaib90 
[Clang 12 packages installed from PPA](https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/clang.sh), the installation script don't use default Ubuntu repo, because these packages [were absent](https://github.com/actions/virtual-environments/pull/3206) when we added it to the image. After the installation PPA is removed and additional dependencies can not be installed :(

So for now if you want to install some additional packages you can delete current installation from PPA and install them from default repo or add a custom PPA using [script](https://apt.llvm.org/llvm.sh) and install dependencies from PPA.

There is no actual reason for this behavior and we'll change it to installation from default repo. I'll create PR soon and will share all details in this ticket :)
Thanks!

**Comment by baranyaib90** [comment]
Hi @LeonidLapshin,
thank you very much for the investigation!
Now everything is clear for me.

**Comment by aminya** [comment]
LLVM 12.0.1 seems to be using GLIBC_2.33, which is not available on Ubuntu 20.04. You should use LLVM 12.0.0 instead.

**Comment by LeonidLapshin** [comment]
@aminya , we don't install llvm on Ubuntu during image generation process, I guess setup action is the best option to use the correct version.

**Comment by LeonidLapshin** [comment]
@aminya  I'll close the issue, but feel free to tag me here to reopen it if you have any concerns
Thanks!

**Comment by aminya** [comment]
Thank you!
