### ISSUE TITLE
Update Node.js to latest LTS

### ISSUE THREAD

**Issue by Glennmen** [actions/virtual-environments#3884]
### Tool name

Node.js

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

v16 Current LTS

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Are you willing to submit a PR?

Sure

**Comment by Glennmen** [comment]
The form didn't really provide any option to add "other" information.
Currently in the Ubuntu 20 container (and all other containers) the highest installed Node.js version is 14 but the current LTS version is 16.
Even though it is possible to install a different version it would imo be better to follow the LTS versions.

Node.js LTS timeline: https://nodejs.org/en/about/releases/

**Comment by Glennmen** [comment]
@catthehacker You are right 😅 Strange that they release it but not as LTS yet. I am used to other softwares where when they release the next LTS version it will be so on release and not 6 months after first release.

**Comment by catthehacker** [comment]
Confusing according to what and how everyone does but I think it's because they want to iron out major issues before people who like stability (e.g. corporations) switch to that version.

**Comment by miketimofeev** [comment]
Hi @Glennmen! As @catthehacker mentioned Node 16 is not LTS till October that's why we stay on 14 and don't add 16 to the pre-cached versions as well. Here is our software support policy
https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md
![image](https://user-images.githubusercontent.com/48208649/129024970-814af3bc-0436-46eb-a4be-3a3bf6e16e2a.png)

The recommended way is to use https://github.com/actions/setup-node action, which enables you to install any Nodejs version in a moment.
I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!
