### ISSUE TITLE
Please remove macos-10.14 docs

### ISSUE THREAD

**Issue by joeyparrish** [actions/virtual-environments#3895]
### Description

The docs at https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.14-Readme.md come up in a [Google search for "GitHub Actions macOS 10.14"](https://www.google.com/search?q=GitHub+Actions+macOS+10.14).  There's nothing there that says the image has been removed, so I was misled into thinking that 10.14 was still available.  And the workflow I ran with `runs-on: macos-10.14` didn't fail, so it took me a while to realize that I didn't do that test I thought I was doing.

I would suggest either removing the doc for macos-10.14 (and macos-10.13, for that matter) so that people aren't misled by search results, or perhaps adding notes to the top of the doc making it very clear that these environments are no longer available for GitHub Actions.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

N/A

### Is it regression?

No

### Repro steps

1. [search Google for "GitHub Actions macOS 10.14"](https://www.google.com/search?q=GitHub+Actions+macOS+10.14)
2. See that the docs at [images/macos/macos-10.14-Readme.md](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.14-Readme.md) come up at the top of the results
3. Note that the docs make no mention of the fact that the environment is not available for GitHub Actions

**Comment by al-cheb** [comment]
Hey, @joeyparrish 
macos-10.14 agents are available in Azure Pipelines  -https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml , that's why we don't have any plans to remove the docs from the repo. The [About GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) is already updated and doesn't include mention about macos-10.14
