### ISSUE TITLE
Update/Add Intel oneAPI HPC Toolkit

### ISSUE THREAD

**Issue by gzagaris** [actions/virtual-environments#3896]
### Tool name

Intel OneAPI HPC Toolkit Support

### Tool license

freeware (no license files required) -- based on EULA

### Add or update?

- [X] Add
- [ ] Update

### Desired version

whatever is latest

### Brief description of tool

Intel oneAPI HPC Toolkit provides free intel C/C++ and Fortran compilers as well as an implementation of MPI. 

### URL for tool's homepage

https://software.intel.com/content/www/us/en/develop/tools/oneapi/all-toolkits.html#gs.8h6xqw

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

**Comment by al-cheb** [comment]
Hello, @gzagaris 
Sorry, due to maintenance concerns, we'd rather not to add this tool to the images. Please install it on runtime - https://software.intel.com/content/www/us/en/develop/documentation/installation-guide-for-intel-oneapi-toolkits-linux/top/installation/install-using-package-managers/apt.html
