### ISSUE TITLE
Add Oracle Cloud Infrastructure CLI

### ISSUE THREAD

**Issue by Djelibeybi** [actions/virtual-environments#3909]
### Tool name

Oracle Cloud Infrastructure CLI

### Tool license

Dual licensed under Apache-2.0 and UPL-1.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Approximate size

255MB

### Brief description of tool

The Oracle Cloud Infrastructure (OCI) CLI is a small-footprint tool that can be used on its own or with the Oracle Cloud Console to complete Oracle Cloud Infrastructure tasks. 

### URL for tool's homepage

https://docs.oracle.com/en-us/iaas/Content/API/Concepts/cliconcepts.htm

### Provide a basic test case to validate the tool's functionality.

```bash
oci --version
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019

### Can this tool be installed during the build?

```bash
pipx install oci-cli
```

### Are you willing to submit a PR?

Yes

**Comment by al-cheb** [comment]
Hi, @Djelibeybi 
Our recommendation is always to use actions from the marketplace. Could you please check if the https://github.com/oracle/oci-cli action works for you?

**Comment by Djelibeybi** [comment]
@al-cheb that's not an action, it's the source repo for the CLI itself.

**Comment by al-cheb** [comment]
@Djelibeybi ,  Sorry, wrong link - https://github.com/marketplace/actions/oci-cli

**Comment by Djelibeybi** [comment]
We have a bunch of actions in development that all pretty much rely on the OCI CLI being available. I figured if it was part of the runner, that would be one less step a user needs to add to each workflow. Especially considering the other cloud CLIs that are preinstalled.

**Comment by maxim-lobanov** [comment]
Agree with @al-cheb on using the action to install the tool in runtime rather than pre-installing on images.
Installation process is pretty quick and easy so installation in runtime shouldn't be a problem. May be installation steps can be included to the new actions in development so no extra steps are required from users side.

We are trying to avoid adding any new tools to images due to maintenance concerns. Our current images are overloaded from the tool count and image size sides and difficult to maintain.

Usually, actions provide the better UX and reliability to users because they allow to specify / freeze tool version and don't depend on image updates. For example, sometimes rollout of the new image with updated version can be delayed for 2-3 weeks (customers still use previous version of tool until update is deployed). Another example is bugs in new tool versions and breaking changes in the major updates. When version 4.x is released, it will be installed instead of 3.x and all users will be affected by any breaking changes if they exist. Using action prevent both problems.

That is the reason why we recommend to use setup actions even for tools that are pre-installed on images, like [Azure CLI](https://github.com/marketplace/actions/azure-cli-action), [AWS CLI](https://github.com/marketplace/actions/setup-aws-sam-cli) and etc.

**Comment by Djelibeybi** [comment]
Fair enough. I will continue with development of an action to deploy the tool. It was worth the request, though. :)

**Comment by maxim-lobanov** [comment]
Thank you for understanding!

I am close the issue for now but feel free to ping us / reopen in future if you have any concerns / new information and think that this decision should be revisited.

Our general advice is implementing installation logic on task side even if if tool is pre-installed on Hosted images:
- if tool is installed and installed version satisfies user's input - use pre-installed version
- if tool is not installed or version doesn't satisfy - install in runtime
Based on our experience, such logic is the best approach and also work great for self-hosted runners.
