### ISSUE TITLE
Add Intel oneAPI HPC Toolkit for VisualStudio 2017

### ISSUE THREAD

**Issue by SandraHartl** [actions/virtual-environments#4112]
### Tool name

Intel oneAPI HPC Toolkit

### Tool license

freeware

### Add or update?

- [X] Add
- [ ] Update

### Desired version

whatever is latest

### Brief description of tool

Intel oneAPI HPC Toolkit provides (among others) a free Fortran compiler and when coupled with Visual Studio allows to run *.vfproj files.

### URL for tool's homepage

https://software.intel.com/content/www/us/en/develop/tools/oneapi/all-toolkits.html#hpc-kit

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by miketimofeev** [comment]
Hi @SandraHartl!
We already had such a request but for Ubuntu and macOS https://github.com/actions/virtual-environments/issues/3896. This is not something we would like to bake into the image due to maintenance concerns. Please consider installing the tool in runtime using one of the package managers https://software.intel.com/content/www/us/en/develop/documentation/installation-guide-for-intel-oneapi-toolkits-windows/top/installation/install-using-package-managers.html

**Comment by SandraHartl** [comment]
Hi,
this allows me to get the fortran compiler from oneAPI from the command line but not with VisualStudio integrated as IDE. So, to my understanding, I am not allowed to run vfproj files. Is there any other way in doing so?

**Comment by miketimofeev** [comment]
@SandraHartl could you clarify which installer should be used to integrate oneAPI with VS?

**Comment by SandraHartl** [comment]
This is what I did on my local maschine using the installation GUI of oneAPI (https://software.intel.com/content/www/us/en/develop/articles/intel-fortran-compiler-in-ms-visual-studio.html). However, I didn't find a ways doing this when using the oneAPI package loaded with pip or conda. I would be grateful for any advise here.

**Comment by miketimofeev** [comment]
@SandraHartl well, technically it's possible using the offline installer and passing the flags from this article https://software.intel.com/content/www/us/en/develop/documentation/installation-guide-for-intel-oneapi-toolkits-windows/top/installation/install-with-command-line.html
The installer is available at the following URL https://registrationcenter-download.intel.com/akdlm/irc_nas/17940/w_HPCKit_p_2021.3.0.3227_offline.exe
One note here — powershell `start-process` should be used otherwise the run step won't wait for the installer to finish

**Comment by miketimofeev** [comment]
@SandraHartl this snippet should install the compiler, but it takes quite a long time:
```
$url = "https://registrationcenter-download.intel.com/akdlm/irc_nas/17940/w_HPCKit_p_2021.3.0.3227_offline.exe"
$installer = Start-DownloadWithRetry -url $url -DownloadPath $env:Temp
$setupPath = "$env:Temp\hpckit"
Extract-7Zip -Path $installer -DestinationPath $setupPath
$bootstraper = Join-Path $setupPath "bootstrapper.exe"
$argumentList = ("--action install", "--eula accept", "--silent", "--components intel.oneapi.win.ifort-compiler")
Install-Binary -FilePath $bootstraper -ArgumentList $argumentList
```
Thanks to @shilovmaksim for the script

**Comment by miketimofeev** [comment]
I also found this repository, which can be useful for your needs https://github.com/oneapi-src/oneapi-ci

**Comment by SandraHartl** [comment]
Thanks @miketimofeev the link to the github repository you send helped me a lot. Now I have a proper ifort on my system I can use. 

To my understanding the following command should allow the coupling to VisualStudio 2017:
@call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

Unfortunatly, nothing changed (still not working) when running my vfproj file with Visual Studio.
"The application which this project type is based on was not found."
