### ISSUE TITLE
Update Ubuntu Chrome

### ISSUE THREAD

**Issue by jaredgreen-pillar** [actions/virtual-environments#417]
**Tool information**
- Tool name: Google Chrome
- Add or update? Update
- Desired version: 80.0.3987.106 (Latest stable release)
- Approximate size: 

**Area for Triage**: Packages

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?** Yes

**Are you willing to submit a PR?**
Yes, but I'm still familiarizing myself with this codebase. It seems that the latest version may be automatically deployed with a new release?

**Comment by vmapetr** [comment]
Hi @jaredgreen-pillar! Indeed, latest stable versions of Google Chrome and Chromedriver are automatically deployed with a new release. They will be available after next image rollout.

**Comment by zacharyhardin1** [comment]
Howdy @vmapetr! Glad to hear that Google Chrome and Chromedriver are deployed with new releases... Any idea when the next image rollout will occur?

**Comment by jaredgreen-pillar** [comment]
Okay thanks! We're awaiting the change as there is a bug introduced within the current GitHub Actions Chrome version that breaks many versions of Angular. (And has been fixed in the latest release)

https://github.com/angular/angular/issues/35214

**Comment by juhi123** [comment]
Hi
Is this something related, I was able to run Chromdriver using `$CHROMEWEBDRIVER `, but suddenly since tomorrow it stopped working and started giving this error
`'/usr/local/share/chrome_driver': Permission denied`

**Comment by vmapetr** [comment]
Hi @juhi123 ! Thanks for reporting the issue. Please, notice that `$CHROMEWEBDRIVER` variable now pointing to Chrome driver folder instead of Chrome driver bin, as it was previously.

Unfortunately, I was unable to reproduce this issue.

Workflow.yml
```
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Script
        run: |
          $CHROMEWEBDRIVER/chromedriver
```
Output:
```
Starting ChromeDriver 80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
```

Could you please create a new issue with repro steps?

**Comment by vmapetr** [comment]
Hi @zachariahcox! Next rollout will occur in 1-2 weeks approximately.

**Comment by juhi123** [comment]
Hi @vmapetr 
Thanks for the update, though it's so strange. Earlier only by `$CHROMEWEBDRIVER` I was able to run chromdriver, please have a look [here](https://github.com/juhi123/codeception-with-github-actions/runs/450114900?check_suite_focus=true)

**Comment by zacharyhardin1** [comment]
Thanks @vmapetr !

**Comment by miketimofeev** [comment]
@zacharyhardin1 the image with Chrome 80.0.3987.106 has been deployed. Could you check the version and close the ticket if everything is ok, please?
@juhi123 Feel free to open a new ticket if you experience any troubles with chromedriver.

**Comment by jaredgreen-pillar** [comment]
Latest image has the correct version (80.0.3987.106) and functions as expected. Thank you!

**Comment by jakehockey10** [comment]
This seems like a perpetual problem where the version updates on one end and someone has to push code changes every time this version changes?  I'm now running into this where I use the specified version listed here: https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md

And now I get these same exact errors.  It doesn't really matter what version I install first with webdriver-update, it always says I have the wrong version.  If I specify 81.0.4044.138, it says that this version of chrome driver expects version 81.  It also says I'm using 81.0.4044.69.  If I go back to what we had it at a few weeks ago, 80.0.3987.149, it says that it expects version 80 and fails with the same error.

If using the environment variable listed above is the correct approach, could someone post a code snippet where it is used in the angular cli project so that I can try it on my end?  No matter what I try, it still gives me the same error.

**Comment by miketimofeev** [comment]
Hi @jakehockey10! Could you please create a separate issue with some sample code and we'll try to help you?

**Comment by jakehockey10** [comment]
Hey @miketimofeev - I was really trying to avoid adding other testing tools to the mix and tried to do a stock angular cli setup.  But with Azure Pipelines, the only way I could find after googling the last several days is people bringing in puppeteer.  I removed puppeteer months ago because it seemed unnecessary, and the conf.js files went back to what they were when we generated them (copy and pasted to make ci versions, but saw no difference in the two).  After adding puppeteer back in, I just force the binary to point to pupeteer's chrome and the problem went away.

Bummer I couldn't get it to work without installing separate versions of things.  But I think this is probably a problem with things outside of virtual-environments.  virtual-environments is coming with pre-installed tools for our benefit, but if my Angular application can't use it, I now see it as not the responsibility of this repo.
