### ISSUE TITLE
Exit code 1 in Windows build do fail the build

### ISSUE THREAD

**Issue by freud14** [actions/virtual-environments#4197]
### Description

I'm using [black](https://github.com/psf/black) as a code formatter and uses it in my CI. When the check fails, it returns 1 as exit code. Using the Linux image, the builds fail automatically. However, it seems that when using the Windows build it does not.  

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

See the Linting task:

https://github.com/GRAAL-Research/poutyne/runs/3756699384?check_suite_focus=true

### Is it regression?

Don't know.

### Expected behavior

The build should fail.

### Actual behavior

The build succeed.

### Repro steps

Install black and run it in a Windows build on a wrongly formatted code.

**Comment by al-cheb** [comment]
Hello, @freud14 
This behavior is by design for PowerShell Core(the default shell on Windows Server , bash is default for Ubuntu, macOS).

Let's compare with bash shell, e.g.:
```
#!/bin/bash
echo "Start"
echo "abc" | grep none
echo "abc" | grep abc
echo "Done"
```
Run:
```
$ bash f.sh
Start
abc
Done
```
![image](https://user-images.githubusercontent.com/47745270/135488763-6e829f26-2c82-41c2-829a-86f12ea41ca2.png)

As you can see above, the script is run  `shell: /usr/bin/bash -e {0}` with e flag. The -e option means "if any pipeline ever ends with a non-zero ('error') exit status, terminate the script immediately"
```
$ bash -e f.sh
Start
```

PowerShell:
```
black --diff --check .
Write-Host "#1 LASTEXITCODE: $LASTEXITCODE"
pylint poutyne/
Write-Host "#2 LASTEXITCODE: $LASTEXITCODE"
pylint tests/
Write-Host "#3 LASTEXITCODE: $LASTEXITCODE"
shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
```

![image](https://user-images.githubusercontent.com/47745270/135489088-8ec55fd6-e676-4018-8bf8-a255618d08d1.png)

The result exit code is 0(pylint tests/ - 0). PowerShell doesn't have such kind of flags like bash and option `$ErrorActionPreference="stop"`  doesn't work for native commands - https://github.com/PowerShell/PowerShell/issues/3415

You should use your own logic to parse errors like - https://stackoverflow.com/questions/11450153/powershell-analogue-of-bashs-set-e

**Comment by freud14** [comment]
Alright, thank you for the answer. Damn Windows as always. I guess I'll make different steps.
