### ISSUE TITLE
Add Ubuntu 21.10

### ISSUE THREAD

**Issue by KOLANICH** [actions/virtual-environments#4210]
### Tool name

Ubuntu 21.10

### Tool license

aggregate of multiple products with different licenses

### Add or update?

- [X] Add
- [X] Update

### Desired version

21.10

### Approximate size

≥8.6 GB

### Brief description of tool

New version of Ubuntu

### URL for tool's homepage

https://help.ubuntu.com/community/Installation

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Not so different from existing envs.
```

### Tool installation time in runtime

Unknown. Pretty long.

### Are you willing to submit a PR?

No.

**Comment by catthehacker** [comment]
Ubuntu 21.10 can't be provided since it's not an LTS release.

> We support at least 2 latest OS versions (LTS only for Ubuntu) and initiate deprecation process for the oldest one when image usage drops below 5%.

from https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md#software-and-images-support-policy

Next LTS release will be Ubuntu 22.04
[![image](https://user-images.githubusercontent.com/31106839/135750874-e1c3cbb8-4373-450b-8dda-4167cdaf53fc.png)](https://ubuntu.com/blog/what-is-an-ubuntu-lts-release)

from https://ubuntu.com/blog/what-is-an-ubuntu-lts-release

**Comment by KOLANICH** [comment]
:facepalm: I'm sorry, I havent read the docs before posting (they have been added quite recently). My bad. I guess the policies are not the things to be disputed. I hope Microsoft policymakers have carefully evaluated pros and cons of before introducing such policies (and it'd be nice to see them near the policies).
