### ISSUE TITLE
Add xmllint

### ISSUE THREAD

**Issue by amai2012** [actions/virtual-environments#423]
**Tool information**
- Tool name: xmllint
- Add or update? Add
- Desired version: any
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Validate/check XML files
  - URL for tool's homepage: http://xmlsoft.org/

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Seconds!?

**Are you willing to submit a PR?**

**Comment by maxim-lobanov** [comment]
Tool can be installed in runtime using the following scripts:
```
sudo apt-get install libxml2-utils
```
Installation takes 7 seconds

**Comment by alepauly** [comment]
hi @amai2012, thanks for your suggestion but considering that installing within your build is pretty simple, we won't add this to the image at this time. thanks for the info @maxim-lobanov.

**Comment by bansp** [comment]
I would like to ask the maintainers to reconsider the "wontfix". `xmllint` is a lightweight utility on top of libxml2 that would cater to the basic needs of the XML-based (or XML-dependent) community by providing fast validation against the most important / widespread document grammars. While its installation may take 7 seconds on a good day, and it has succeeded for me as well, this very note was prompted by the following in my Actions script log, right now:
```
The following NEW packages will be installed:
  libxml2-utils
0 upgraded, 1 newly installed, 0 to remove and 12 not upgraded.
Need to get 108 kB of archives.
After this operation, 179 kB of additional disk space will be used.
Err:1 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libxml2-utils amd64 2.9.10+dfsg-2+ubuntu18.04.1+deb.sury.org+1
  404  Not Found [IP: 91.189.95.83 80]
E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/libx/libxml2/libxml2-utils_2.9.10+dfsg-2+ubuntu18.04.1+deb.sury.org+1_amd64.deb  404  Not Found [IP: 91.189.95.83 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
##[error]Process completed with exit code 100.
```
(and it keeps failing when I try to 're-run jobs'; I use `ubuntu-latest`)

My thinking is: xmllint is a tiny versatile utility on top of a library that is (and will no doubt remain, despite JSON) fundamental for nearly any Linux-based tools and toolchains. The price to add it and thus keep the XML people happy (or at least quieter ;-)) is 179 kB. Maybe the price is worth paying, or at least low enough not to mind paying it, against the community benefit.

Thanks for your work on Actions and thanks in advance for considering this request!

**Comment by bachp** [comment]
@bansp Have you considered runnint `apt-get update` before `apt-get install libxml2-utils` in my case it reduced the issue.

**Comment by bansp** [comment]
Hi @bachp I do use that line indeed now, thanks, but how can that help against network latency? I was unable to fetch the package. Updating first, with each single action, I run a greater risk of overall failure, because many more chance repositories can turn out to be unavailable.
Part of my thinking was that installing the utils package is a small price in PR terms as well, to be able to say to the XML community, "we're not neglecting you guys -- just like the others, you have a fundamental piece of software ready to use out of the box, while all the more complex stuff has to be installed first". But I'm not here to raise the flag and shout demands -- please read my comments as just something submitted for (re)consideration, in case the original decision was not meant to be absolutely final. Cheers!

**Comment by igorsantos07** [comment]
4 years later and I must add: it's odd, to say the least, to have `jq` but not `xmllint` available on the standard Ubuntu images :man_shrugging:
