### ISSUE TITLE
environments ending in latest should not produce upgrade warnings

### ISSUE THREAD

**Issue by ssbarnea** [actions/virtual-environments#4233]
### Description

I find the warnings raised by workflows using platforms like `ubuntu-latest` or `macos-latest` noisy as best and distracting.

These warnings make no sense for someone that did already make the decision to use the latest platforms in their workflows.

GHA should avoid penalizing those that decided to go for this path instead of going for a hardcoded version.

Those that do not want surprises should have already used the pinned versions and maybe be warned when these platforms are retired.

Still, those picking the "latest" tag, already made a decision and they expect to start using the newer platform as soon it becomes available to them.

A warning does not help here and only adds noise, noise that lingers for weeks and months.

The current behavior somehow drives people to move to pinned versions and that means that when new platforms become available they will almost for sure miss to test with them.

To make an analogy with docker containers using latest tag, when someone is using a latest tag, they know that it can change at any moment, they do not need to be warned about that at every execution.

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

n/a

### Repro steps

Check jobs that use ubuntu-latest or macos-latest and you will see that they have warnings about the upcoming upgrades.

**Comment by miketimofeev** [comment]
Hi @ssbarnea!
We understand that those warnings can be annoying for you, but I'm afraid we would have received much more complaints if we hadn't made a warning at all as many people don't check this repository for the announcements, and don't expect the tag migration. 
Currently, the notifications in GitHub are configured in the following way:
- If your build is on `macos-latest` and it's resolved to `macOS-10.15` the notification about sooner migration will be displayed so that you are aware of such future changes
- if your build is on `macos-latest` and it's resolved to` macOS-11`, and **the build fails** the notification about the changed macos-latest label will be displayed so that you are aware that your build might have failed because of that.

Unfortunately, currently, there is no way to make this warning dismissable after the first show. Please feel free to raise a discussion about the proper notifications method in our discussions section https://github.com/actions/virtual-environments/discussions The notification conditions are subject to change if we have enough feedback.

I'm going to close the issue, please feel free to contact us if you have any concerns.
Thank you!

**Comment by ssbarnea** [comment]
As its usefulness is debatable it would be useful to give an option to silence them inside the pipeline config. No need to think about UI notification that can be marked as ack by the user as this would be too complex to be practical to implement. Still, disabling using pipeline config looks like a decent compromise IMHO. Thanks!
