### ISSUE TITLE
Build failure due to running a subprocess in Java in windows-2019/20211102.4 environment

### ISSUE THREAD

**Issue by algomaster99** [actions/virtual-environments#4485]
### Description

I am executing junit5 for executing tests in my [project](https://github.com/SpoonLabs/sorald) and inside one of the test cases, a [subprocess is executed](https://github.com/INRIA/spoon/blob/2fff4c50266f79bc06b961e3b01ca6c6e0fcc1ab/src/main/java/spoon/support/compiler/SpoonPom.java#L523) which tries to find the path to the `mvn` executable. If we run `mvn.cmd -version`, the process exits with code `1` and there is nothing in the error stream (`.read()` returns `-1`). One workaround we have thought of is to execute `cmd /c mvn.cmd -version` which returns the path to the `mvn.cmd` executable. However, it would be better if we don't have to resort to that because open a entire subshell is vulnerable to attacks if user inputs are taken.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version
```
Microsoft Windows Server 2019
  10.0.17763
  Datacenter
Virtual Environment
  Environment: windows-2019
  Version: 20211102.4
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20211102.4/images/win/Windows2019-Readme.md
```

### Build link
https://github.com/SpoonLabs/sorald/runs/4123271163?check_suite_focus=true#step:11:44

### Is it regression?

win19/20211018.0 https://github.com/SpoonLabs/sorald/runs/4087248573?check_suite_focus=true

### Repro steps

1. Excute the following Java code in the a workflow.
   ```java
    Process p = Runtime.getRuntime().exec(new String[]{"mvn.cmd", "-version"});
   ```
2. The tests will execute but the subprocess `p` exits with code `1`.

**Comment by al-cheb** [comment]
Hey, @algomaster99 
We will take a look at it.

**Comment by algomaster99** [comment]
Hi @al-cheb !

Thank you! Please mention me if you need anymore details.

**Comment by nikolai-frolov** [comment]
Hello @algomaster99. Looking at the exception messages `spoon.SpoonException: M2_HOME must be initialized to use this MavenLauncher constructor`, your project still uses `M2_HOME` which was deprecated and removed along with Win 20211102.4 release (more details here: https://github.com/TheCakeIsNaOH/chocolatey-packages/issues/17). Probably you need to redesign your scripts to avoid M2_HOME usage.

**Comment by algomaster99** [comment]
@nikolai-frolov Thanks for your reply!

Our project is configured to find path of `mvn` from `PATH` as well (by running `mvn -version` on linux and `mvn.cmd -version` on Windows). It doesn't necessarily rely on the value of `M2_HOME`. However, we cannot run execute the `mvn.cmd -version` command in Windows because when we execute the above snippet,
 >  `Process p = Runtime.getRuntime().exec(new String[]{"mvn.cmd", "-version"});`

the subprocess exits with `1` however, JVM executing Junit5 proceeds to run and it only exits when we get the `M2_HOME must be initialized to use this MavenLauncher constructor` exception.

So we try to find the `mvn` executable in two steps.
1. We check the value of `M2_HOME`.
2. We try to execute `mvn.cmd -version` command and get the path from its output.

On Windows, we aren't able to execute the command as a subprocess. It is obvious that `mvn` is in `PATH` because `mvn tests` is executed in the linked workflow before.

**Comment by slarse** [comment]
Alright, so I debugged this quite extensively. The root of the problem is that for some reason, on Windows, `Runtime.exec` does not lookup binaries on the `PATH`. So, even if `mvn.cmd` is clearly on _all_ paths (user, system and process), it's not recognized as a command.

This differs from how it works on *NIX-like systems, where any executable on the `PATH` (or rather, in a directory on the `PATH`) is recognized as a valid command. So this is not a problem with `setup-java`, it's just an inconsistency with how `Runtime.exec` works across platforms.

If anyone can explain why it's like this, feel free, I can't find this documented anywhere. What works is either launching an entire shell which then actually resolves the `PATH` (e.g. `cmd /c "mvn.cmd -version"`), or providing the absolute path to the binary when launching the subprocess (e.g. `C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.3\bin\mvn.cmd`).

@algomaster99 You can close this issue, this is just a Windows quirk and not a problem with `setup-java`.

**Comment by algomaster99** [comment]
Thanks, @nikolai-frolov and @slarse for your answers! Closing this issue as it is not related to GHA.
