### ISSUE TITLE
Network timeout in specific Cloud Github CI Runners

### ISSUE THREAD

**Issue by Dd-Abraham** [actions/virtual-environments#4700]
### Description

Hello,

We are facing timeouts when requesting a particular host from specific Github CI runners (SaaS/Cloud runners). This issue happens intermittently and only on specific Github CI runners (1 time out of 3/4 runs).

This happens when requesting https://package.datadome.co/linux/DataDome-Apache-latest.tgz. We do not observe this behaviour anywhere else but here in Github CI.

We don't see the request arriving at all at our webserver (no access logs).

We have only observed this behaviour in Github CI Actions in private repositories, not sure if it matters.

We are unsure if this issue happens when requesting other hosts or only for this specific one. We haven't seen it happen when requesting anything else.

The issue is 100% reproducible if you end up using the same runner and 100% runner dependent from what we have tested.

Runners where it has happened:

```
GHEUS3U20WUS3C12-0030
GHEUS3U20WUS3C16-0067
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20211108.1

### Is it regression?

More like intermittent

### Expected behavior

```
wget https://package.datadome.co/linux/DataDome-Apache-latest.tgz
--2021-12-09 10:35:52--  https://package.datadome.co/linux/DataDome-Apache-latest.tgz
SSL_INIT
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving package.datadome.co (package.datadome.co)... 34.243.206.89
Connecting to package.datadome.co (package.datadome.co)|34.243.206.89|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://package.datadome.co/linux/DataDome-Apache-2.47.tgz [following]
--2021-12-09 10:35:52--  https://package.datadome.co/linux/DataDome-Apache-2.47.tgz
SSL_INIT
Reusing existing connection to package.datadome.co:443.
HTTP request sent, awaiting response... 200 OK
Length: 25494 (25K) [application/x-gzip]
Saving to: ‘DataDome-Apache-latest.tgz’

DataDome-Apache-latest.tgz                           100%[===================================================================================================================>]  24.90K  --.-KB/s    in 0.02s   

2021-12-09 10:35:52 (1.12 MB/s) - ‘DataDome-Apache-latest.tgz’ saved [25494/25494]
```

(Successful download)

### Actual behavior

```
Connecting to package.datadome.co (package.datadome.co)|34.243.206.89|:443... failed: Connection timed out.
```

(It retries 20 times and fails the pipeline after a couple minutes)

### Repro steps

1. Create a new Github CI workflow in a private repository that performs a wget on https://package.datadome.co/linux/DataDome-Apache-latest.tgz.
You can use the following workflow:
```
name: Demo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: ls /data/instancename

      - run: wget https://package.datadome.co/linux/DataDome-Apache-latest.tgz
```

2. Run it multiple times until it timeouts.

**Comment by al-cheb** [comment]
Hey, @Dd-Abraham 
We will take a look at it.

**Comment by shilovmaksim** [comment]
Hi @Dd-Abraham . 
I've investigated this issue. Connection timeouts trying to download package from https://package.datadome.co not related to either following:
- repo visibility (workflow using the same agents despite the repo privateness)
- VM image (either on GHA image or vanilla marketplace image)
  - Clean ubuntu (Location: West US2): 
![image](https://user-images.githubusercontent.com/89912354/145771988-d4eee352-229b-4a65-9cca-fabc2ee93728.png)
![image](https://user-images.githubusercontent.com/89912354/145772066-36d56b6d-6055-427b-8127-bbe71d980bf3.png)

    - GHA image VM (Location West US2): 
![image](https://user-images.githubusercontent.com/89912354/145772594-ab39cf33-95a7-403f-8c2d-92aa82eec733.png)
![image](https://user-images.githubusercontent.com/89912354/145772689-3ddd1084-d815-467a-ba9e-5c3cc57bd8d0.png)

- image OS (Windows or Ubuntu with one note here)
  - It works on MacOS image which GHA hosting on another cloud provider
- Command that trying to download (wget, curl, Invoke-WebRequest)

Example run: https://github.com/shilovmaksim/test-repo/runs/4502810248

This is clearly the connectivity issue between Azure cloud that hosting GHA resources and AWS "https://package.datadome.co" hosted on.
I would recommend you to check your host LB or FW settings or please engage Azure support as it will be much faster to communicate with them directly rather than through our team.

**Comment by Dd-Abraham** [comment]
Hello @shilovmaksim thanks for your digging. Unfortunately we do not have an active Azure subscription with a decent enough support plan to be able to get technical support for an issue like this.

Isn't this a known issue for GHA ? I've seen multiple tickets opened in this repository with the same issue. Would it be possible for you to engage with them ?

We also lack relevant information about GHA infrastructure to be able to engage in any kind of support procedure with Azure anyway.

**Comment by shilovmaksim** [comment]
Hi @Dd-Abraham . This type of issue is not something common and usually caused by misconfiguration of a package host.
I've opened support ticket in Azure. Let's see what they'll answer about this.

**Comment by Dd-Abraham** [comment]
Thank you @shilovmaksim

**Comment by shilovmaksim** [comment]
Hi @Dd-Abraham .
Azure support confirmed the issue and that it somehow related to the VM region: no repro on the West EU region. Unfortunately support could not get the possible cause.
GitHub hosted runners setup to run on a VMs from multiple regions. We cannot change it.
As a possible workaround, you can setup your own runners ( [about-self-hosted-runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) ) that will not have this issue.

**Comment by Dd-Abraham** [comment]
Ok, thanks for confirming the issue, we already have a work around in place that's simpler than setting up our own runners which we won't do for the moment. 

Thanks anyway ! I'll close this ticket
