### ISSUE TITLE
Update NSIS to 3.08

### ISSUE THREAD

**Issue by andrew-r-king** [actions/virtual-environments#4739]
### Tool name

NSIS / MakeNSIS

### Tool license

zlib/libpng

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.08

### Brief description of tool

Nullsoft Scriptable Install System

### URL for tool's homepage

https://nsis.sourceforge.io

### Provide a basic test case to validate the tool's functionality.

```bash
This script just needs to be updated to install 3.08:
https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Install-NSIS.ps1

There's a pretty nasty bug in 3.06.1 (current version) that prevents one from adding plugin directories (that was fixed in 3.07+): https://sourceforge.net/p/nsis/bugs/1264/

plugins are a cruicial part of NSIS installers
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

sure!

**Comment by miketimofeev** [comment]
Hi @andrew-r-king!
Thank you for your contribution! The PR will be merged once all the checks are passed.

**Comment by miketimofeev** [comment]
@andrew-r-king the PR is merged and changes will be available next week.

**Comment by GrafGenerator** [comment]
Although it's not directly related to original issue purpose, I'm posting comment here in case anyone face this too.

NSIS v3.07 introduced Unicode being used by default when compiling installers, for me this caused setup compilation process to show no errors at all. Installer failed randomly, producing no output log (actually the log file was simply "C", with some lines containing 2, which led me to the reason it failing).

In case this happens, quickest way is to add "Unicode false" to the very beginning of NSI scripts. This should do the thing, however, for me it caused another issue. Before this I included plugins dynamically, providing `/X"!addplugindir plugins-folder"` to makensis, now it's not working. The reason seems to be that, the overall command is `makensis /X"!addplugindir plugins-folder" /X"include setup.nsi"`, and makensis does this:

1. Loads default plugins which are now unicode (x86-unicode path)
2. Loads my custom plugins, specified by /X directive.
3. Faces "Unicode false" in NSI script, drops included plugins, loads ANSI versions (x86-ansi).
4. Continues executing script. Custom plugins are lost now.

Fixes are obvious: either add !addplugindir to NSI script as well, or add another /X"Unicode false" before every other /X, forcing makensis to switch early.

**Comment by miketimofeev** [comment]
@andrew-r-king the new images have been deployed!
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
