### ISSUE TITLE
Update Google Chrome

### ISSUE THREAD

**Issue by DanielLDB** [actions/virtual-environments#5045]
### Tool name

Google Chrome

### Tool license

Proprietary freeware, based on open source components.

### Add or update?

- [ ] Add
- [X] Update

### Desired version

98.0.4758.8000

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by danielhjacobs** [comment]
Because this has not yet been done but https://github.com/giggio/node-chromedriver/pull/347 was merged:

On the Ruffle CI:

Looks like ubuntu wants ChromeDriver version 98 and fails with ChromeDriver version 96: https://github.com/ruffle-rs/ruffle/runs/5147150936?check_suite_focus=true

Meanwhile, Windows uses Chrome version 97 and so ChromeDriver version 98 fails: https://github.com/ruffle-rs/ruffle/runs/5147528388?check_suite_focus=true

**Comment by miketimofeev** [comment]
@DanielLDB the new image has been deployed.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
