### ISSUE TITLE
Add MacPorts

### ISSUE THREAD

**Issue by nalzok** [actions/virtual-environments#5117]
### Tool name

MacPorts

### Tool license

3-Clause BSD License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest, i.e. 2.7.1

### Approximate size

15MB

### Brief description of tool

A package management tool, an increasingly popular alternative to HomeBrew. To quote the project homepage,

> The MacPorts Project is an open-source community initiative to design an easy-to-use system for compiling, installing, and upgrading either command-line, X11 or Aqua based open-source software on the Mac operating system. To that end we provide the command-line driven MacPorts software package under a [3-Clause BSD License](http://opensource.org/licenses/BSD-3-Clause), and through it easy access to thousands of ports that[ greatly simplify](https://guide.macports.org/#introduction) the task of [compiling and installing](https://guide.macports.org/#using) open-source software on your Mac.
> 
> We provide a single software tree that attempts to track the latest release of every software title (port) we distribute, without splitting them into “stable” Vs. “unstable” branches, targeting mainly macOS Mojave v10.14 and later (including macOS Monterey v12 on both Intel and Apple Silicon). There are thousands of ports in our tree, distributed among different categories, and more are being added on a regular basis.

### URL for tool's homepage

https://www.macports.org/

### Provide a basic test case to validate the tool's functionality.

```bash
sudo port selfupdate
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
# See https://www.macports.org/install.php
aria2c https://github.com/macports/macports-base/releases/download/v2.7.1/MacPorts-2.7.1-12-Monterey.pkg
sudo installer -pkg MacPorts-2.7.1-12-Monterey.pkg -target /
```

### Tool installation time in runtime

Several minutes

### Are you willing to submit a PR?

Yes

**Comment by miketimofeev** [comment]
Hi @nalzok!
We understand this is a popular tool but I'm afraid we wouldn't like to install it along with the homebrew because of maintenance concerns — if something doesn't work due to the conflict between the packages pre-installed with brew and installed with MacPorts a customer will come to us and complain.
Please consider installing MacPorts in runtime as it does take less than a minute:
```
wget https://github.com/macports/macports-base/releases/download/v2.7.1/MacPorts-2.7.1-11-BigSur.pkg
sudo installer -pkg ./MacPorts-2.7.1-11-BigSur.pkg -target /
```
I'm going to close the issue but please feel free to contact us if you have any concerns.
Thank you!

**Comment by ManuelSchneid3r** [comment]
I'd like to ask you to reconsider this issue since homebrew decided to not support universal binaries, while macports does. With great power comes great responsibility. Avoiding conflicts is the responsibility of the developer. If you still decide to not ship macports, please add a little tutorial on setting up macports properly. At least on my system it pulls half an operating system to build two dependencies, probably due to some missing library paths. 

If anybody managed to get a manually installed macports work properly please let me know.

**Comment by jimmy-shaojun** [comment]
Hi, @ManuelSchneid3r  I try to install macports in ~/ and it seems ok.

I need macports because my project needs access to GnuCash python bindings and it is only available in Mac with macports.

This is a [build job](https://github.com/huangjimmy/gnucash-plaintext/actions/runs/8395589499/job/22995177731) that install macports and then build and install GnuCash with python binddings in mac-latest

This is the [workflow file](https://github.com/huangjimmy/gnucash-plaintext/actions/runs/8395589499/workflow)

The only problem in my case is that the build process is too long and timeout after 6 hours.  I have to disable the mac job while keeping the workflow source code for reference.

I also try on my own Mac. 

It takes macports hours to install GnuCash on my 2017 Intel MacBook Pro. I check the mac runners provided by github and I believe unless you use a paid plan you won't be able to build something like GnuCash with default mac-latest runner. My guess is that you will need to use xlarge runner.

Macports does install GnuCash quickly on my latest M2 Max 64GB ram MacBook Pro.

**Comment by spinicist** [comment]
> Hi @nalzok! We understand this is a popular tool but I'm afraid we wouldn't like to install it along with the homebrew because of maintenance concerns — if something doesn't work due to the conflict between the packages pre-installed with brew and installed with MacPorts a customer will come to us and complain. Please consider installing MacPorts in runtime as it does take less than a minute:
> 
> ```
> wget https://github.com/macports/macports-base/releases/download/v2.7.1/MacPorts-2.7.1-11-BigSur.pkg
> sudo installer -pkg ./MacPorts-2.7.1-11-BigSur.pkg -target /
> ```
> 
> I'm going to close the issue but please feel free to contact us if you have any concerns. Thank you!

Hi, I tried this method today but it doesn't work for me. The install appears to complete successfully but then a subsequent `sudo port install` command fails to find the `port` executable. My workflow can be found here: https://github.com/spinicist/riesling/blob/ducc/.github/workflows/build.yml#L46

Do I need to change the path to the binary?

**Comment by spinicist** [comment]
Specifying the full path as `/opt/local/bin/port` seems to have worked. I hope.

**Comment by HofiOne** [comment]
> This doesn't leave Macports in a useable state, my build system can't find the installed libraries. Such disappointment.

You can see a working usage example in syslog-ng CI macOS build [workflow file](https://github.com/syslog-ng/syslog-ng/blob/master/.github/workflows/macos.yml)

Bullet points:
- download the proper MacPorts pkg file, and
- install it (like mentioned above)
- set up the build env prior to using the `port` command
- use `port install` as usually
