### ISSUE TITLE
Cannot build Python C extensions on windows-2022

### ISSUE THREAD

**Issue by lpsinger** [actions/virtual-environments#5141]
### Description

When we try to build Python C extensions on windows-2022, the build fails [see GitHub Actions log](https://github.com/astropy/pytest-doctestplus/runs/5336186459?check_suite_focus=true#step:5:220) with the following error message:

> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
[221](https://github.com/astropy/pytest-doctestplus/runs/5336186459?check_suite_focus=true#step:5:221)

This worked on windows-2019. We noticed it because windows-latest just bumped to windows-2022.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20220220.1

### Expected behavior

The Python C extension should be built without errors.

### Actual behavior

The build fails with the error message noted above.

### Repro steps

Build any Python C extension. See https://github.com/astropy/pytest-doctestplus/blob/main/.github/workflows/python-tests.yml

**Comment by mikhailkoliada** [comment]
@lpsinger thanks, we will take a look!

**Comment by nikolai-frolov** [comment]
@dsame this issue looks similar to https://github.com/actions/virtual-environments/issues/5125 which you are looking at. Could you please confirm?

**Comment by nikolai-frolov** [comment]
@lpsinger could you please share the simple project/yml which allows to reproduce the issue in case it's still actual?

**Comment by nikolai-frolov** [comment]
@lpsinger this yml doesn't work for me without additional steps: https://github.com/nikolai-frolov/image-testing/actions/runs/1910180528. Please provide a simple example.

**Comment by lpsinger** [comment]
See https://github.com/lpsinger/github-actions-windows-2022-python-c-extension. This is as simple as I can make it.

**Comment by mayeut** [comment]
Given the number of issues linked, not sure if "It is a tox issue" applies in all cases but at least, for the minimal reproducer shared by @lpsinger, it is https://github.com/tox-dev/tox/issues/2382.
Installing tox from main solves the issue: https://github.com/mayeut/github-actions-windows-2022-python-c-extension/runs/5799864485?check_suite_focus=true

**Comment by pllim** [comment]
Speaking for `astropy/pytest-doctestplus` (source of the original post), it is undesirable for us to be using dev tox but we'll be happy to try this tox fix out once it is released. Thanks!

**Comment by dsame** [comment]
Hello @lpsinger, 

Can you please try to re-run you build with windows-latests without other changes?

I forked and reverted your repo to the failed commit https://github.com/astropy/pytest-doctestplus/commit/feea9835dd345d2efc9907a4be9f92b0fbe37289

and the build passed https://github.com/akv-platform/pytest-doctestplus/actions/runs/2149804973
also i run the build the repo head and it passed as well https://github.com/akv-platform/pytest-doctestplus/runs/5975846421?check_suite_focus=true

JFI: i suspected there's some issue with the tox could not find build tools due to something related to this setting https://docs.python.org/3/distutils/apiref.html#module-distutils.msvccompiler but i am not able to investigate the problem because it is reproduced not.

**Comment by lpsinger** [comment]
Working again now. Thanks!
