### ISSUE TITLE
Update/Add yq

### ISSUE THREAD

**Issue by allanlei** [actions/virtual-environments#5144]
### Tool name

yq

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

4.20.2

### Brief description of tool

> yq is a portable command-line YAML, JSON and XML processor

Looking to include `yq` which is in `ubuntu-latest` such that the tool sets are consistent in `macos-latest`

### URL for tool's homepage

https://github.com/mikefarah/yq

### Provide a basic test case to validate the tool's functionality.

```bash
yq <<< 'hello: world'
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Hello @allanlei!
Thanks for the report, we will decide on adding it and get back to you.

**Comment by miketimofeev** [comment]
@allanlei we don' mind adding `yq` to macOS for consistency. The new images will be deployed next week.

**Comment by miketimofeev** [comment]
@allanlei The PR with yq has been merged. We are going to deploy the new images next week. Sorry for the delay

**Comment by allanlei** [comment]
@miketimofeev 
No problem.  Thanks for this!

**Comment by igorboskovic3** [comment]
The new MacOS 11 image have been deployed.
We added yq tool to image here
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md

![image](https://user-images.githubusercontent.com/68074361/162761700-60154b62-f20b-4369-a6c2-8434231e60cb.png)

Sorry for the delay due to unpredictable circumstances
