### ISSUE TITLE
Bug with container actions and NPM (workspaces?) and github-repository links

### ISSUE THREAD

**Issue by tetrasmolyn** [actions/virtual-environments#5152]
### Description

Please see my community post: https://github.community/t/bug-with-container-actions-and-npm-workspaces-and-github-repository-links/230977

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/tetrasmolyn/containertest

### Repro steps

I have a very bizarre scenario here, which I have spent several days trying to isolate.

Let me set the scene: medium sized monorepo using npm workspaces, with several packages in package.json pointing to (internal) github repositories directly.

Everything runs fine with the standard Github Action (ie. runs-on: ubuntu-latest).
The second I add “container: node:16-alpine” (or ubuntu:latest, or anything), it starts breaking with odd errors during “npm ci” / “npm install”.

Community post has more details

Here is an example simplified repo with the problem:
https://github.com/tetrasmolyn/containertest

Reproduction Steps

Please see community post:
https://github.community/t/bug-with-container-actions-and-npm-workspaces-and-github-repository-links/230977

**Comment by mikhailkoliada** [comment]
@tetrasmolyn Hi!

Thanks for the report! We will take a look!

**Comment by dsame** [comment]
@tetrasmolyn 
The root cause is the node:16-alpine sets $HOME env variable to the strange values /github/home - please contact the image developers to change this

The workarounds:
1. Grant write permission to the default npm cache dir: `- run: mkdir -p /github/home && sudo chown -R 1001:121 /github/home`
see the build https://github.com/akv-platform/containertest/actions/runs/2030958270

2. Change the npm cache dir to the location with write permissions `npm ci --cache /tmp/.npm`
see the build https://github.com/akv-platform/containertest/runs/5667982457?check_suite_focus=true

**Comment by panekj** [comment]
> The root cause is the node:16-alpine sets $HOME env variable to the strange value `/github/home`

This is not correct, `HOME=/github/home` is set by GHA runner, probable here: https://github.com/actions/runner/blob/882f36dcf8a951dac2dc1bebd9e69bdc4de6b1a7/src/Runner.Worker/Handlers/ContainerActionHandler.cs#L169-L171
```
❯ docker run -ti --rm node:16-alpine env
NODE_VERSION=16.14.2
HOSTNAME=6010b15ff178
YARN_VERSION=1.22.18
SHLVL=1
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
```

**Comment by miketimofeev** [comment]
@panekj could you please file an issue to the runner repo then?
