### ISSUE TITLE
Apparent performance regression in latest windows images (20220220.1 compared to 20220207.1)

### ISSUE THREAD

**Issue by MikeDombo** [actions/virtual-environments#5158]
### Description

The recent windows images seem to have had a performance regression from windows-2022 20220207.1 to 20220220.1. Tests are now timing out and taking more than 45 minutes, where a succesful test 13 days ago took roughly 34 minutes and was successful.

The only difference I can see is the windows image number, but certainly changes to the underlying VM hardware could also affect the performance (but I don't have a way to know that there is any change).

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20220220.1 - https://github.com/actions/virtual-environments/releases/tag/win22%2F20220220.1 - https://github.com/aws-greengrass/aws-greengrass-nucleus/runs/5379679653?check_suite_focus=true
20220207.1 - https://github.com/actions/virtual-environments/releases/tag/win22%2F20220207.1 - https://github.com/aws-greengrass/aws-greengrass-nucleus/runs/5225475348?check_suite_focus=true

### Is it regression?

20220207.1 https://github.com/aws-greengrass/aws-greengrass-nucleus/runs/5225475348?check_suite_focus=true

### Expected behavior

Tests should pass in ~34 minutes with no errors.

### Actual behavior

Many tests fail with timeouts and the total test time is over 45 minutes. The tests are primary around process launching and monitoring. 

### Repro steps

Run the CI steps for Greengrass Nucleus project and observe that it is significantly slower than previous runs.

**Comment by mikhailkoliada** [comment]
Hello @MikeDombo!

Thanks for the report, we will take a look.

**Comment by dsame** [comment]
Hi @MikeDombo 

I rolled back the codebase to the last successful commit and increased the timeouts for the failed tests by ~100 times.

There's neither significant total build time increase nor some individual tests. It proves the tests fail because of some other reason they did not complete in time.  I still suppose there're flaky code but i can not identify it well because of code base complexity. 

Can you please create minified version of the build including only the tests from DeploymentTaskIntegrationTest.java and add more debug output to the code under the testing or give some idea where the execution can be  affected by some side effects during the execution (say having not synchronization in the parallel threads for example ).

Ideally can you please add unit tests for  the code used in the integration tests if they do not exist. They can give more idea for the investigation.

Thanks.

**Comment by al-cheb** [comment]
I am planning to close the thread. Feel free to open it if you have any concerns.
