### ISSUE TITLE
Update/Add Xcode 13.3

### ISSUE THREAD

**Issue by haavamoa** [actions/virtual-environments#5241]
### Tool name

Xcode

### Tool license

Apple

### Add or update?

- [ ] Add
- [X] Update

### Desired version

13.3

### Brief description of tool

Latest iOS 15.3.1 requires Xcode 13.3 installed.

### URL for tool's homepage

https://developer.apple.com/xcode/

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by maxim-lobanov** [comment]
Hello @haavamoa , Xcode 13.3 can't be installed on macOS 11 because it is not supported by Apple.
To use Xcode 13.3, you need macOS 12.
Unfortunately, it is in private preview for now. You can sign up to macOS 12 preview using this message: https://github.com/actions/virtual-environments/issues/3649#issuecomment-1068085030
