### ISSUE TITLE
Chromium install fails when comparing versions

### ISSUE THREAD

**Issue by jammehcow** [actions/virtual-environments#5256]
### Description

When building the Ubuntu 20.04 image, the chrome install fails with `/tmp/script_3539.sh: line 30: [: 1017e516b4fd1e4ceeae91b31d8ba562dded4af4: integer expression expected` (maps to `images/linux/scripts/installers/google-chrome.sh`).

This happens because the response from https://www.googleapis.com/storage/v1/b/chromium-browser-snapshots/o?delimiter=/&prefix=Linux_x64/10 contains a single line that doesn't match the expected version format:
```
Standard format:
Linux_x64/101799/

Erroneous version:
Linux_x64/1017e516b4fd1e4ceeae91b31d8ba562dded4af4/
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

None available, testing locally with QEMU

### Is it regression?

no, appears to be caused by an external dependency

### Expected behavior

google-chrome script installs chomium without error

### Actual behavior

script crashes, `Browsers.Tests.ps1` fails to find chromium

### Repro steps

1. Checkout `releases/ubuntu20/20220316`
2. Build packer image
3. Wait for failure

**Comment by mikhailkoliada** [comment]
@jammehcow Hello!

Thanks, we will take a look!

**Comment by jmos5156** [comment]
I've had a play around with the `google-chrome.sh` script and have some findings.

1. As [jammehcow](https://github.com/jammehcow)says,  Google have somehow listed this `1017e516b4fd1e4ceeae91b31d8ba562dded4af4` as a version number [here](https://www.googleapis.com/storage/v1/b/chromium-browser-snapshots/o?delimiter=/&prefix=Linux_x64/10). This does not look like a valid entry and does throw the script of a little but it's not the full story.
 
2. The script function `GetChromiumRevision` retrieves two lists of chrome browser versions. 1) for the current version of installed chrome and 2) the version previous Then sorts them. However, the sort happens on the concatenated list which places older versions at the top.

Using the https://omahaproxy.appspot.com/ as in the function, yields Branch Base Position which is four digits.
![image](https://user-images.githubusercontent.com/34477034/159539865-2c0f8163-5ee5-4c20-805d-908b9f6ef880.png)
This means that older version numbers will always be higher and we can hit issues.

To fix 1. we could use `sed "/[a-z]/d"` in the pipeline to remove entries that contain alpha chars or even use `[:alnum:]`.
To fix 2. could we not run `sort --version-sort` on each list individually and then concatenate them. This will at least place the latest versions above the previous versions and we have a greater chance of getting the nearest one.

To help with the four-digit code for the base branch would running another check against the V8 Version be of use? Having the double-check could help with base number issues like these allbeit they probably do not happen very often.

**Comment by miketimofeev** [comment]
Thanks, @jmos5156!
yes, fixing 1. is easy, we will apply the pattern.
We have also found this strange four-digit number and decided to apply a workaround and hardcode the previous revision for now. Will keep an eye on this because it is not clear if that four-digit number is a bug or feature since all the further versions (beta and dev) contain six digits as usual.

**Comment by jeffj254** [comment]
Ran into this today as well, we're also going with hardcoding the version for now.  Putting some filtering so alphanumerics are removed from the version list seems like a good fix to me, though as said, the 4 digit base position will continue to be an issue.

Sorting each returned version list individually and then concatenating would put us back in the situation where certain releases of Chrome could cause the algorithm to choose a very old version of Chrome (#4314).  The fix for that issue was to include the versions from the previous base position and merge them together to provide a greater chance of properly choosing a recent release, I think that functionality is still needed, barring a more thorough rewrite of this.

**Comment by miketimofeev** [comment]
@jammehcow @jeffj254 the PR is merged now and the generation should work again. We will think of a better approach to handle chromium releases, please also share your thoughts and feel free to submit a PR with the improvements.
Thank you!

**Comment by jammehcow** [comment]
Thanks @miketimofeev & @jeffj254, I'll give it a play later today.

**Comment by jammehcow** [comment]
Sorry for the late follow up: all looks good to me! Thanks for the quick fix.
