### ISSUE TITLE
Update [zlib]

### ISSUE THREAD

**Issue by xavier2k6** [actions/virtual-environments#5330]
### Tool name

Zlib

### Tool license

N/A

### Add or update?

- [ ] Add
- [X] Update

### Desired version

1.2.12

### URL for tool's homepage

Zlib.net

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by al-cheb** [comment]
Hello @xavier2k6,
We don't have any plans to add zlib tool on Windows due to manually maintenance release to build a new version of tool every time when a new release is released. Ubuntu Server and macOS have the previous zlib 1.2.11 version. Let's wait until zlib 1.2.12 has been updated in the apt and brew repos.

**Comment by miketimofeev** [comment]
@xavier2k6 macOS brew formula update is currently in review https://github.com/Homebrew/homebrew-core/pull/98171
For linux as @al-cheb said we have to wait until the upstream repository is updated.
I'm going to close the issue.
Thank you!

**Comment by xavier2k6** [comment]
@al-cheb @miketimofeev `zlib 1.2.12` available in [homebrew](https://formulae.brew.sh/formula/zlib#default) & [ubuntu](https://launchpad.net/ubuntu/+source/zlib) now.

**Comment by xavier2k6** [comment]
@miketimofeev Thanks for the follow-up.
