### ISSUE TITLE
Update Mingw on windows

### ISSUE THREAD

**Issue by abrown** [actions/virtual-environments#5530]
### Tool name

mingw

### Tool license

ZPL?

### Add or update?

- [ ] Add
- [X] Update

### Desired version

Latest?

### Brief description of tool

The current `windows-latest` image has MinGW v8.1.0 installed (https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#tools). Since v8.1.0 was released in October 2018, MinGW has released several more versions, all the way up to v11.2.0: https://community.chocolatey.org/packages/mingw#versionhistory. I am proposing an upgrade to v11.2.0 (or really any version newer than what is currently available.

### URL for tool's homepage

https://community.chocolatey.org/packages/mingw#versionhistory

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
choco install mingw
```

### Are you willing to submit a PR?

Sure...

**Comment by igorboskovic3** [comment]
Hi @abrown thank you for your suggestion, we will take a look.

**Comment by miketimofeev** [comment]
@abrown we rolled back to mingw 8.1.0 due to the fact that the latest version at that moment (10.2) didn't include the` mingw32-make.exe` tool but looks like the tool is present in the newest version (11.2.0) so we don't have any objections adding it to the image. Would you mind creating a PR? If yes please make sure to move the MinGW version to the toolset file so we can install different versions for windows-2019 (8.1.0) and for windows-2022 (11.2.0)

**Comment by bnjbvr** [comment]
I've taken a quick look at this, but I'm not sure to follow what's going on right now: it seems that the provisioner scripts will install mingw with choco (using the script you're alluding to), but mingw is also listed in the list of packages to install with msys, if I understand correctly (I would certainly be wrong, since I just skimmed the code for half an hour.)

Should it be only one or the other, instead? If so, which would be preferred?

Also, it seems that the mingw install script also copies the `mingw-make` to `make` so it can be found more easily by tooling. I presume this should still run, independently of the way mingw is installed. If so, I _think_ it would Just Work to remove the `Choco-Install` line from that file, let Choco/Msys install mingw, as the provisioner script first installs the common tools _before_ running the mingw-specific script. Is that a reasonable approach?

**Comment by miketimofeev** [comment]
@bnjbvr we install mingw package for msys2 as well, yes, but:
- it's true only for win19
- msys2 is not on the path
so, we are interested only in this script https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Install-Mingw64.ps1
$toolsetVersion = (Get-ToolsetContent).mingw.version

**Comment by abrown** [comment]
@miketimofeev, thanks! About how long should I wait to see this propagate to GitHub runners out there?

**Comment by miketimofeev** [comment]
@abrown we will start the new image deployment on Monday-Tuesday and it will take 3-4 days to propagate the image.
