### ISSUE TITLE
Running .net5 tests failed because .net5 framework was not found

### ISSUE THREAD

**Issue by pmatuszewski** [actions/virtual-environments#5794]
### Description

Before environment update I was able to run tests for .net5 application. 
Currently when tests are run following error is displayed:

Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.WindowsDesktop.App', version '5.0.0' (x86) was not found.
  - The following frameworks were found:
      3.1.26 at [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
      6.0.6 at [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Environment: windows-2019
  Version: 20220614.0

### Is it regression?

20220606.1

### Expected behavior

It should be possible to run tests for .net5 application

### Actual behavior

Running tests fails

### Repro steps

1. build .net5 project with tests using msbuild
2. run tests e.g dotnet test apptests.dll

**Comment by miketimofeev** [comment]
This is expected behavior as runtime component was upgraded from 5 to 6 recently https://github.com/actions/virtual-environments/pull/5749/files
![image](https://user-images.githubusercontent.com/48208649/175029066-66720829-4631-4928-b800-27cde8f2be0e.png)
@timheuer could you please suggest what is the best possible option to solve the issue?

**Comment by timheuer** [comment]
@pmatuszewski .NET 5 is out of support, but you can at your own control install it on your run.  Using the `setup-dotnet` action and specify the `5.0.x` version to install prior to your subsequent commands.

**Comment by pmatuszewski** [comment]
Thanks for your response. Unfortunately installing .NET 5 with setup-dotnet didn't solve the issue. The same error is returned when tests are run.
![image](https://user-images.githubusercontent.com/12195214/175073905-8b5c5cdd-ef1b-4625-b6f0-2d29634334ce.png)
![image](https://user-images.githubusercontent.com/12195214/175074014-a0786f90-9b0f-492e-9c5c-ac872fc4ff49.png)

**Comment by timheuer** [comment]
@pmatuszewski is this a public repo? I think I'll need more info to see what's going on here -- the Desktop aspect is probably the cause here but I don't know why.  My .NET 5 projects are running/testing fine: https://github.com/timheuer/ClassLibrary2/runs/7007951826?check_suite_focus=true -- so I'm not sure what the diff is here (in mine using windows-2019 runner image, and both projects target net5.0)

**Comment by al-cheb** [comment]
@pmatuszewski, Any updates?

**Comment by al-cheb** [comment]
I am planning to close the thread. If you have any concerns feel free to open it.

**Comment by reegeek** [comment]
Hi,
I have the same error.

The issue is that we cannot run net50 **x86** test with the latest image.

On my project:
this [run](https://github.com/reegeek/StructLinq/actions/runs/3181478586/jobs/5186282072) worked with image version 20220925.1
And not working on this [run](https://github.com/reegeek/StructLinq/actions/runs/3441318752/jobs/5740724005) with image version 20221027.1

**Comment by reegeek** [comment]
In fact, when a runtime is integrate to a image, x64 and x86 version are installed.

With dotnet-setup you cannot specify x86.
actions/setup-dotnet#72
