### ISSUE TITLE
LLVM 14 linker error (lld-link: error: ignoring unknown debug$S subsection kind 0xFF in file libucrt.lib)

### ISSUE THREAD

**Issue by thbusch** [actions/virtual-environments#5813]
### Description

Since the latest update lld from LLVM-14.0.4-win64 produces a bunch of errors which seem related to the latest Windows SDK

`lld-link: error: ignoring unknown debug$S subsection kind 0xFF in file libucrt.lib(initialization.obj)
lld-link: error: ignoring unknown debug$S subsection kind 0xFF in file libucrt.lib(initialization.obj)
lld-link: error: ignoring unknown debug$S subsection kind 0xFF in file libucrt.lib(_file.obj)
etc...
`

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20220619.1

### Is it regression?

20220614.0

### Expected behavior

no linker errors

### Actual behavior

`lld-link: error: ignoring unknown debug$S subsection kind 0xFF in file libucrt.lib(initialization.obj)
lld-link: error: ignoring unknown debug$S subsection kind 0xFF in file libucrt.lib(initialization.obj)
lld-link: error: ignoring unknown debug$S subsection kind 0xFF in file libucrt.lib(_file.obj)
etc...
`

### Repro steps

build binary with 
`"clang\bin\LLVM-14.0.4-win64\bin\clang.exe" -DMKLANG_EXPORTS -std=c99 --target=x86_64-pc-windows-msvc -fuse-ld=lld -Wno-cast-align -fcomment-block-commands=retval -ferror-limit=200 -fmessage-length=0 -fno-short-enums -ffunction-sections -fdata-sections -DWIN32 -D_WINDLL -Wno-everything -g -gdwarf-4 -O0 -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=undefined,float-divide-by-zero,unsigned-integer-overflow,implicit-conversion,local-bounds -Wl,/ignore:longsections,/WX,/wholearchive input.c -o output.exe`

**Comment by al-cheb** [comment]
Hello @thbusch.
Could you share a minimal repo how to reproduce the issue?

**Comment by FrancescElies** [comment]
@al-cheb Hi 👋

On our side providing a reprex is always quite a big effort, we have a pretty complex setup.

What we can confirm though is that for the same commit we have different results since Wednesday 22 June, the following links are froma private repo:
- This was [green](https://mbbm-ast.visualstudio.com/AST/_build/results?buildId=87490&view=results), Environment: windows-2022 Version: 20220614.0
- This is now [red](https://mbbm-ast.visualstudio.com/AST/_build/results?buildId=87732&view=results), Environment: windows-2022 Version: 20220619.1

In the new image came windows sdk 10.0.22621.0, in both builds we are doing stuff with llvm 14 asan & ubsan, we are unsure if the issue is on llvm or the new windows sdk. But one thing is clear, same commit different out from CI.

**Comment by FrancescElies** [comment]
@al-cheb we realized the following, we still one clang job successfully running on the new image but the other jobs started failing as we posted previously.

The jobs that failing use the flag `-g -gdwarf-4 -O0` the one which is successful don't so I guess there is something going on with those flags and windows sdk `10.0.22621.0`.

Is there a place we can post this issue for the new windows sdk?

As a workaround we will switching back to the old win-sdk.

Thanks for your help.

**Comment by al-cheb** [comment]
@FrancescElies, I think you could use - https://developercommunity.visualstudio.com/report?space=8&entry=problem

**Comment by FrancescElies** [comment]
@al-cheb It looks like this error is actually a warning (our linking step is a bit strict), we will proceed to ignore that warning.

In the meanwhile here a min reprex.

`example.c`
```c
int main(void) {
  return 1;
}
```

In a powershell execute, this steps will work `10.0.19041.0` for but fail for `10.0.22621.0`:
```powershell
# https://stackoverflow.com/questions/41399692/running-a-build-script-after-calling-vcvarsall-bat-from-powershell
function Invoke-CmdScript {
  param(
    [String] $scriptName
  )
  $cmdLine = """$scriptName"" $args && set"
  & $Env:SystemRoot\system32\cmd.exe /c $cmdLine |
  select-string '^([^=]*)=(.*)$' | foreach-object {
    $varName = $_.Matches[0].Groups[1].Value
    $varValue = $_.Matches[0].Groups[2].Value
    set-item Env:$varName $varValue
  }
}


Invoke-CmdScript "c:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/Build/vcvarsall.bat" x64 10.0.22621.0
# If you change the version to `10.0.19041.0` the following command will work
clang  -std=c99 --target=x86_64-pc-windows-msvc -fuse-ld=lld    -g -gdwarf-4 -O0  "-Wl,/WX"    example.c

```

The problem seems to be the combination of `lld` (if not using the lld linker but the msvc one is fine), `-g -gdwarf-4` and `-Wl,/WX` (making the linker complain about warnings) and winsdk `10.0.22621.0`.

### Questions
- Do you know a better way of doing visual studio stuff on powershell, quite often I end up having to google _how do I do Visual studio stuff in powershell_? This time I ended up with this `Invoke-CmdScript `

- Is there a task to easily select the desired windows sdk in azure devops? I searched but could not find it.

- Probably after this we should probably close the issue as it's only a problem of what is the default win-sdk, it would be great though to have a similar way like in python to select the desired win-sdk

**Comment by FrancescElies** [comment]
Hi @al-cheb,

We tested our llvm asan job pinning the win-sdk it uses in the following constellation:

| vm-image     | win-sdk      | result                                                                                                 |
|:-------------|:-------------|:-------------------------------------------------------------------------------------------------------|
| windows-2019 | 10.0.14393.0 | ✅                                                                                                     |
| windows-2019 | 10.0.16299.0 | ✅                                                                                                     |
| windows-2019 | 10.0.17134.0 | ✅                                                                                                     |
| windows-2019 | 10.0.17763.0 | ✅                                                                                                     |
| windows-2019 | 10.0.18362.0 | ✅                                                                                                     |
| windows-2019 | 10.0.19041.0 | ✅                                                                                                     |
| windows-2019 | 10.0.20348.0 | ✅                                                                                                     |
| windows-2019 | 10.0.22000.0 | ✅                                                                                                     |
| windows-2022 | 10.0.17763.0 | lld-link: error: /INFERASANLIBS is not allowed in .drectve                                             |
| windows-2022 | 10.0.19041.0 | lld-link: error: /INFERASANLIBS is not allowed in .drectve                                             |
| windows-2022 | 10.0.20348.0 | lld-link: error: /INFERASANLIBS is not allowed in .drectve                                             |
| windows-2022 | 10.0.22000.0 | lld-link: error: /INFERASANLIBS is not allowed in .drectve                                             |
| windows-2022 | 10.0.22621.0 | lld-link: error: ignoring unknown debug$S subsection kind 0xFF in file libucrt.lib(initialization.obj) |

As you can see in `windows-2019` we could build with any  win-sdk version, but it seems like `windows-2022` for the same sdk `10.0.20348.0` (which is available in both) the library is trying to link differs and lld-link is not happy about it.

**Comment by al-cheb** [comment]
@FrancescElies, Thank you to raise this issue. We are planning to close the thread as external.
