### ISSUE TITLE
[all OSs] Android ndk-bundle along with old NDK versions will be deprecated on July, 24

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#5879]
### Breaking changes

- Symlink from LTS NDK to `ndk-bundle` won't be created anymore.
- NDK version from 15 to 18 will be removed from macOS-10.15 image.

### Target date

The propagation will start on July, 24 and take 2-3 days.

### The motivation for the changes

- `ndk-bundle` was explicitly marked as "Obsolete" by Google and no one should be using it anymore. The current symlink creation process breaks the Android SDK package manager. More details can be found here https://github.com/actions/virtual-environments/issues/2689#issuecomment-1172129050
- Old ndk versions 15-18 are not needed by xamarin-android anymore and can be deleted.

### Possible impact

If your builds depend on the `ndk-bundle` symlink they can be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

The symlink can be created using the following snippets:
- macOS:
```bash
function get_full_ndk_version {
    majorVersion=$1
    ndkVersion=$(${SDKMANAGER} --list | grep "ndk;${majorVersion}.*" | awk '{gsub("ndk;", ""); print $1}' | sort -V | tail -n1)
    echo "$ndkVersion"
}
ANDROID_HOME=$HOME/Library/Android/sdk
SDKMANAGER=$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager
ndkDefault=$(get_full_ndk_version "23")
ln -s $ANDROID_HOME/ndk/$ndkDefault $ANDROID_HOME/ndk-bundle
```
- Ubuntu:
```bash
function get_full_ndk_version {
    majorVersion=$1
    ndkFullVersion=$($SDKMANAGER --list | grep "ndk;${majorVersion}.*" | awk '{gsub("ndk;", ""); print $1}' | sort -V | tail -n1)
    echo "$ndkFullVersion"
}
ANDROID_ROOT=/usr/local/lib/android
ANDROID_SDK_ROOT=${ANDROID_ROOT}/sdk
ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk-bundle
SDKMANAGER=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager
ndkDefaultFullVersion=$(get_full_ndk_version "23")
ln -sf $ANDROID_SDK_ROOT/ndk/$ndkDefaultFullVersion $ANDROID_NDK_ROOT
```
- Windows:
```pwsh
$sdkRoot = "C:\Android\android-sdk"
$sdkManager = "$sdkRoot\cmdline-tools\latest\bin\sdkmanager.bat"
$androidPackages = Get-AndroidPackages -AndroidSDKManagerPath $sdkManager
$ndkDefaultVersion = ($androidPackages | Where-Object { $_ -match "ndk;23" }).Split(';')[1]
$ndkRoot = "$sdkRoot\ndk-bundle"
New-Item -Path $ndkRoot -ItemType SymbolicLink -Value "$sdkRoot\ndk\$ndkDefaultVersion"
setx ANDROID_NDK_HOME $ndkRoot /M
setx ANDROID_NDK_PATH $ndkRoot /M
setx ANDROID_NDK_ROOT $ndkRoot /M
(Get-Content -Encoding UTF8 "${ndkRoot}\ndk-build.cmd").replace('%~dp0\build\ndk-build.cmd','"%~dp0\build\ndk-build.cmd"')|Set-Content -Encoding UTF8 "${ndkRoot}\ndk-build.cmd"
```

**Comment by rexingQ** [comment]
Pop

**Comment by jonasflynn66** [comment]
> ### Breaking changes
> * Symlink from LTS NDK to `ndk-bundle` won't be created anymore.
> * NDK version from 15 to 18 will be removed from macOS-10.15 image.
> 
> ### Target date
> The propagation will start on July, 24 and take 2-3 days.
> 
> ### The motivation for the changes
> * `ndk-bundle` was explicitly marked as "Obsolete" by Google and no one should be using it anymore. The current symlink creation process breaks the Android SDK package manager. More details can be found here [side-by-side NDK installed as the "(obsolete)" NDK #2689 (comment)](https://github.com/actions/virtual-environments/issues/2689#issuecomment-1172129050)
> * Old ndk versions 15-18 are not needed by xamarin-android anymore and can be deleted.
> 
> ### Possible impact
> If your builds depend on the `ndk-bundle` symlink they can be broken.
> 
> ### Platforms affected
> * [x]  Azure DevOps
> * [x]  GitHub Actions
> 
> ### Virtual environments affected
> * [x]  Ubuntu 18.04
> * [x]  Ubuntu 20.04
> * [x]  Ubuntu 22.04
> * [x]  macOS 10.15
> * [x]  macOS 11
> * [x]  macOS 12
> * [x]  Windows Server 2019
> * [x]  Windows Server 2022
> 
> ### Mitigation ways
> The symlink can be created using the following snippets:
> 
> * macOS:
> 
> ```shell
> function get_full_ndk_version {
>     majorVersion=$1
>     ndkVersion=$(${SDKMANAGER} --list | grep "ndk;${majorVersion}.*" | awk '{gsub("ndk;", ""); print $1}' | sort -V | tail -n1)
>     echo "$ndkVersion"
> }
> ANDROID_HOME=$HOME/Library/Android/sdk
> SDKMANAGER=$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager
> ndkDefault=$(get_full_ndk_version "23")
> ln -s $ANDROID_HOME/ndk/$ndkDefault $ANDROID_HOME/ndk-bundle
> ```
> 
> * Ubuntu:
> 
> ```shell
> function get_full_ndk_version {
>     majorVersion=$1
>     ndkFullVersion=$($SDKMANAGER --list | grep "ndk;${majorVersion}.*" | awk '{gsub("ndk;", ""); print $1}' | sort -V | tail -n1)
>     echo "$ndkFullVersion"
> }
> ANDROID_ROOT=/usr/local/lib/android
> ANDROID_SDK_ROOT=${ANDROID_ROOT}/sdk
> ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk-bundle
> SDKMANAGER=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager
> ndkDefaultFullVersion=$(get_full_ndk_version "23")
> ln -sf $ANDROID_SDK_ROOT/ndk/$ndkDefaultFullVersion $ANDROID_NDK_ROOT
> ```
> 
> * Windows:
> 
> ```powershell
> $sdkRoot = "C:\Android\android-sdk"
> $sdkManager = "$sdkRoot\cmdline-tools\latest\bin\sdkmanager.bat"
> $androidPackages = Get-AndroidPackages -AndroidSDKManagerPath $sdkManager
> $ndkDefaultVersion = ($androidPackages | Where-Object { $_ -match "ndk;23" }).Split(';')[1]
> $ndkRoot = "$sdkRoot\ndk-bundle"
> New-Item -Path $ndkRoot -ItemType SymbolicLink -Value "$sdkRoot\ndk\$ndkDefaultVersion"
> setx ANDROID_NDK_HOME $ndkRoot /M
> setx ANDROID_NDK_PATH $ndkRoot /M
> setx ANDROID_NDK_ROOT $ndkRoot /M
> (Get-Content -Encoding UTF8 "${ndkRoot}\ndk-build.cmd").replace('%~dp0\build\ndk-build.cmd','"%~dp0\build\ndk-build.cmd"')|Set-Content -Encoding UTF8 "${ndkRoot}\ndk-build.cmd"
> ```

NAWS ALL GOOD ARR ALL

**Comment by MarijnS95** [comment]
@miketimofeev Repeating what I asked in https://github.com/actions/virtual-environments/issues/2689#issuecomment-1195127579, this issue seems to be about removing the `ndk-bundle` symlink (which was breaking sdkmanager), but couldn't you have kept something along the lines of:

```sh
export ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/$ndkDefaultFullVersion
```

Without creating a symlink at all, so that most software requiring just the "default" (latest LTS, afaiu) NDK would keep working?

I have a couple repositories failing because of this, and I think you could've stored the result of the suggested workaround in a much-more-easily accessible `ANDROID_NDK_DEFAULT_HOME=$ANDROID_SDK_ROOT/ndk/$ndkDefaultFullVersion` otherwise? For now I'm addressing this by just pointing my CI's to the latest:

```yaml
    - name: Setup NDK path
      shell: bash
      run: echo "ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV
```

**Comment by miketimofeev** [comment]
Hey @MarijnS95! Sorry for the inconvenience but I assume the variable is related only to ndk_bundle, which is obsolete now, isn't it?

**Comment by MarijnS95** [comment]
@miketimofeev I've always understood `ANDROID_NDK_HOME` and `ANDROID_NDK_ROOT` to point to the NDK the user wants to use, regardless whether that's `ndk-bundle` or another version downloaded/extracted elsewhere. That's also how our Rust tools (`cargo-apk`, `cargo-ndk`, etc) treat these variables.

**Comment by MarijnS95** [comment]
@miketimofeev I wouldn't expect anything in the SDK something, but it should have been in the NDK-specific build-system docs where it turns out not to be... https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md

At least https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-android:~:text=Else%2C%20if%20an%20environment%20variable%20ANDROID_NDK_ROOT%20or%20ANDROID_NDK%20is%20set%2C%20it%20will%20be%20used%20as%20the%20value%20of%20CMAKE_ANDROID_NDK%2C%20and%20the%20NDK%20will%20be%20used mentions it, and there are probably other places where we can find it being used. Android Studio manages it internally so it's really only for external tools that wish to utilize the NDK in a consistent/configurable manner.

**Comment by miketimofeev** [comment]
@saurik could you provide your thoughts regarding the env variables too?

**Comment by ThadHouse** [comment]
This is breaking any android build that builds openssl. It looks for ANDROID_NDK or ANDROID_NDK_ROOT, both of which are now no longer defined. Many builds were dependent on those variables, and at least the variables is something that should be looked at bringing back.

https://github.com/openssl/openssl/blob/master/Configurations/15-android.conf#L27

**Comment by miketimofeev** [comment]
@ThadHouse @MarijnS95 thanks for all the examples, I'll get those variables back and point them to the latest LTS NDK (25 for now)

**Comment by MarijnS95** [comment]
@miketimofeev Thanks! I've meanwhile been asking around for explicit docs on this for the NDK, given that it only exists for the SDK. Hopefully that'll help clarify even further once they arrive :)

**Comment by miketimofeev** [comment]
@ThadHouse @MarijnS95 we have added three variables that point to the latest LTS NDK (25 at the moment) to all the images:
`'ANDROID_NDK', 'ANDROID_NDK_HOME', 'ANDROID_NDK_ROOT'`
Sorry for the inconvenience and please let me know if there is anything else left.
Thank you!

**Comment by saurik** [comment]
> @saurik could you provide your thoughts regarding the env variables too?

I took a _glorious_ half-year break from paying attention to my GitHub inbox, but a friend of mine came across this threads and told me a few days ago that I'd been asked a question about it--which I didn't reply to--and then "they did something random" ;P.

FWIW, what you did is exactly what I would have recommended--including awkwardly having to set all three of those variables, as even Google was inconsistent with their various projects over the years and have caused us lots of confusion--so that's great! :D

The only thing I'm left wondering about is what the intended purpose of `ANDROID_NDK_LATEST_HOME` is (mostly as its existence seemed to confuse my friend even further as it simply _looked cooler_ than the handful of variables everyone else uses; lol).
