### ISSUE TITLE
Unable to install PHP 5.6 and 7.0 on ubuntu-latest

### ISSUE THREAD

**Issue by shivammathur** [actions/virtual-environments#592]
**Describe the bug**
Broken packages in ubuntu.
https://github.com/shivammathur/test-setup-php/runs/521860276?check_suite_focus=true#step:3:47

**Area for Triage**: Packages, PHP

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Installing php 5.6 and php 7.0 should work without errors.
```
sudo apt-get install php5.6
sudo apt-get install php7.0
```

**Actual behavior**
There are broken packages which break the installation.
https://github.com/shivammathur/test-setup-php/runs/521860276?check_suite_focus=true#step:3:47

**Notes**
- PHP 5.6 and 7.0 are installed on ubuntu-16.04, but that image also has broken packages.
- Adding a `sudo apt-get update` step fixes the issue, but it should work without it.
- In `apt-get update` step `heroku` list gives an error - https://github.com/shivammathur/test-setup-php/runs/521878018?check_suite_focus=true#step:3:52

**Comment by johnterickson** [comment]
@alepauly this looks like apt isn’t configured with the right keys

**Comment by alepauly** [comment]
thanks @johnterickson, we'll look into it.

**Comment by al-cheb** [comment]
Hello, @shivammathur 

It's not a bug. This behavior is by design for Ubuntu when packages are missing in repo. If Ubuntu  issues a new version of a given package, then the old version will no longer be available. Attempting to install it will cause the errors you're seeing. Re-running `sudo apt-get update` before your install will clear up the problem. 

```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2-bin_2.4.29-1ubuntu4.12_amd64.deb  404  Not Found [IP: 52.177.174.250 80]
Fetched 3649 kB in 3s (1129 kB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2-utils_2.4.29-1ubuntu4.12_amd64.deb  404  Not Found [IP: 52.177.174.250 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2-data_2.4.29-1ubuntu4.12_all.deb  404  Not Found [IP: 52.177.174.250 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2_2.4.29-1ubuntu4.12_amd64.deb  404  Not Found [IP: 52.177.174.250 80]
```

http://azure.archive.ubuntu.com/ubuntu/pool/main/a/apache2/:
|Old Package Version| New Package Version | Update date|
|-------------|----------------|--------------|
|apache2-bin_2.4.29-1ubuntu4.12_amd64.deb | apache2-bin_2.4.29-1ubuntu4.13_amd64.deb | 2020-03-18 14:08 | 
|apache2-utils_2.4.29-1ubuntu4.12_amd64.deb| apache2-utils_2.4.29-1ubuntu4.13_amd64.deb | 2020-03-18 14:08 | 
|apache2-data_2.4.29-1ubuntu4.12_all.deb | apache2-data_2.4.29-1ubuntu4.13_all.deb | 2020-03-18 14:08 | 
|apache2_2.4.29-1ubuntu4.12_amd64.deb| apache2_2.4.29-1ubuntu4.13_amd64.deb | 2020-03-18 14:08 |

**Comment by shivammathur** [comment]
@al-cheb shouldn't the ubuntu images have updated package information... as in there should be scheduled task to do this.
In my opinion if possible apt-get install ... should work out of the box without update.

**Comment by al-cheb** [comment]
@shivammathur, We update package cache once after build generation process  is done(for example the last update was `ubuntu18:20200316` -  https://github.com/actions/virtual-environments/blob/releases/ubuntu18/20200316/images/linux/Ubuntu1804-README.md). We can't use scheduled task to update local cache every time because the consistence of image will be always changed. In that case you should always use `apt-get update` to have obtain latest changes.
