### ISSUE TITLE
Update Java to latest LTS version (Java 11) across all images

### ISSUE THREAD

**Issue by brunoborges** [actions/virtual-environments#595]
As mentioned in #405, it is imperative that all images have the same Java LTS version set as default to avoid complexity in cross-platform build workflows.

Java 11.0.7 is the latest LTS release.

**Comment by alepauly** [comment]
Since switching to latest LTS as default is a breaking change for many workflows and builds we won't do it until we have support and adoption from the ecosystem (e.g. `setup-java`) and can minimize disruption to existing builds. The work to improve `setup-java` is in transit, so I'll leave this open until we can get back to it.

**Comment by DiederickA** [comment]
As stated above 'switching to latest LTS as default is a breaking change' it won't happen till setup-java feature is further developed. At the same time in our organization users start requesting newer Java versions (13, 14). Therefore, we would like to see these versions to be included as well (across the three platforms). Does that also wait for the setup-java feature? As this wait is yet unknown, these versions should be made available.

**Comment by maxim-lobanov** [comment]
@DiederickA , We wouldn't like to pre-cache non-LTS versions (13, 14) on image. But they can be installed via `actions/setup-java` right now. 
```
- name: Set up JDK 14
  uses: actions/setup-java@v1
  with:
    java-version: 14

```

**Comment by DiederickA** [comment]
Is that action setup-java also available in Azure DevOps, or is it only a GitHUB action??

**Comment by maxim-lobanov** [comment]
@DiederickA , For Azure DevOps, there is a separate action [Java Tool Installer task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops) with absolutely same functionality

**Comment by maxim-lobanov** [comment]
Hello @brunoborges , thank you for your proposal. Just an update for visibility:
Per internal discussion, we wouldn't like to change default Java on existing images due to unpredictable customers impact.
We are going to setup Java 11 (LTS) as default on all new images since it won't introduce breaking changes for customers.
Just an example, `ubuntu-20.04` (aka `ubuntu-latest`) has Java 11 as default. We will follow this approach for all future images.

**Comment by brunoborges** [comment]
That's excellent news, thanks @maxim-lobanov !
