### ISSUE TITLE
Jest on windows-latest has exit code 1 with passing tests

### ISSUE THREAD

**Issue by Deseteral** [actions/virtual-environments#606]
**Describe the bug**
When running Jest (node.js test runner) in Actions CI on `windows-latest` tests will pass, but Jest will have exit code 1 causing build to fail. This only happens on `windows-latest`, when running in `windows-2016` tests will pass with correct exit code (this is also the case for other platforms such as Mac and Linux).

I've already submitted this issue to Jest, and @thejoebourneidentity suggested to submit the issue here.
Original issue: https://github.com/facebook/jest/issues/9413

**Area for Triage**: 
Area: JavaScript and Node.js

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
When running Jest with passing tests on `windows-latest` Jest's exit code should be 0.

**Actual behavior**
Run the CI in example repo: https://github.com/Deseteral/jest-gh-actions-issue

**Comment by maxim-lobanov** [comment]
Hello! Thank you for report.
It looks like the issue comes from PowerShell.
```
- name: npm test
   run: npm test 
```
This code uses different shell on different platforms. On Ubuntu and macOS, `bash` is used. On Windows, `Powershell` is used.

If you change this step a bit:
```
- name: npm test
  shell: cmd
  run: npm test 
```
It will start to pass on Windows but this code won't work on Ubuntu / macOS because they don't support cmd :)

We will look deeper to issue with PS.

**Comment by maxim-lobanov** [comment]
Hello @Deseteral ,
Could you please rerun your pipeline one more time and share link to the fresh repro?
I am asking because I have forked your repository, trigger the CI and it passed without any errors:
https://github.com/maxim-lobanov/jest-gh-actions-issue/runs/527988969?check_suite_focus=true

Please let me know if I missed something

**Comment by Deseteral** [comment]
Oh well, looks like the problem is fixed. This was happening in January and I thought that this is still the case. I should've checked before submitting this issue. Sorry for wasting for time :/

**Comment by maxim-lobanov** [comment]
Thank you for response.
My guess was that it could be related to PS (bash is default shell for Ubuntu and macOS, but PS is default shell for Windows images) but I didn't have a chance to reproduce it.

Feel free to ping me and reopen if you see this issue again
