### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by Garima-msft** [actions/virtual-environments#611]
**Tool information**
- Tool name: Az (PowerShell Module)
- Add or update? update
- Desired version: 3.4.0
- Approximate size: 
- If this is an add request:
  - Brief description of tool: AzSK tool requires Az dependency modules installed
  - URL for tool's homepage: https://github.com/azsk/DevOpsKit

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- Windows Server 2016 R2
- Windows Server 2019

**Can this tool be installed during the build?**
Install-Module Az -Repository PSGallery -RequiredVersion '3.4.0'

**Are you willing to submit a PR?**

**Comment by al-cheb** [comment]
Hello, @Garima-msft 
We already have preinstalled `Az 3.5.0` PowerShell module  on Windows Server 2016 and 2019 images.

Windows Server 2019 - https://github.com/actions/virtual-environments/blob/releases/win19/20200319/images/win/Windows2019-Readme.md
`This version is saved but not installed Location: C:\Modules\az_3.5.0\Az\3.5.0\Az.psd1`

Windows Server 2016 - https://github.com/actions/virtual-environments/blob/releases/win16/20200316/images/win/Windows2016-Readme.md
`This version is saved but not installed Location: C:\Modules\az_3.5.0\Az\3.5.0\Az.psd1`

**Comment by al-cheb** [comment]
Hello, @Garima-msft
This behavior is expected that we couldn't  pre-install all desired Az PowerShell module versions on images related due to significantly increase image size, building time, etc.

1. Can we remove old versions?
No. This can break existing customers who has written there scripts based on the old AzurePS commands and using that specific version in the task.

2. Can we change default versions?
There are breaking changes between V2.1.0 and V5.13.0, V6.13.1. There are many third party custom tasks that may have taken dependency on V2.1.0 which will break if we change the default version.

Feel free to open thread if you have any concerns.
