### ISSUE TITLE
Include the moby-buildx package on Linux

### ISSUE THREAD

**Issue by chrispat** [actions/virtual-environments#690]
We need to include the moby-buildx packages when we install moby and the related container tools in the linux images.

**Virtual environments affected**
- [ ] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by moikot** [comment]
Ubuntu 18.04 has a very old version of Docker. Would it be possible to update it?

**Comment by maxim-lobanov** [comment]
Hello @moikot ,
We [install moby-docker](https://github.com/actions/virtual-environments/blob/master/images/linux/scripts/installers/docker-moby.sh#L18) on Ubuntu images (original Docker can't be pre-installed on images due to license agreement).
Currently, Ubuntu images contain moby-docker v19.03.8 and it is the [latest available version](https://github.com/moby/moby/releases).

**Comment by moikot** [comment]
Hello @maxim-lobanov 
I'm not sure if I understand you correctly, but Ubuntu [18.04 specification says](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md):
"Docker-Moby (Docker version 3.0.11+azure, build eb310fca49568dccd87c6136f774ef6fff2a1b51)"
I've run `docker version` command and indeed it was 3.0.11. 

An excerpt from my pipeline logs:
```
Pool: Azure Pipelines
Image: ubuntu-18.04
Agent: Hosted Agent

2020-04-19T14:57:12.5598554Z Client:
2020-04-19T14:57:12.5603744Z  Version:           3.0.11+azure
2020-04-19T14:57:12.5605622Z  API version:       1.40
2020-04-19T14:57:12.5607457Z  Go version:        go1.12.17
2020-04-19T14:57:12.5616640Z  Git commit:        eb310fca49568dccd87c6136f774ef6fff2a1b51
2020-04-19T14:57:12.5618420Z  Built:             Tue Mar  3 21:59:52 2020
2020-04-19T14:57:12.5619832Z  OS/Arch:           linux/amd64
2020-04-19T14:57:12.5647345Z  Experimental:      false
2020-04-19T14:57:12.5648840Z 
2020-04-19T14:57:12.5650108Z Server:
2020-04-19T14:57:12.5651257Z  Engine:
2020-04-19T14:57:12.5652319Z   Version:          3.0.11+azure
2020-04-19T14:57:12.5654338Z   API version:      1.40 (minimum version 1.12)
2020-04-19T14:57:12.5655500Z   Go version:       go1.12.17
2020-04-19T14:57:12.5656551Z   Git commit:       aa6a9891b0
2020-04-19T14:57:12.5657482Z   Built:            Tue Mar 10 18:53:36 2020
2020-04-19T14:57:12.5658487Z   OS/Arch:          linux/amd64
2020-04-19T14:57:12.5659432Z   Experimental:     false
2020-04-19T14:57:12.5660304Z  containerd:
2020-04-19T14:57:12.5661188Z   Version:          v1.2.13
2020-04-19T14:57:12.5662255Z   GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
2020-04-19T14:57:12.5663229Z  runc:
2020-04-19T14:57:12.5664883Z   Version:          1.0.0-rc10
2020-04-19T14:57:12.5665545Z   GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
2020-04-19T14:57:12.5666251Z  docker-init:
2020-04-19T14:57:12.5666657Z   Version:          0.18.0
2020-04-19T14:57:12.5667109Z   GitCommit:        fec3683
``

**Comment by maxim-lobanov** [comment]
@moikot , sorry for confusion. I have got a bit more details and will try to clarify:
Official version of Docker can't be pre-installed on images because of EULA.

From https://github.community/t5/GitHub-Actions/What-really-is-docker-3-0-6/m-p/30767/highlight/true#M552
> we are running a fork of the github.com/moby/moby project we build and distribute and is licensed by Microsoft for use on services running on Azure

Currently, the latest available version `moby-engine_3.0.11+azure-2_amd64.deb ` ([Link](https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/m/moby-engine/)).

I will sync with team to clarify if we can build new package with latest version of Docker (3.2.6).
But I think we need the separate issue to track your request because the current one is about buildx adding and it is almost finished. Could you please create it?

**Comment by moikot** [comment]
@maxim-lobanov I didn't think that it's a common practice on GitHub to retroactively edit comments so that the subsequential commenters look like fools repeating basically the same sentences.

If Microsoft thinks it's a good idea to have versioning schema for their custom docker packages different from the official ones, I have to say it's super confusing, but I don't want to spend my time on this nonsense anymore.

**Comment by maxim-lobanov** [comment]
@moikot , I changed initial comment because it could be a bit confusing for other customers (who are out of context) due to inconsistent version approach. Sorry for inconvenience.

I have clarified this question with the team who owns moby docker used by our images:
They build the moby binaries from own mirror of upstream moby and currently, the releases maintained by own release tag (3.0.11+azure the latest version). That release contains exactly the same set of commits as the upstream moby/moby 19.03.8 so you can be sure that the latest docker version is available on image. They have a plan to fix release naming approach to be consistent with official releases in future versions so it should fixed with next release.

Thank you for hands up of this issue

**Comment by andy-mishechkin** [comment]
Hello!
Moby-buildx has been added to Ubuntu 16/18 images, and has been tested.
Now we are waiting the deployment of these images with moby-buildx.
If you'll detect some issues with moby-buildx working - please inform us about it

**Comment by psftw** [comment]
How can I call buildx? With Docker CE it is built-in as a subcommand, but this ("docker buildx") doesn't seem to work in Actions.

https://github.com/actions/virtual-environments/blob/master/images/linux/scripts/installers/docker-moby.sh#L30 :thinking:

**Comment by maxim-lobanov** [comment]
Hello @psftw , we have a delay with delivering new image because of the a few issues.
We are expecting new image is available on Tue next week. After that command `docker buildx` should work

**Comment by andy-mishechkin** [comment]
Docker buildx has been tested on the last Ubuntu image - all works correct.
I think, we can close this issue

**Comment by crazy-max** [comment]
@psftw In the meantime you can use https://github.com/crazy-max/ghaction-docker-buildx

**Comment by crazy-max** [comment]
Would it be possible to support more platforms?

![image](https://user-images.githubusercontent.com/1951866/83818031-ce615c80-a6b5-11ea-9aa1-48507c897b98.png)

Like [ghaction-docker-buildx](https://github.com/crazy-max/ghaction-docker-buildx)?

![image](https://user-images.githubusercontent.com/1951866/83818083-f224a280-a6b5-11ea-83ec-3e390fdb4a6d.png)

**Comment by miketimofeev** [comment]
@crazy-max could you please create a separate issue for adding the platforms?
