### ISSUE TITLE
Breaking change notifications are needed

### ISSUE THREAD

**Issue by tusharb86** [actions/virtual-environments#719]
**Describe the bug**
In the latest release of the Ubuntu image (from 20200315.1 to 20200330.1), the location of the Android "sdkmanager" tool changed without any notification to consumers of these images.

**Area for Triage**: Android, Deployment/Release

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
The Android sdkmanager tool was previously located at `/usr/local/lib/android/tools/bin/sdkmanager`.

**Actual behavior**
The Android sdkmanager tool moved to a new location at `/usr/local/lib/android/*sdk*/tools/bin/sdkmanager` without any sort of communication or notification to users of the build images (specifically Azure Pipelines customers).

There needs to be a mechanism to inform customers of these images that a new version was deployed, at the very least. Additionally, it would be great to know about breaking changes like this. The links on the homepage to follow along are for the general GitHub project, not virtual-environments. Maybe those need to be updated?

See https://github.com/actions/virtual-environments
> High Impact Changes (ex. breaking changes, new or deprecated environments) will be posted to the GitHub Changelog on our [blog](https://github.blog/changelog/) and on [twitter](https://twitter.com/GHchangelog).

**Comment by maxim-lobanov** [comment]
Hello @tusharb86 ,
Thank you for bringing this up.
We have reworked `sdkmanager` path in scope of #539 . Previously, it was installed to non-default location and this change moves it to the correct one. This change was not announced because we didn't think that people depend on absolute path to `sdkmanager`. So we didn't consider it as a breaking change. But it was.

Sorry for inconvenience and breaking your build. Usually, we use the following channels to inform about breaking changes:
- [GitHub blog](https://github.blog/changelog/) for significant breaking changes.
- [Pinned issues in virtual-environments](https://github.com/actions/virtual-environments/issues) for small changes like [example](https://github.com/actions/virtual-environments/issues/319).

Please let us know if you have any issues with build pipeline right now, so we can help you.

**Comment by maxim-lobanov** [comment]
I am closing this issue for now because there is no action items here.
Again, thank you for hands up about the issue. We will keep it on mind and will notify about all potential breaking changes using the channels above.

Feel free to share any thought and ideas how this process can be improved.
