### ISSUE TITLE
Cannot link to Boost 1.72 on Windows

### ISSUE THREAD

**Issue by HenryAWE** [actions/virtual-environments#754]
**Describe the bug**
Some of the Boost 1.72 libraries cannot be opened when the linker wants to link against them.
Since I didn't change any of the CMakeLists.txt from the last successful build, I think it might be a bug of the virtual environment.

**Area for Triage**: C/C++

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
The libraries of Boost can be linked

**Actual behavior**
Linker reports that these libraries cannot be opened
[Detailed information](https://github.com/HenryAWE/SubterraneanRose/actions/runs/83746003)

**Comment by Darleev** [comment]
Hello @HenryAWE,
It seems you have faced the same issue as describe [here ](https://github.com/actions/virtual-environments/issues/749). Could you please try the same fix? 
We are looking forward to your reply.

**Comment by HenryAWE** [comment]
> Hello @HenryAWE,
> It seems you have faced the same issue as describe here . Could you please try the same fix?
> We are looking forward to your reply.

I don't think I'm facing a same issue like that. My situation is that the Boost can be found by the CMake and the codes which only depends on the header-only part of the Boost can be successfully compiled. But the libraries, such as `libboost_locale-vc142-mt-x64-1_72.lib` or `libboost_serialization-vc142-mt-x64-1_72.lib`, cannot be opened by linker.

**Comment by Darleev** [comment]
@HenryAWE, thank you for provided details. I'm checking the issue to figure out a root cause. 
We will keep you posted.

**Comment by Darleev** [comment]
@HenryAWE let me provide you with details of the investigation:
1. First of all, we have reproduced the issue on our side.
2. Tried to add some new variables to cmake command like BOOST_LIBRARYDIR, but with no luck.

3. Then, we turned on verbose logging and tried to perform cmake again. During cmake command we can see, that cl command executes to compile the code. After that, we tried to compile some sample code, with missed libraries to get real problem details. It was the issue: 

`LINK : fatal error LNK1104: cannot open file 'LIBCMT.lib'`

It means that LIBPATH variable is not defined, due to fact that BOOST_ROOT environment variable is absent.

**Solution:**

In order to fix the issue, we need to specify BOOST_ROOT variable right before build command.
```
#cmd
set BOOST_ROOT=%BOOST_ROOT_1_72_0%
$powershell
$env:BOOST_ROOT=$env:BOOST_ROOT_1_72_0
```

Please add this step to your workflow file, and let us know if anything else is required.
We are looking forward to your reply.

**Comment by HenryAWE** [comment]
Thanks,  it solved my problem.
