### ISSUE TITLE
Add ARM64 Windows environment

### ISSUE THREAD

**Issue by joaomoreno** [actions/virtual-environments#768]
**Feature**: Add Windows ARM64 as an environment

Hi there, are there any plans to support a hosted ARM64 environment? We're seeing quite some enthusiasm over here: https://github.com/microsoft/vscode/issues/33620

**Comment by alepauly** [comment]
Hi @joaomoreno, unfortunately not at this time. Adding extra environments currently affects overall capacity and how we can serve the existing environments. If that changes in the future we'll definitely consider it. Have you looked into setting up your own [self-hosted runner](https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners)?

**Comment by joaomoreno** [comment]
@alepauly Windows ARM64 doesn't seem to be a supported platform for self-hosted runners, or am I missing something?

**Comment by alepauly** [comment]
> @alepauly Windows ARM64 doesn't seem to be a supported platform for self-hosted runners, or am I missing something?

Hi @joaomoreno, you aren't missing anything, my bad. I wasn't looking at the Windows part of your request and was thinking the runner could run on ARM64 but that's not true on Windows. Until DotNet Core doesn't run there, we probably won't be able to support it.

**Comment by joaomoreno** [comment]
Relevant: https://github.com/dotnet/winforms/issues/2053#issuecomment-540269844

**Comment by dennisameling** [comment]
Just for the record, I just created a PR to add support for Windows ARM64 to GitHub Actions runners (self-hosted): https://github.com/actions/runner/pull/785

**Comment by jeremyd2019** [comment]
Sorry if posting to an old closed/wontfix issue is not appreciated vs opening a new one.  I was notified about this interesting Azure development:
https://azure.microsoft.com/en-us/blog/now-in-preview-azure-virtual-machines-with-ampere-altra-armbased-processors/

>The Dpsv5 and Epsv5 Azure VM-series feature the Ampere Altra Arm-based processor operating at up to 3.0GHz. The new VMs provide up to 64 vCPUs and include VM sizes with 2GiB, 4GiB, and 8GiB per vCPU memory configurations, up to 40 Gbps networking, and optional high-performance local SSD storage.
> The VMs currently in preview support Canonical Ubuntu Linux, CentOS, and Windows 11 Professional and Enterprise Edition on Arm.

If the reason GitHub hosted Windows on ARM VMs could not be offered was because Azure didn't have such a thing, it sounds like that's changing! :tada:

**Comment by panekj** [comment]
@jeremyd2019 it won't happen because Azure will not provide Windows Server on arm64, they only provide client OS which is Windows 11

**Comment by triplef** [comment]
@alepauly @erik-bershel would it be possible to get this ask re-evaluated please? 🙏

Windows on ARM has been gaining a lot of traction since the original post here in 2020, and much work has been put into tooling support for WoA since then. A lot of projects on GH are working on or already have WoA support and would like to build/test it with Actions (as shown by the list of linked tickets above).

I’m not sure if Actions runs on Azure but if so their WoA support is also generally available since last year:
https://azure.microsoft.com/en-us/blog/azure-virtual-machines-with-ampere-altra-arm-based-processors-generally-available/

**Comment by erik-bershel** [comment]
Hi @triplef!
Unfortunately, there are no such plans yet. I can say with confidence that we will definitely announce such changes.

**Comment by Xazax-hun** [comment]
With more parties entering the Arm64 PC CPU market (https://www.tomshardware.com/news/amd-and-nvidia-to-develop-arm-cpus-for-client-pcs-report), and this issue is blocking many projects from shipping Arm64 binaries on Windows, I'd expect the pressure to ship this feature to increase over time.

**Comment by EwoutH** [comment]
Could we reopen this issue? Even if not planned currently, it would be useful for users to voice their concerns, ideas and developments.

**Comment by EwoutH** [comment]
It seems that as Microsoft wants to compete with macOS and Chrome OS and it pushing Arm support quite heavily on Windows, there is a huge benefit in having CI pipelines running easily.

Arm–based processors have been available in Azure [since September 2022](https://azure.microsoft.com/en-us/blog/azure-virtual-machines-with-ampere-altra-arm-based-processors-generally-available/) and there is [extensive documentation](https://learn.microsoft.com/en-us/windows/arm/create-arm-vm) about it. Both energy efficiency and [performance per dollar](https://bell-sw.com/blog/application-cost-reduction-with-arm-servers/) is generally cheaper using Arm-servers, especially in applications that are as independent and thus scale as well as CI.

I don't understand what the hesitation is of adding Arm based Windows hosted runners - or at least why it can't be further discussed.

**Comment by panekj** [comment]
> or at least why it can't be further discussed.

You can discuss it, the issue is not locked.

> I don't understand what the hesitation is of adding Arm based Windows hosted runners

There is no hesitation, Azure (which is used as underlying platform for GitHub Actions) doesn't provide Windows Server on ARM64 (publicly) (yet).

**Comment by johnnyshields** [comment]
Hi, so the most recent Microsoft keynote event [made a big splash with the new Qualcomm Snapdragon Elite ARM processors](https://www.youtube.com/watch?v=4Z5VbcLnhBQ).

At the moment, tons of language support (.NET, Python, Ruby, etc.) is blocked for Windows ARM because there is **no Azure Windows ARM instance which we can run CI**.

**Microsoft owns Github.** Can someone get the left-hand to talk to the right-hand here (even if it Azure Windows ARM is just made internally available for Github Actions CI?)

**Comment by EwoutH** [comment]
Those Azure Cobalt 100 processors seems like excellent SoCs to host some CI runners on!
- [Announcing the preview of new Azure VMs based on the Azure Cobalt 100 processor](https://techcommunity.microsoft.com/t5/azure-compute-blog/announcing-the-preview-of-new-azure-vms-based-on-the-azure/ba-p/4146353)

**Comment by johnnyshields** [comment]
@alepauly how about re-opening this issue?

**Comment by dessant** [comment]
> https://techcommunity.microsoft.com/t5/azure-compute-blog/announcing-the-preview-of-new-azure-vms-based-on-the-azure/ba-p/4146353

>  GitHub Actions is now available for Windows and Linux on Arm in 2 flavors – [self-hosted runners](https://github.blog/changelog/2022-09-28-github-actions-self-hosted-runners-now-support-windows-arm-hardware/) that can be hosted on an Arm VM or Arm device, and [GitHub hosted runners](https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/) that is available in private beta with GA expected later this summer.

**Comment by johnnyshields** [comment]
@alepauly how may projects get access to Private Beta for Windows on ARM? Would be great if can be enabled for all projects linking to this issue.

**Comment by nulano** [comment]
> @alepauly how may projects get access to Private Beta for Windows on ARM? Would be great if can be enabled for all projects linking to this issue.

It seems to be explained here: https://resources.github.com/devops/accelerate-your-cicd-with-arm-and-gpu-runners-in-github-actions/

**Comment by johnnyshields** [comment]
@nulano strange that link is now broken…

Also saw this:
https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/

**Comment by nulano** [comment]
> @nulano strange that link is now broken. It also looks like it was for Linux ARM not Windows.
> 
> Also saw this: https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/

Yep, that's where I found the link. IIRC it was for both, but I'm not sure.

**Comment by jeremyd2019** [comment]
From https://github.com/msys2/msys2-docker/issues/2#issuecomment-2157568668:
> https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/
> 
> > GitHub is ecstatic to unveil ArmⓇ-based Linux and Windows runners for GitHub Actions are now in Public Beta. […] These runners are available to our customers on our GitHub Team and Enterprise Cloud plans. We expect to begin offering Arm runners for open source projects by the end of the year.
> 

🎉 🎆 🙌 best news I've heard in a while

**Comment by kevcenteno** [comment]
@lkfortuna Is there anyway we could accelerate availability for (popular) open source projects or get a stronger idea of when the windows+arm64 images will be generally available? I ask because this is yet another barrier to buying into the Windows on Arm ecosystem as a developer.  Having to set up multiple toolchains to compile all the open source tools that developers use is a headache for most (lazy-like-me) developers.  Sure, windows emulation is fine for now I suppose, but - again - I'm lazy and probably won't re-install my dev tools until I absolutely have to.

Tagging @ivcarreras @jamshedd for visibility and advocacy.

**Comment by johnnyshields** [comment]
Github team may we please get a comment on this?

**Comment by nbolton** [comment]
In case anyone is wondering how to get Git working on the Windows ARM64 runners...
```
      - name: Install Git
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          choco install -y --no-progress git
          echo "C:\Program Files\Git\cmd" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
```

**Comment by spyoungtech** [comment]
For those stumbling upon this wanting to quickly understand the current situation: ARM runners are here, in beta, but only for organizations and enterprises with a compatible subscription plan. You have to opt in to use the ARM runner, just like with [managing any other large runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/managing-larger-runners#networking-for-larger-runners). Many marketplace actions are, understandably, not compatible with this runner configuration, YMMV.

Short version: Under your organization settings in **Actions -> Runners** you can create a new github-hosted runner and you can now specify "Windows ARM64" for the platform. The only image available is the Windows 11 (Preview) partner image.

![image](https://github.com/user-attachments/assets/9650ff1b-1bd1-4323-b25e-5ef30add3151)

<details>
<summary> A few configurations are available </summary>

![image](https://github.com/user-attachments/assets/6e7c2c59-3fa6-4dda-b4d0-e867c24037da)

</details>

Be aware there are charges involved for this that are not covered by your included Actions minutes, even for public projects.

Hopefully in the future we see ARM64 runners become available to individual users and open source projects under included CI minutes. Until then, self-hosting continues to be the workaround for those who may not be able to reasonably leverage the above.

**Comment by johnnyshields** [comment]
@spyoungtech Thank you very much for this update. It strikes me as a bit backwards to rollout Windows ARM64 only for enterprise, because there isn't a ton you an enterprise do with Windows ARM64 until the core languages and libraries (many which are open source on Github) can support it in their respective CI. So it would be very nice if Github could flip it on at least for the public repos mentioned in this thread.

**Comment by RiadhKHEDHIRI** [comment]
I second @johnnyshields
![tweet-1823801071430721682](https://github.com/user-attachments/assets/76f1d676-01a0-4180-b8ff-f973c0be841f)

**Comment by lilith** [comment]
As an OSS developer, even though I own a snapdragon laptop, I can't afford to support windows on arm natively without github runner support. CI is the only way we can maintain so much.

**Comment by johnnyshields** [comment]
Update: ARM64 Linux and Windows runners are now in Paid GA: 
https://github.blog/changelog/2024-09-03-github-actions-arm64-linux-and-windows-runners-are-now-generally-available/

This still prevents the vast majority of OSS projects from using them--most can't afford to pay 😢

**Comment by lilith** [comment]
They still don't even come with pwsh, bash, git, or msvc build tools installed. No pre-installed software at all.

Takes 30+ min to install the compilers and prerequisites, so not usable anyway...

**Comment by erik-bershel** [comment]
> Daar GitHub Actions maintainers, is there anything you can share about arm64 runner availability for (large) OSS projects?

Hey @EwoutH! There is no new information at the moment. 😞  It will most likely appear on the :octocat: [GitHub blog](https://github.blog/changelog/label/runners/) like [here](https://github.blog/changelog/2024-06-03-actions-arm-based-linux-and-windows-runners-are-now-in-public-beta). 
Stay tuned! 🎧

**Comment by EwoutH** [comment]
Thanks for getting back so quickly! If I may ask, doesn't have Microsoft an interest in proving a smooth software experience for its Arm users? And doesn't that start with making sure proper tools are available for developers, including CI runners to build and test their packages? And isn't a huge amount of software dependent on OSS software?

Or is there an engineering capacity or hardware availability bottleneck? You probably have very solid reasons, but some insight will help create understanding among OSS maintainers.

Even just giving the largest 0.1% of OSS projects access to Arm64 runners will have a huge impact.

**Comment by johnnyshields** [comment]
Hmm.... 6 months after the big Snapdragon Elite ARM blitz, M$FT still not offering GH ARM runners. Does not bode well for the future of the platform.

**Comment by lilith** [comment]
I pay for an arm runner, but it doesn't even have git installed, it's a
blank OS. The hardware exists, but there's no image.

**Comment by kevcenteno** [comment]
> Hmm.... 6 months after the big Snapdragon Elite ARM blitz, M$FT still not offering GH Windows ARM runners. Does not bode well for the future of the platform.

Agreed.  I held off on buying a Windows ARM machine because of this issue.  Now on my way to the Apple store to buy a new M4 machine instead.

**Comment by lilith** [comment]
Arm64 is the future, based on battery/perf, but I will be very sad if msft
fumbles it once again for such silly reasons.

**Comment by EwoutH** [comment]
Let’s keep this conversation professional and on topic, and give the GitHub Action team some time to get back to us.

**Comment by jeremyd2019** [comment]
> I pay for an arm runner, but it doesn't even have git installed, it's a blank OS. The hardware exists, but there's no image.

I'd rather they prioritize making them available for free to OSS projects (heck, maybe a closed beta for large projects at first), and then we can quibble about what software is preinstalled.

**Comment by lilith** [comment]
It's pretty impossible to have runs complete before timing out when you
have to install pwsh/bash/visual studio/node/msvc/rust/git/etc from scratch
though and actions don't work. I suspect the lack of an image is actually
the constraint, since the hardware and capability exists, but an unusable
image, available free, would swamp their support more than just withholding
it. I speculate, of course.

Maybe the lack of windows aarch64 git.exe, docker issues, and similar tools
could be a partial blocker? It seems to work under emulation, though...

It's sad to see there's been no official response the last few months. Hard
to believe it matters if they won't offer any updates or if they're even
allocating resources to it.

I like my Snapdragon X laptop, and it's Rust compilation speed to battery
usage ratio is phenomenal. But... you can't ship what you can't test
automatically, especially with complex project trees that depend on CI.

**Comment by jaromil** [comment]
Hi, just a heads up from yet another OSS dev: was considering buying a new ARM64 surface laptop, but seeing there is not yet a CI runner I give up the idea since that would make me unable to use my own tools. Anyway, looking forward to 2025, keep it up and merry holidays everyone!

**Comment by oberrich** [comment]
> In case anyone is wondering how to get Git working on the Windows ARM64 runners...
> 
> ```
>       - name: Install Git
>         run: |
>           Set-ExecutionPolicy Bypass -Scope Process -Force
>           [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
>           iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
>           choco install -y --no-progress git
>           echo "C:\Program Files\Git\cmd" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
> ```

This did get Git working again but even with the `git.install`, `/GitAndUnixToolsOnPath` parameter and refreshing env it refuses to find `bash`.
Any idea how to get bash working again?

See https://github.com/delulusoft/phnt-rs/blob/8421a2c4a64658590cd7b848cdb5015284c72f22/.github/workflows/rust.yml#L25-L34

**Comment by michael-hawker** [comment]
Is this the proper tracking issue now? https://github.com/github/roadmap/issues/1098
