### ISSUE TITLE
Distribute Azure VM Image Builder Templates

### ISSUE THREAD

**Issue by JamieMagee** [actions/virtual-environments#811]
Is it possible to distribute [Azure VM image builder templates](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/image-builder-overview) for these images?

I had hoped for #176, but if that's not possible it should be possible to distribute the templates in a different form.

Looks like @danielsollondon is the most knowledgeable in this area.

**Comment by alepauly** [comment]
Hi @JamieMagee, that's an interesting idea. I have very little knowledge on templates but if we could get some help in understanding what needs to get done and how it would be maintained, we are definitely open considering it. I'll mark the issue as `community-feature` since we can't actively work on it due to priorities but hopefully others can help.

**Comment by ChengYen-Tang** [comment]
I really need the official image, the network in my area always fails to install, I'm almost crazy.

**Comment by miketimofeev** [comment]
Closing this for now as now progress was made throughout the year

**Comment by mario-d-s** [comment]
@miketimofeev can you elaborate please, what progress has been made here? I can't find any reference to such templates.

**Comment by MatthewSteeples** [comment]
Not sure what the comment would have been in reference to that long ago, but more recently there's Managed Pools to try: https://learn.microsoft.com/en-us/azure/devops/managed-devops-pools/?view=azure-devops

**Comment by mario-d-s** [comment]
@MatthewSteeples wow, that looks pretty good. I will probably abandon the plan then to start building VMSS images from this repo, in favor of that. Thanks for pointing it out!
