### ISSUE TITLE
Swift on macOS-latest has exit code 1

### ISSUE THREAD

**Issue by ProgramComputer** [actions/virtual-environments#832]
**Describe the bug**

When running Swift.yml in Actions CI on macOs-latest tests will pass, but Swift.yml will have exit code 1 causing build to fail.

**Area for Triage**: 
 Apple

**Question, Bug, or Feature?**: 

Bug
**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**

When running Swift.yml with passing tests on macOS-latest Swift’s exit code should be 0.

**Actual behavior**
Run the CI in example repo: https://github.com/ProgramComputer/Securinspect

**Comment by maxim-lobanov** [comment]
Hello @ProgramComputer , I think that issue is pretty clear from the error message that you have in build logs: 
![image](https://user-images.githubusercontent.com/16715858/81079081-bd2b0180-8ef7-11ea-80dc-d01cf07d1f0d.png)
`swift build`command should be run in folder where package manifest is located. Your repository doesn't contain `package.swift` file so command fails.
I have cloned your repo locally and it failed for me too.

**Comment by ProgramComputer** [comment]
@maxim-lobanov Thank You, I have resolved my issue.
