### ISSUE TITLE
Include Android emulator in Ubuntu images

### ISSUE THREAD

**Issue by mganandraj** [actions/virtual-environments#836]
**Tool information**
- Tool name: Android x86 Emulator from the Android SDK
- Tool license: Same as Android SDK
- Add or update? Add
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Currently the Ubuntu images include all the build toolchains but no emulators are included for running CI validations.
  - URL for tool's homepage: https://developer.android.com/

**Area for Triage**: Android

**Question, Bug, or Feature?**: "Feature"

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?** Yes

**Tool installation time in runtime**

**Are you willing to submit a PR?**
Yes

**Comment by andy-mishechkin** [comment]
This emulator is shipped by Apache 2.0 license

**Comment by maxim-lobanov** [comment]
Hello @mganandraj, thank you for your suggestion.
Considering the fact that android emulators are pretty huge, we don't have resources to pre-install and support android emulators on Ubuntu image for now. Probably, we will be able to revisit this decision in future if we see more interests for it and have resources to support it.

Emulators can be installed in runtime using the [android-emulator-runner](https://github.com/ReactiveCircus/android-emulator-runner) action (in case if you use GitHub Action).
Also emulators can be installed using the following code (it takes about 1 minute to install one particular emulator):
```
${ANDROID_HOME}/tools/bin/sdkmanager --install "system-images;android-29;google_apis_playstore;x86_64"
```

**Comment by mganandraj** [comment]
Hi @maxim,

Considering the size of the image, Is it a good practice to download and install them as part of CI validation, assuming double digit PRs each day ? Are there network caching layers to serve this kind of download patterns ?

Thanks
ANandraj

**Comment by maxim-lobanov** [comment]
We understand that it can be pretty painful to install Android emulators in runtime, especially if the number of builds is pretty huge.
We are trying to improve our images constantly and currently, our main focus is improving stability of our images and software that is already installed. It means that we have to be fairly picky right now about new software. 

> Are there network caching layers to serve this kind of download patterns ?

By default, no, but you can use [actions/cache](https://github.com/actions/cache) to cache android emulators folder. Potentially, It can speed up your builds because access to the cache is significantly faster than external sources.
