### ISSUE TITLE
Documentation for when prerelease images are available

### ISSUE THREAD

**Issue by StephenCleary** [actions/virtual-environments#847]
**Describe the bug**
I can't find a description for when/how prerelease images are rolled out, or if/how prelease images can be used in my actions before they roll out.

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

(possibly others)

**Expected behavior**
I'd like some way to know where in the pipeline a given release is in, and how likely/soon that release will be available.

The original specific problem I had was that Azure CLI 2.3.1 has a [bug where it won't include error details in its output](https://github.com/Azure/azure-cli/issues/12241); this [was fixed](https://github.com/Azure/azure-cli/pull/12848) >20 days ago and is not present in the current ([2.5.1](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.5.1)) release of Azure CLI.

However, only Azure CLI 2.3.1 is [available](https://github.com/actions/virtual-environments/blob/releases/ubuntu18/20200406/images/linux/Ubuntu1804-README.md) on `ubuntu-latest` (20200406.2), which is a month old at this point. The Ubuntu build just [takes the latest Azure CLI version](https://github.com/actions/virtual-environments/blob/f757c3eaa79d6acbd814eb2c4977e2de0664c7af/images/linux/scripts/installers/azure-cli.sh), and in fact the [newest Ubuntu build](https://github.com/actions/virtual-environments/blob/releases/ubuntu18/20200430/images/linux/Ubuntu1804-README.md) (20200430.1) does have Azure CLI 2.5.1.

So the problem is that it's not clear where the environment releases are in the rollout process. For this specific problem, it's not clear what's keeping 20200430.1 from being available and used for `ubuntu-latest`.

**Comment by maxim-lobanov** [comment]
Hello @StephenCleary ,
Actually, you can't switch between image versions. Let me clarify our deployment process a bit.

We have a huge number of VMs that we need to update and usually it takes 3-4 days to propagate new image to all VMs. Pre-release is created when deployment is started. And then pre-release is converted to release when the deployment is finished. Current deployment is in progress and we are expecting `20200430.1` to deploy to all VMs on Tue next week (Friday is deployment freeze).

As you can see from the previous releases, usually we deploy both Ubuntu and Windows image on weekly basis. The reason why the current image is not updated for a long time is that previously we had an incident with [free space](https://github.com/actions/virtual-environments/issues/709) on Ubuntu images. Also we had deployment freeze the most of this week due to [GitHub Satellite](https://githubsatellite.com/).

As I mentioned above, the new image with Azure CLI 2.5.1 should be available early next week. Thank you for your patience.
If it is your blocker, you can update Azure CLI in runtime using this code: `curl -L https://aka.ms/InstallAzureCli | bash` based on [official documentation](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest#install-or-update).

Please let me know if you have any other questions.

**Comment by StephenCleary** [comment]
Ah, [that](https://github.com/actions/virtual-environments/issues/709) makes perfect sense. Thanks!
