### ISSUE TITLE
Ubuntu 16.04 NewImage - go breaking change. 

### ISSUE THREAD

**Issue by rebecca-makar** [actions/virtual-environments#886]
**Describe the bug**
20200430.2- working on this image
20200512.2 - broke on this image
`
Using Go, older install for version 1.11: 
Here are docs showing the way I have had it set up, but I am using version 1.11.
It shows the path where the GOROOT directory is: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/go?view=azure-devops&tabs=go-older#set-up-go 

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
A description of what you expected to happen.
Symlink would point to version of go folder I have automated. 

**Actual behavior**
Symlink is going one more layer deep: 1.11.<X> but old documentation and way automation I have using it is just looking for `go: cannot find GOROOT directory: /usr/local/go1.11`

This broke from yesterday to today but I also saw that it was the new image. 

I saw this PR was the change: https://github.com/actions/virtual-environments/pull/848
It is a breaking change since it is expecting 1.11.<> 
Tagging below since I saw them on the PR:
@vsafonkin 
@alepauly

**Comment by maxim-lobanov** [comment]
Hello Rebecca,

We have moved location of Go versions to `/opt/hostedtoolcache` instead of `/usr/local/go*` to improve work of [Go tool task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/go-tool?view=azure-devops). Previously, this task always downloaded Go on-flight (even if version is pre-installed on image). After moving, Go task will be able to find pre-installed Go on image and it means that customers won't have to wait for downloading / installation Go in runtime.

I am sorry for breaking you with these changes. We didn't notify customers about it beforehand because based on [official documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/go?view=azure-devops&tabs=go-current#set-up-go), Go task is recommended way to setup Go 11.1+. Documentation still contains old way to setup Go manually, but this way is intended for Go < 11.1 and we don't have such versions on the image for now.

Is it possible for you to try to switch to the new approach and check if it works for you?
I will take care about updating documentation to make sure that customers are not confused with legacy approach.

**Comment by rebecca-makar** [comment]
Hi @maxim-lobanov 

I changed it to the setup of Go 11.1+, just had to play around with figuring out where the go get was installing the clone... I am manually updating some files to handle mock cases, once figured that out everything was good.

Thanks again!!  Closing this.
