### ISSUE TITLE
Update/Add [latex and friends: miktex]

### ISSUE THREAD

**Issue by FrancescElies** [actions/virtual-environments#894]
Related to #613, this might be closed because of the same reason, but I am opening an issue to see if there is any interest out there.

**Tool information**
- Tool name: [Miktex](https://miktex.org/)
- Tool license: [here](https://miktex.org/copying)
- Add or update? Add
- Desired version: 2.9
- Approximate size: around 880MB
- If this is an add request:
  - Brief description of tool: TeX/LaTeX 
  - URL for tool's homepage: https://miktex.org

**Area for Triage**:
Packages

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
It can but it would take too long in my opinion.

**Tool installation time in runtime**
Long

**Are you willing to submit a PR?**
With some guidance and if I get the priority at work to do that, sure.

**Comment by FrancescElies** [comment]
ℹ Downloading a zip package with [miktex portable](https://miktex.org/howto/portable-edition) unpacking it and adapting the PATH variable takes around 1 minute in the cloud.

**Comment by alepauly** [comment]
Hi @FrancescElies, thanks for the suggestion but considering the size of the package and cost/benefit of having it baked into the image, we won't add it at this time

**Comment by jmarrec** [comment]
@alepauly Whould the fact that it takes 25 minutes to install a miktex install on a windows instance prompt you to reconsider by any chance (trying my luck :)) ?

```
    - name: Install System dependencies and LaTeX
      shell: bash
      run: |
        set -x
        echo "Downloading MiKTeX CLI installer"
        # We download from a specific miror already # TODO: Should store this setup package somewhere ourselves
        curl -L -O https://ctan.math.illinois.edu/systems/win32/miktex/setup/windows-x64/miktexsetup-4.1-x64.zip
        unzip miktexsetup-4.1-x64.zip

        echo "Setting up the local package directory via download"
        ./miktexsetup_standalone --verbose \
            --local-package-repository=C:/MiKTeX-Repo \
            --remote-package-repository="https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/" \
            --package-set=complete \
            download

        echo "Installing from the local package directory previously set up"
        ./miktexsetup_standalone --verbose \
            --local-package-repository=C:/MiKTeX-Repo \
            --package-set=complete \
            --shared=yes \
            install

        echo "Adding MiKTeX bin folder to PATH and to GITHUB_PATH"
        echo "C:/Program Files/MiKTeX/miktex/bin/x64/" >> $GITHUB_PATH
        export PATH="/c/Program Files/MiKTeX/miktex/bin/x64/:$PATH"

        echo "Configuring MiKTeX to install missing packages on the fly"
        initexmf --admin --verbose --set-config-value='[MPM]AutoInstall=1'

        echo "Configure default mirror for packages"
        mpm --admin --set-repository="https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/"
        # Avoid annoying warning: "xelatex: major issue: So far, you have not checked for updates as a MiKTeX user."
        mpm --find-updates
        mpm --admin --find-updates
```

example run: https://github.com/jmarrec/EnergyPlus/runs/2876590566?check_suite_focus=true

**Comment by FrancescElies** [comment]
@jmarrec downloading miktex from azure artifacts or similar instead of Cpan I bet would speed up things.

**Comment by jmarrec** [comment]
This is probably true than CTAN is slower than paid services.

But note that it would require me hosting a separate instance of a ctan repo, or go through a complicated process of setting up some kind of archive of all the tar.lzma package archive I might need (then figure out the commands needed to actually make use of that, which I am attempting now and is definitely not trivial). In both case I also would need to have an azure artifact, or S3, or similar account, which I do not have.

I do not know to which extent you're familiar with how miktex and packages install on windows (and the miktexsetup_standalone, initexmf, mpm utilities, and the very confusing --admin flags for these given than GHA runs elevated), but it's definitely not easy/straightforward (to me at least), and it's been a major pain point of my CI setup. Your comment above about unpacking a miktex portable zip taking 1 minute is, IMHO, seriously downplaying the complexity, and the required time (both in actually making in work, then in github action runtime... what takes 25 minutes to run on windows will take about 2 min on Ubuntu via apt-get). Perhaps I missed an obvious solution, and if you have an example workflow that works and performs much better than this, I'm definitely all ears!

Anyways, I'm just mentioning the serious runtime penalty to see if this could be reconsidered for inclusion on the runners (which would solve all of my problems). That being said, if the answer is still that it won't be included, then that's fine and I'm on my own figuring it out :)

----

For context: I **do** want to build the PDF on windows. Because I want to ensure that it works. it's also one step in a complicated C++ workflow and I wish to keep my Linux, Mac and Ubuntus workflows separate because merging them in a matrix makes them way too complicated.

Also note that I was using the chocolatey miktex package previously, but it would always fail on Github Actions (and not locally) because the CTAN mirror it would pick by default would fail, hence why I've already gone the miktexsetup_standalone route to begin with so I could configure things with a more reliable CTAN mirror.

**Comment by FrancescElies** [comment]
My knowledge on how to install miktex and it’s packages is limited and hopefully I will keep it that way if I can avoid it. I would like to keep my head free from that kind of Baggage. 

I am in a similar situation. Complex build process and at the end a PDF needs to be produced. 

I avoid having miktex to install packages on the fly. In order to do that I downloaded miktex portable once and installed if I remember correctly the packages I need from the ui. Once downloaded locally I compressed the whole portable directory again with my dependencies and uploaded the whole thing to azure artifacs (luckily I don’t have to pay it myself, this is what we use at work). 
Summary: avoid network operations on third party stuff like the plague. 

If you are in an open source project, I’m not sure what to propose. In a closed source thing maybe pay some money to azure devops, s3 might help. 

I can hear your pain struggling to install stuff on windows. Chocolatey, well … it helps in some cases but I also had a bunch of other problems with it, I use locally but not in ci. 

I hope that helps. At the moment I am afraid I cannot send you a snippet of what we do, I would have to check if that would be ok.
