### ISSUE TITLE
Update/Add Windows Ruby - remove embedded MSYS2 installs

### ISSUE THREAD

**Issue by MSP-Greg** [actions/virtual-environments#930]
**Tool information**
- Tool name: **Ruby all versions**
- Tool license: **na**
- Add or update? **update ?**
- Desired version: **na**
- Approximate size: **smaller than current**

**Question, Bug, or Feature?**: Question

### Preface

This is a long post, as I've tried to explain the issue in a manner that (hopefully) will be clear to people unfamiliar with Windows Ruby.

### General Info

Windows images now have a stand-alone MSYS2 install.

All currently installed Windows Rubies are RubyInstaller2 (RI2) builds.  All are using the 'devkit' exe package (see packages for Ruby 2.7.1 at [oneclick/rubyinstaller2/releases/tag/RubyInstaller-2.7.1-1](https://github.com/oneclick/rubyinstaller2/releases/tag/RubyInstaller-2.7.1-1)), which includes an embedded minimal MSYS2 install (basic MSYS2 and MinGW gcc tools).

All RI2 builds (which started with Ruby 2.4.x) include vendored code to assist with MSYS2 tools.  One part of the that is the `ridk` CLI tool.  The other main part is code that hooks into 'gem install' to enable compiling extension gems.

Also, all RI2 Rubies are packaged with their own MinGW dlls, so they function without an MSYS2 installation.  If one wants to install an extension gem, then MSYS2 tools are required.

For quick example of Rubies functioning with the stand-alone MSYS2 install, please see an Actions workflow run at: [MSP-Greg/actions-msys2-pkgs/actions/runs/112803470](
https://github.com/MSP-Greg/actions-msys2-pkgs/actions/runs/112803470).  It hides the embedded MSYS2 install and then shows that Ruby works with the new stand-alone install.  Also, note that this workflow is using [actions/setup-ruby](https://github.com/actions/setup-ruby), not [ruby/setup-ruby](https://github.com/ruby/setup-ruby).

Each Ruby job has four steps:
* ridk version
* MSYS2 Size & Rename
* ridk version
* Install extension gem (requires MSYS2 gcc)

1. The first 'ridk version' step shows the 'msys2: path:' as embedded in the Ruby install folder.  See Ruby 2.7 job, which shows `C:\hostedtoolcache\windows\Ruby\2.7.1\x64\msys64`
2. The 'MSYS2 Size & Rename' step shows the size of all files in the 'msys2: path:' folder, and then renames the folder, which 'hides' it from the Ruby install.
3. The second 'ridk version' step shows the 'msys2: path:' as `c:\msys64`, which is the new stand-alone MSYS2 installation.
4. The 'Install extension gem (requires MSYS2 gcc)' step installs an extension gem (one requiring gcc), hence showing that the Ruby ridk code is correctly locating the stand-alone MSYS2 install.

### Benefits

The current embedded MSYS2 installs are about 1 GB, so removing them would save 4 x 1 GB.  I did not check the number of files.

The embedded MSYS2 installs become stale, but the frequent image refreshes will keep the stand-alone MSYS2 install more up to date.

### Negatives

The only negative example I can think of is that any Gems that are compiled with OpenSSL require that the version of the MinGW OpenSSL 'dev' package be the same version as what Ruby was built with.  Ruby 2.4 is built with 1.0.2, all newer versions use 1.1.1.  Separate embedded MSYS2 would easily allow for that.  I suspect this could be an issue on self-hosted runners, but I'm not sure.  As to normal GHA, there are custom actions that account for these package mismatches (installing the correct package based on Ruby version).

### Implementation

Two main options:

After recently finding https://github.com/actions/virtual-environments-packages, it is more apparent how the toolcache Rubies work.  The system could stay the same, and simple remove the `msys64` folder from the root Ruby folders.  In the action workflow above, I just renamed it for demo purposes.

The other option is to base the install on the RI2 base 7z package, e.g. `rubyinstaller-2.7.1-1-x64.7z`, which is simple to install and doesn't require removing any files.  These are the packages that [ruby/setup-ruby](https://github.com/ruby/setup-ruby) downloads and installs, regardless of whether a version match exists in the toolcache.

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by MSP-Greg** [comment]
Re the Ruby 2.7.1 package from https://github.com/actions/virtual-environments-packages, at:
https://github.com/actions/virtual-environments-packages/packages/110285

If you drill down into the package, you see 'rubyinstaller-2.7.1-1-x64.exe' and also 'tool.zip'.  The script install_to_tools_cache.ps1 seems to only uses tool.zip, so I'm not sure why the exe is included.

Anyway, looking at tool.zip (below), the two largest folders are `msys64` and `share`.  `msys64` is the embedded msys2 install, and `share` has 2k+ small html doc files.  In ruby/setup-ruby, the 7z cmd line excludes those to speed the extraction.  They could also be removed, as CI has no need for them:

<img src="https://user-images.githubusercontent.com/15081176/82760793-a6bbeb80-9dbb-11ea-9530-cae5f70f6203.png" alt="drawing" width="300rem"/>

**Comment by maxim-lobanov** [comment]
@MSP-Greg , Thank you for enhancement request.
What steps can we use to validate Ruby after removing embedded msys64 to make sure that system MSYS is used?

**Comment by MSP-Greg** [comment]
Something like the following (adapted to what you need)
```ps1
# devkit locates MSYS2 and adds to Ruby's path
if ($(ruby -rdevkit -e "puts %x[gcc --version]") -Match 'Built by MSYS2') {
  echo "found MSYS2 gcc by loading devkit"
} else {
  echo "can't find MSYS2 gcc by loading devkit"
}

# if the formatting of 'ridk version' changes, this might break
if ($(ridk version) -Match 'path: C:\\msys64') {
  echo "ridk version finds MSYS2 location"
} else {
  echo "ridk version DOESN'T find MSYS2 location"
}
```

Note that current gcc's installed on Actions output the following, and hence, don't match 'Built by MSYS2' used above:
```
C:\ProgramData\Chocolatey\bin\gcc.exe --version
  gcc.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
C:\Strawberry\c\bin\gcc.exe --version
  gcc.exe (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0
```

**Comment by MSP-Greg** [comment]
@maxim-lobanov

As to the code example, the first test is good enough.  The second one (ridk version) uses the same code as the first, and the important thing is that it finds the MSYS2 gcc.exe.

JFYI, MSYS2 just did a new release, from [20200517](https://github.com/msys2/msys2-installer/releases/tag/2020-05-17) to [20200522](https://github.com/msys2/msys2-installer/releases/tag/2020-05-22).

**Comment by 1480c1** [comment]
MSYS, MinGW, MSYS2, and mingw-w64 are all separate projects, so it would be best to make sure not to use the wrong word when describing something since it can confuse others too

MSYS: <http://www.mingw.org/wiki/MSYS>
- `MSYS is a collection of GNU utilities such as bash, make, gawk and grep to allow building of applications and programs which depend on traditionally UNIX tools to be present. It is intended to supplement MinGW and the deficiencies of the cmd shell.`

MinGW: <http://www.mingw.org/> and <https://osdn.net/projects/mingw/>
- `a contraction of "Minimalist GNU for Windows", is a minimalist development environment for native Microsoft Windows applications`
- Only produces 32-bit binaries [(at least as of now)](https://osdn.net/projects/mingw/ticket/37867)

MSYS2: <https://www.msys2.org/>
- `an independent rewrite of MSYS, based on modern Cygwin (POSIX compatibility layer) and MinGW-w64 with the aim of better interoperability with native Windows software. It provides a bash shell, Autotools, revision control systems and the like for building native Windows applications using MinGW-w64 toolchains.`

Mingw-w64: <http://mingw-w64.org/doku.php> and <https://sourceforge.net/projects/mingw-w64/>
- `Mingw-w64 is an advancement of the original mingw.org project, created to support the GCC compiler on Windows systems. It has forked it in 2007 in order to provide support for 64 bits and new APIs`
- Has 64-bit binary support
- Does not distrute their own official binaries, but they do have some ["personal"](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/) and [automated](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Automated%20Builds/) builds available
- [Reason why Mingw-w64 and MinGW were not merged](https://sourceforge.net/p/mingw/mailman/message/23108552/)

**Comment by 1480c1** [comment]
One such confusion, the comment section on the `mingw` package section of chocolatey <https://chocolatey.org/packages/mingw>

**Comment by maxim-lobanov** [comment]
We have switched Windows Ruby binaries in https://github.com/actions/virtual-environments/pull/2047 and now they don't have embedded MSYS2
