### ISSUE TITLE
Building Ubuntu VM setup locally

### ISSUE THREAD

**Issue by elshize** [actions/virtual-environments#931]
Hi, I found instructions on how to build a VM on Azure but I'd like to set it up locally so that I can easily test all my config before pushing to the repository. Would you mind helping out with that? Ideally, it would be nice if there was a docker image one can download, or at least some kind of script setting up the environment, installing packages, etc. Without that, it's rather difficult to guess what will or will not work, and I end up making changes, pushing, then fixing, then pushing... you get the idea.

I would very much appreciate some help with setting it up or finding other resources that could help me.

**Comment by Darleev** [comment]
Hello @elshize,
There was a separate [project in the past](https://hub.docker.com/_/microsoft-azure-pipelines-vsts-agent), where it was possible to build separate agent in docker image for local testing. Currently, in order to build local machine with pre-installed software on your own, I see only one way:
- Take [installation scripts](https://github.com/actions/virtual-environments/tree/master/images) for windows/linux
- Perform commands one by one, according to configuration files:
[Ubuntu 16](https://github.com/actions/virtual-environments/blob/master/images/linux/ubuntu1604.json)
[Ubuntu 18](https://github.com/actions/virtual-environments/blob/master/images/linux/ubuntu1804.json)
[Windows 2019](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Azure.json)
[Windows 2016](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Azure.json)
Also, it is possible to build your own image using [Packer](https://www.packer.io) and how you have already mentioned, you can use separate virtual machine with pre-installed software and perform all required tests in it.

**Comment by elshize** [comment]
Thanks @Darleev, this helps a lot. Just to clarify, since I'm not familiar with Packer, this can be used to set up a VM outside of cloud, as in my local desktop for instance?

**Comment by Darleev** [comment]
@elshize for local testing, you can use the following approaches:
[VMware](https://www.packer.io/docs/builders/vmware/)
[Hyper-V](https://www.packer.io/docs/builders/hyperv/)
[VirtualBox](http://packer.io/docs/builders/virtualbox/)
In other words, need to build image for one of these virtual environments and deploy as virtual machine locally.

**Comment by elshize** [comment]
Thanks, sounds good. I should be able to take it from here. I appreciate you taking the time to help, thanks a bunch!

**Comment by Darleev** [comment]
@elshize I'm going to close the issue. 
In case of any questions, please let us know.

**Comment by elshize** [comment]
@Darleev Thanks again for your help!
