### ISSUE TITLE
Update/Add [Flutter]

### ISSUE THREAD

**Issue by rishabhdeepsingh** [actions/virtual-environments#961]
**Tool information**
- Tool name: flutter
- Tool license: BSD 3-Clause
- Add or update? Add
- Desired version: latest
- Approximate size: 
- If this is an add request:
  - Brief description of the tool: Flutter is Google's SDK for crafting beautiful, fast user experiences for mobile, web, and desktop from a single codebase. Flutter works with existing code, is used by developers and organizations around the world, and is free and open source.
  - URL for tool's homepage: https://github.com/flutter/flutter

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
No.

**Tool installation time in runtime**
We just need to clone and build some libraries. Approx 5min

**Are you willing to submit a PR?**
I can try.

**Comment by Darleev** [comment]
Hello @rishabhdeepsingh,
We had [a similar request ](https://github.com/actions/virtual-environments/issues/21) in the past, but currently, we are not planning to add it to the images. In order to install flutter in runtime, you can use a [solution described in the documentation.](https://github.com/marketplace/actions/flutter-action)
In case of any questions, please let us know.
