### ISSUE TITLE
Add vault binary

### ISSUE THREAD

**Issue by awolde** [actions/virtual-environments#990]
**Tool information**
- Tool name:  HashiCorp Vault
- Tool license: OSS
- Add
- Desired version: Whatever is the latest
- Approximate size: 100MB
- If this is an add request:
  - Brief description of tool: Used to read secrets from Vault server
  - URL for tool's homepage: https://www.vaultproject.io/downloads

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
yes

**Tool installation time in runtime**
couple of seconds 

**Are you willing to submit a PR?**
yes

**Comment by maxim-lobanov** [comment]
Hello, as a possible work around, tool can be installed in runtime pretty quick:
```
# macOS (takes 15 seconds)
brew install vault
vault --version

# Windows (takes 24 seconds)
choco install vault
vault --version

# Ubuntu (takes 4 seconds)
wget https://releases.hashicorp.com/vault/1.4.2/vault_1.4.2_linux_amd64.zip -O "vault.zip"
unzip "vault.zip"
./vault --version
```

**Comment by awolde** [comment]
Thanks @maxim-lobanov. Currently I'm using docker container to run vault commands, but it seems like wget might be faster. Will check.

**Comment by alepauly** [comment]
Hi @awolde, while this was requested in the past in #24 (by @rtselizondo) it still not a common request. My suggestion would be to build an Action that does the install for you. This simplifies it but also it would make it so that if we add it in the future, the Action can detect and move along with little to no effect. We'll leave this issue open for now so that others can vote up if this is something that would be beneficial to their workflows. Thanks!
